samtools/htsjdk

- src/java/htsjdk/variant/vcf/VCFConstants.java
- src/java/htsjdk/variant/vcf/VCFStandardHeaderLines.java
I tried to remove everything that's not in the VCF spec, but AD is tightly coupled with VariantContext and would break too much code to remove.  Otherwise, I believe that all non-standard annotations have been removed
> Removed GATK-specific constants from VCFConstants

- src/java/htsjdk/samtools/SAMFileReader.java
- src/java/htsjdk/samtools/SamReader.java
- src/java/htsjdk/samtools/SamReaderFactory.java
this is to address #161 
I also fixed a completely incorrect comment for SamReader.type()
For some reason there was a transient build failure relating to `RelativeIso8601DateTest`.  I reran the build without problem, but there seems to be some edge case where one of these tests is failing at some random time.  (I clicked rerun without recording more details thinking I could still access the old build.  I can't figure out how to get at it now though.)
> adding getResourceDescription() to SamReader

- .idea/modules/htsjdk.iml
- build.sbt
Quick fix to avoid artifact naming collisions for javadocs/srcs etc.
> Fix artifact names.

- src/java/htsjdk/samtools/SAMRecord.java
It throws unsupported operation exception.
This is useless and confusing.  It it's there for backwards compatibility (which is probably even worse than removing it because programs fail at run time) it should be deprecated and then removed after whatever delay is required.
> removing SAMRecord.setAlignmentEnd()

- src/java/htsjdk/samtools/BAMFileReader.java
- src/java/htsjdk/samtools/CRAMFileReader.java
- src/java/htsjdk/samtools/SAMFileReader.java
- src/java/htsjdk/samtools/SAMTextReader.java
- src/java/htsjdk/samtools/SamReader.java
it was in the deprecated `SAMFileReader` which is confusing especially since it depends on `PrimitiveSamReader` which is in `SamReader`
updated a few out of date documentation strings
> Moving ReaderImplementation to SamReader

- src/java/htsjdk/samtools/SAMRecord.java
- src/java/htsjdk/samtools/filter/IntervalFilter.java
- src/java/htsjdk/samtools/util/Interval.java
- src/java/htsjdk/samtools/util/IntervalList.java
- src/java/htsjdk/samtools/util/IntervalListReferenceSequenceMask.java
- src/java/htsjdk/samtools/util/IntervalTreeMap.java
- src/java/htsjdk/samtools/util/IntervalUtil.java
- src/java/htsjdk/samtools/util/Locatable.java
- src/java/htsjdk/samtools/util/OverlapDetector.java
- src/java/htsjdk/samtools/util/SamRecordIntervalIteratorFactory.java
- src/java/htsjdk/samtools/util/SimpleInterval.java
- src/java/htsjdk/tribble/Feature.java
- src/java/htsjdk/tribble/SimpleFeature.java
- src/java/htsjdk/tribble/TabixFeatureReader.java
- src/java/htsjdk/tribble/TribbleIndexedFeatureReader.java
- src/java/htsjdk/tribble/bed/BEDFeature.java
- src/java/htsjdk/tribble/bed/SimpleBEDFeature.java
- src/java/htsjdk/tribble/dbsnp/OldDbSNPCodec.java
- src/java/htsjdk/tribble/dbsnp/OldDbSNPFeature.java
- src/java/htsjdk/tribble/example/ExampleBinaryCodec.java
- src/java/htsjdk/tribble/gelitext/DiploidGenotype.java
- src/java/htsjdk/tribble/gelitext/GeliTextCodec.java
- src/java/htsjdk/tribble/gelitext/GeliTextFeature.java
- src/java/htsjdk/variant/variantcontext/VariantContext.java
- src/tests/java/htsjdk/samtools/util/SimpleIntervalTest.java
- src/tests/java/htsjdk/tribble/BinaryFeaturesTest.java
- src/tests/java/htsjdk/tribble/dbsnp/OldDbSNPCodecTest.java
- src/tests/java/htsjdk/tribble/gelitext/GeliTextTest.java
Renaming htsjdk.samtools.util.Interval -> NamedInterval which now extends the minimal Interval
extracting out a minimal genomic interval class from and naming that Interval
SAMRecord implements HasGenomicInterval
Feature implements HasGenomicInterval
renaming classes that are based on NamedInterval
renaming htsjdk.tribble.index.interval.Interval to FileInterval
This is motivated by the need to have a common interface to work with tribble `Feature` and `SAMRecord` for location based caching purposes. 
It's also a first step into integrating the the many interval classes that htsjdk, picard,  and GATK have and pushing functionality into a common base class.  See https://github.com/broadinstitute/hellbender/issues/100   and https://github.com/broadinstitute/hellbender/issues/159
@droazen …
> creating a Locatable interface

- src/java/htsjdk/samtools/BinaryTagCodec.java
I'd like to be able to use this codec in CRAM. Is there a particular reason for this class to be package-private?
> Expose BinaryTagCodec

- src/java/htsjdk/samtools/SAMFileHeader.java
- src/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/java/htsjdk/samtools/util/SequenceUtil.java
- Moved PgIdGenerator from Picard-public to here 
- Fixed a small bug in SAMRecordSetBuilder (didn't add the NM tag which then fails validation)
Needed for a new tool in Picard (Position-based downsampling)
> Yf geometrical downsampling

- src/java/htsjdk/variant/variantcontext/CommonInfo.java
Issue #841, Prevent negative zeros -0 in output vcf files, prescribed
adding 0.0 to the PHRED scaled score result. @vdauwera, @ronlevine indicated to implement the updates in the HTSJDK repo.
> Added the constant 0.0 to the PHRED scaled score (floating-point) result to prevent negative zero results; see issue in gatk-unstable 841

- src/java/htsjdk/variant/variantcontext/JEXLMap.java
- src/tests/java/htsjdk/variant/variantcontext/VariantJEXLContextUnitTest.java
In order to use the "FT" flag in JEXL expressions, I thought it would be a good idea to add them to the JEXL map.  I needed to use this flag in GATK's GenotypeConcordance tool to set genotypes that fail genotype-level filters to no-call.
I propose the following:
- Add the meta-tag 'isPassFT' which is true when g.isFiltered() is false.  (NOTE: I believe isFiltered is already available at the variant level; I'm also open to using "isFailFT" if that's more intuitive)
- Add the VCFConstants.GENOTYPE_FILTER_KEY (FT) to the JEXL map.  If the FT key is not present or is "PASS" (and therefore not present in g.getFilters()), manually set this entry to PASS.
> Added Genotype Filters to JEXL Map

- src/java/htsjdk/samtools/BAMIndexer.java
this fixes a small bug in the output of the BamIndexer which presents itself on large BAMs.,
> fixed an overflow bug in the output when indexing large bam

- src/java/htsjdk/samtools/AbstractBAMFileIndex.java
- src/java/htsjdk/samtools/BAMFileReader.java
- src/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/java/htsjdk/samtools/util/AbstractAsyncWriter.java
- src/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/java/htsjdk/samtools/util/BlockGunzipper.java
- src/java/htsjdk/samtools/util/IOUtil.java
- src/java/htsjdk/samtools/util/SortingLongCollection.java
- src/java/htsjdk/samtools/util/ftp/FTPUtils.java
- src/java/htsjdk/tribble/BinaryFeatureCodec.java
- src/java/htsjdk/tribble/TabixFeatureReader.java
- src/java/htsjdk/tribble/TribbleIndexedFeatureReader.java
- src/java/htsjdk/tribble/example/CountRecords.java
- src/java/htsjdk/tribble/readers/AsciiLineReaderIterator.java
- src/java/htsjdk/tribble/readers/LineIteratorImpl.java
- src/java/htsjdk/tribble/readers/LineReaderUtil.java
- src/java/htsjdk/tribble/readers/TabixIteratorLineReader.java
- src/java/htsjdk/variant/variantcontext/writer/BCF2Writer.java
- src/java/htsjdk/variant/variantcontext/writer/IndexingVariantContextWriter.java
- src/java/htsjdk/variant/variantcontext/writer/VCFWriter.java
- src/java/htsjdk/variant/variantcontext/writer/VariantContextWriterFactory.java
- src/java/htsjdk/variant/vcf/VCFRecordCodec.java
Many places in the code directly throw RuntimeException, especially under circumstances where a more specialized exception type would be informative. In particular, cases where a checked IOException is being replaced with RuntimeException now throw RuntimeIOException.
(I haven't included any of the uses in the CRAM code at this stage since it looks to be under fairly rapid development)
> Use RuntimeIOException instead of RuntimeException where appropriate

- src/java/htsjdk/samtools/AbstractSAMHeaderRecord.java
- src/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/tests/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
- testdata/htsjdk/samtools/roundtrip.sam
The HashMap implementation has changed in Java8 so the iteration order is different with respect to earlier Java versions. This results in SAM header attribute ordering changing, as they are currently being inserted into a regular HashMap. This PR swaps to using a LinkedHashMap so that the attributes are now maintained in insertion-order.
> Consistent header order

- src/java/htsjdk/variant/vcf/VCFCompoundHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFContigHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFHeader.java
- src/java/htsjdk/variant/vcf/VCFHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFSimpleHeaderLine.java
- src/tests/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
This was missed in the previous pull request to make SAM/Variant
records Serializable. We want to be able to serialize VCFHeaders
just as we do SAMFileHeaders
> Make VCFHeader Serializable

- src/java/htsjdk/samtools/util/IntervalList.java
- src/tests/java/htsjdk/samtools/util/IntervalListTest.java
Contig must be in header. Note that one could still forcefully modify the underlying dictionary, so the protection is only partial.
Removed protection code from the "padding" function since now contig should be in header.
> Added checks to adding an interval to an IntervalList

- src/java/htsjdk/tribble/util/ParsingUtils.java
- src/java/htsjdk/variant/vcf/AbstractVCFCodec.java
- src/tests/java/htsjdk/tribble/util/ParsingUtilsTest.java
This is an alternative to fix to #229 (in addition to those proposed under #246 and #241.
A quick check gives comparable performance of this implementation of ParsingUtils.split compared to String.split on Oracle JDK 7&8 and significantly better performance of this ParsingUtils.split compared to String.split on Oracle JDK 6.
> Split by char to remove some hard limits in AbstractVCFCodec

- src/java/htsjdk/variant/vcf/VCFHeader.java
- src/tests/java/htsjdk/variant/variantcontext/writer/VCFWriterUnitTest.java
- src/tests/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
There was a nasty bug in VCFHeader that caused newly-added header lines
to only be added to type-specific lookup tables and not to the master list
of header lines. This meant that new lines got silently dropped when writing
a modified VCFHeader back out via VCFWriter.
Fixed the issue and added comprehensive unit tests for VCFHeader.addMetaDataLine().
Also attempted to improve documentation and method naming a bit in an
effort to avoid future bugs like this. Eg., there was a method "loadVCFVersion()"
that actually REMOVED the vcf version lines!
> Fix catastrophic bug in VCFHeader that caused newly-added header lines to be silently dropped

- src/java/htsjdk/tribble/AsciiFeatureCodec.java
- src/java/htsjdk/tribble/FeatureCodec.java
- src/java/htsjdk/variant/bcf2/BCF2Decoder.java
- src/java/htsjdk/variant/bcf2/BCF2Type.java
- src/java/htsjdk/variant/bcf2/BCF2Utils.java
- src/java/htsjdk/variant/utils/GeneralUtils.java
- src/java/htsjdk/variant/variantcontext/Allele.java
- src/java/htsjdk/variant/variantcontext/FastGenotype.java
- src/java/htsjdk/variant/variantcontext/Genotype.java
- src/java/htsjdk/variant/variantcontext/GenotypeBuilder.java
- src/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
- src/java/htsjdk/variant/variantcontext/GenotypesContext.java
- src/java/htsjdk/variant/variantcontext/VariantContext.java
- src/java/htsjdk/variant/variantcontext/VariantContextBuilder.java
- src/java/htsjdk/variant/variantcontext/VariantContextUtils.java
- src/java/htsjdk/variant/variantcontext/writer/BCF2FieldEncoder.java
- src/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/java/htsjdk/variant/vcf/VCFEncoder.java
- src/java/htsjdk/variant/vcf/VCFFilterHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFFormatHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFInfoHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFSimpleHeaderLine.java
- src/java/htsjdk/variant/vcf/VCFStandardHeaderLines.java
These changes are to documentation only, and the vast majority are just formatting changes. These are not complete (there are still some `<code>` tags that could be included) but leave the docs for the whole package in a usable state. The Javadocs generate under my Eclipse version with no errors (though there are still warnings).
> Javadoc formatting improvements for htsjdk.variant.* packages

- src/java/htsjdk/variant/variantcontext/Allele.java
- src/java/htsjdk/variant/vcf/AbstractVCFCodec.java
- src/java/htsjdk/variant/vcf/VCFConstants.java
- src/tests/java/htsjdk/variant/variantcontext/AlleleUnitTest.java
Partial solution for https://github.com/broadinstitute/gsa-unstable/issues/998
Summary of code changes:
**Allele.java**
* ctor - created the SPAN_DEL allele
* create() - added case statement for * (spanning deletion)
* added final before method arguments
**AbstractVCFCodec.java**
* changed length() == 0 to isEmpthy()
**VCFConstants.java**
* added SPANNING_DELETION_ALLELE
**AlleleUnitTest.java**
* added testCreatingSpanningDeletionAlleles, testBadNoCallAllele and testBadSpanningDeletionAllele
* In testCreatingSpanningDeletionAlleles, I am not sure if the the spanning deletions should be processed like a no-call,  having no bases (see *Allele.Allele(final byte[] bases, final boolean isRef)*)
> Rhl allele rep span dels

- src/java/htsjdk/variant/variantcontext/Allele.java
- src/java/htsjdk/variant/vcf/AbstractVCFCodec.java
- src/tests/java/htsjdk/variant/vcf/AbstractVCFCodecTest.java
…kAllele()
If isRef is not passed, acceptableAlleleBases(final String bases)  is used instead of acceptableAlleleBases(final String bases, boolean isReferenceAllele). This version sets isReferenceAllele to true. For the case of "*",  reference allele is not acceptable and will generate an exception.
> Pass isRef to Allele.acceptableAlleleBases() in AbstractVCFCodec.checkAllele()

- .travis.yml
travis claims that dispatch is faster with the sudoless container builds
> setting travis to use the containerized build

- src/java/htsjdk/variant/variantcontext/VariantContextUtils.java
This is a fix for the API. The method signature should use interfaces not concrete classes to allow more flexibility in client code. This is a backwards compatible change - callers are unaffected and it's a static method so no one can override it.
> API VariantContextUtils.initializeMatchExps fixed to use interfaces

- .travis.yml
We're having constant failures since I moved us to the travis sudoless build.  Until travis fixes whatever is going on on their end I think we should revert it.  Sorry for the hassle.  Should fix #276 but we go back to having slow dispatch.
> moving back to travis non-containerized build

- src/java/htsjdk/samtools/util/AbstractProgressLogger.java
- src/java/htsjdk/samtools/util/ProgressLogger.java
- src/java/htsjdk/samtools/util/ProgressLoggerInterface.java
Pulled out an AbstractProgressLoger and refactored project logger to implement that.
This allows other implementations of AbstractProgressLogger that easily substitute a different logging system other than the Picard built in, without having to reimplement the existing logic.
> Refactor ProgressLogger for extensibility

- src/java/htsjdk/variant/variantcontext/CommonInfo.java
- src/java/htsjdk/variant/variantcontext/VariantContext.java
This pull-request contains a new utility function getAttributeAsList in ` src/java/htsjdk/variant/variantcontext/CommonInfo.java `  that always return the value as a java.util.List (empty list if the key is not found, List is the value if a List or an array, or as a ollections.singletonList . The method is also available in  src/java/htsjdk/variant/variantcontext/VariantContext.java  .
I use this function to safely loop over the value(s) in an INFO field.
```java
for(Object annotation : variantContext.getAttributeAsList("ANN"))
{
//...
}
```
> added getAttributeAsList in CommonInfo and VariantContext

- src/java/htsjdk/samtools/SAMFlag.java
- src/java/htsjdk/samtools/SAMRecord.java
- src/tests/java/htsjdk/samtools/SAMFlagTest.java
This pull request contains a new enum htsjdk.samtools.SAMFlag describing the available SAM flags. It can be used in a GUI, HTML form, menu... to display the available flags...
SAMFlag contains a static method returning the java.util.Set for a given integer
```java
public static Set<SAMFlag> getFlags(int flag)
```
I've added a small shortcut in src/java/htsjdk/samtools/SAMRecord.java
```java
public final Set<SAMFlag> getSAMFlags() {
return SAMFlag.getFlags( this.getFlags() );
}
```
I've added a test under src/tests/java/htsjdk/samtools/SAMFlagTest.java
> enum describing SAM FLAG (for gui/ menu / etc... )

- src/java/htsjdk/tribble/AbstractFeatureCodec.java
- src/java/htsjdk/tribble/FeatureCodec.java
- src/java/htsjdk/tribble/gelitext/GeliTextCodec.java
remove default implementation of FeatureCodec.canDecode to enforce implementation in concrete classes
> remove default implementation of FeatureCodec.canDecode 

- src/java/htsjdk/samtools/metrics/MetricBase.java
- src/java/htsjdk/samtools/util/FormatUtil.java
- src/tests/java/htsjdk/samtools/metrics/MetricBaseTest.java
- src/tests/java/htsjdk/samtools/metrics/MetricsFileTest.java
I split this into 2 commits, the first should be uncontroversial, the second I want to make sure no one objects too.
Commit 1:
Fix a bug in the implementation of `hashCode()` in `MetricsBase` it was crashing if any values were `null`.
Commit 2: 
Fix what I consider a bug in the `equals` method of `MetricBase`
Currently, the equality is exact equality with respect to floating point numbers.  However, when written to disk a MetricsBase has limited floating point precision, so writing something to disk and reading it back in will sometimes not equal the original file. I've altered the `equality` and `hashCode` methods to compare by using the same representation of floating point numbers as is written to disk.  This is technically backwards compatibility breaking, but I think the current …
> Fix 2 bugs in MetricsBase

- src/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
Fixes https://github.com/broadinstitute/gsa-unstable/issues/1104
In getSubsequenceAt(), was throwing an IllegalArgumentException for a negative capacity in ByteBuffer.allocate(capacity). This was due to overflowing an int for (length % basesPerLine + 2) * bytesPerLine. Casting to a long avoids this problem.
> Fix overflow during buffer creation

- src/java/htsjdk/samtools/util/BlockCompressedOutputStream.java
- src/java/htsjdk/samtools/util/IOUtil.java
that GZIP file are opened with. Support for this already existed, but
the level was hardcoded to use Defaults.COMPRESSION_LEVEL (=5).
> Added IOUtil.setDefaultCompressionLevel() to set the compression level

- build.xml
The Implementation-Version value in the MANIFEST file of htsjdk JAR file was using a wrong (non existent) property, and so was not even expended in the MANIFEST file.
> Fix typo to get htsjdk version the jar

- build.xml
Javadoc commits on the **gh-pages** branch (such as 738728d0376fc912a527b35b08a6accc932fad41) are illegible as all 1,300+ HTML files have differences like
```diff
<HTML>
<HEAD>
-
+
<TITLE>
API Help (HTSJDK API Documentation)
</TITLE>
-<META NAME="date" CONTENT="2015-07-27">
+<META NAME="date" CONTENT="2015-08-11">
<LINK REL ="stylesheet" TYPE="text/css" HREF="stylesheet.css" TITLE="Style">
```
This makes it pretty much impossible to see what actually **has** changed in these commits.  As most of the files haven't really changed, dropping the misleading `<META NAME="date" …>` would not be a loss to those looking at the web pages.
> Suppress javadoc generation timestamp comments

- src/java/htsjdk/samtools/util/StringUtil.java
Currently when presented with a SAM file with a record with an empty QNAME (which is not valid by SAMv1.pdf), Picard tools report
> SAMFormatException: Error parsing text SAM file. Not enough fields
but in fact the record has plenty of fields.  With this fix, they instead report e.g.
> `$` picard SamFormatConverter I=qnames-empty.sam O=qnames-empty-picard.bam
> SAMFormatException: Error parsing text SAM file. Empty field at position 0 (zero-based)
which is more accurate.  Example SAM file:
```
@SQ	SN:chr1	LN:5000
@RG	ID:foo	SM:bar	PL:ILLUMINA
4	*	0	0	*	*	0	0	ATGC	????	RG:Z:foo
```
> Improve empty QNAME error message

- src/java/htsjdk/samtools/SAMTag.java
- src/java/htsjdk/samtools/SAMUtils.java
- src/java/htsjdk/samtools/filter/OverclippedReadFilter.java
- src/tests/java/htsjdk/samtools/filter/OverclippedReadFilterTest.java
* Copy OverclippedReadFilter from GATK, so we can use it for detecting cross-species contamination.
* Add the ability to un-map a read but preserve original mapping info in the tags.
* Add two new tags - FT (read filter reason) and OF (original flags), which I will petition to get added to the SAM spec, per request from @yfarjoun
> Add OverclippedReadFilter and new tags

- .travis.yml
- build.xml
This change allows submitters to once again see which tests are failing in
their branches via travis.
> Set TestNG verbosity back to 2, and reduce log file size by grepping out PASSED: lines.

- .travis.yml
- src/tests/java/htsjdk/variant/bcf2/BCF2UtilsUnitTest.java
- src/tests/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
The VCFHeader tests were dumping extremely large String representations of VCFHeaders
to the TestNG log due to the way they were using DataProviders -- this comprised
the vast majority of htsjdk test output. This refactors these tests to produce
much less output.
With this change, grepping out the "PASSED:" lines should no longer be necessary
(this approach didn't work well anyway, since it didn't correctly propagate the
TestNG exit status to travis).
> Make the VCF/BCF Header tests less chatty

- src/java/htsjdk/samtools/SAMTag.java
- src/java/htsjdk/samtools/SAMUtils.java
Add OR (original RNAME) tag and use it when we call ```makeReadUnmappedWithOriginalTags```.
> Set original RNAME when unmapping reads

- src/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/tests/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
Fix a bug where once you've called clearOptions followed by setOption on any VariantContextWriterBuilder, subsequent calls to clearOptions on any VariantContextWriterBuilder set the options from the previous setOption calls instead of clearing the options, due to a shared reference to a mutable set.
> Fix VariantContextWriterBuilder.clearOptions bug.

- src/java/htsjdk/samtools/BinaryTagCodec.java
- src/java/htsjdk/samtools/CRAMFileWriter.java
- src/java/htsjdk/samtools/CRAMIterator.java
- src/java/htsjdk/samtools/SAMRecord.java
- src/java/htsjdk/samtools/SAMUtils.java
- src/java/htsjdk/samtools/TextTagCodec.java
- src/java/htsjdk/samtools/cram/build/ContainerParser.java
- src/java/htsjdk/samtools/cram/encoding/reader/CramRecordReader.java
- src/java/htsjdk/samtools/cram/structure/ReadTag.java
- src/java/htsjdk/samtools/util/BinaryCodec.java
- src/tests/java/htsjdk/samtools/CRAMEdgeCasesTest.java
- src/tests/java/htsjdk/samtools/SAMIntegerTagTest.java
- src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java
- src/tests/java/htsjdk/samtools/SamSpecIntTest.java
- src/tests/java/htsjdk/samtools/cram/structure/ReadTagTest.java
replaced exception when reading unsigned int in ReadTag with a direct conversion to long
> unsigned int is backed by a long value

- src/java/htsjdk/samtools/BAMRecord.java
- src/java/htsjdk/samtools/BAMRecordCodec.java
- src/java/htsjdk/samtools/CRAMFileWriter.java
- src/java/htsjdk/samtools/DefaultSAMRecordFactory.java
- src/java/htsjdk/samtools/MergingSamRecordIterator.java
- src/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/java/htsjdk/samtools/SAMFileWriterImpl.java
- src/java/htsjdk/samtools/SAMRecord.java
- src/java/htsjdk/samtools/SAMRecordCoordinateComparator.java
- src/java/htsjdk/samtools/SAMRecordDuplicateComparator.java
- src/java/htsjdk/samtools/SAMUtils.java
- src/java/htsjdk/samtools/SamPairUtil.java
- src/java/htsjdk/samtools/cram/build/Sam2CramRecordFactory.java
- src/java/htsjdk/samtools/filter/IntervalFilter.java
- src/java/htsjdk/samtools/util/AbstractProgressLogger.java
- src/tests/java/htsjdk/samtools/BAMFileWriterTest.java
- src/tests/java/htsjdk/samtools/CramFileWriterTest.java
- src/tests/java/htsjdk/samtools/MergingSamRecordIteratorTest.java
- src/tests/java/htsjdk/samtools/SAMFileReaderTest.java
- src/tests/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
- src/tests/java/htsjdk/samtools/SAMRecordDuplicateComparatorTest.java
- src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java
- src/tests/java/htsjdk/samtools/SAMTextWriterTest.java
- src/tests/java/htsjdk/samtools/SamReaderFactoryTest.java
- This is the first pass of improving null SAMFileHeader support. There are some TODOs inline with questions.
- Once we have agreement on those, the next pass will be to find all the places that call getReferenceIndex/getReferenceName and the mate analogs internally and make sure they do something reasonable with the new sentinel values.
- The existing doc seems to already indicate that the header does not have to be set. We may want to add more detail there, but I've updated the doc for the individual methods, and will clean those up
again once we have resolution on the rest of the contract (ie null value handling, etc.)
- I chose to return a MISSING_HEADER validation error when validating records. Not sure if thats what  we want.
- The existing implementation silently allows the caller …
> Improve handling of null SAMFileHeaders in alignment records.

- src/java/htsjdk/samtools/util/BinaryCodec.java
When converting an unsorted SAM to a sorted BAM with index creation on a NAS i noticed that the time it took was longer than expected.
Profiling revealed that almost all the time was spent in the BinaryCodec write methods.
Using buffered streams cuts the time required for that operation in half. 
This is for my use case where the files where stored on a NAS. The speed gain on a local HD or SSD is much lower.
But as i often use code like that where the data is not stored locally, but on a network drive, this will help to speed up some operations.
> Use buffered streams in binary codec to be much faster on network drives

- src/java/htsjdk/samtools/util/DiskBackedQueue.java
- src/tests/java/htsjdk/samtools/util/DiskBackedQueueTest.java
- src/tests/java/htsjdk/samtools/util/SortingCollectionTest.java
spilled to disk and have started removing records from RAM, or whenever
we start removing records from disk.  The pathology was that we would
let callers add if there was any room in ram, regardless if we had
spilled records to disk, thus causing records to become out of order.
If the entire queue is empty, we set canAdd to true again.  Added test
to make sure an exception is thrown if we add when we should not.
See: https://github.com/broadinstitute/picard/issues/327
@bradtaylor
> the disk backed queue should set "canAdd" to false whenever we have

- src/java/htsjdk/samtools/CRAMFileWriter.java
- src/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/java/htsjdk/samtools/SamFileValidator.java
- src/tests/java/htsjdk/samtools/CRAMFileWriterWithIndexTest.java
- src/tests/java/htsjdk/samtools/CramFileWriterTest.java
- src/tests/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
These are proposed changes for issues discovered when adding CRAM file tests to GATK4. However, we really need to resolve the policy issue about whether/how to require references for CRAM files (partly being discussed in #339) before I can proceed with these, since some of these changes clash with changes made there).
> Fixes for CRAM bugs.

- src/java/htsjdk/samtools/cram/ref/ReferenceSource.java
- src/java/htsjdk/samtools/reference/AbstractFastaSequenceFile.java
- src/java/htsjdk/samtools/reference/FastaSequenceFile.java
- src/java/htsjdk/samtools/reference/FastaSequenceIndex.java
- src/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
- src/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java
- src/java/htsjdk/samtools/util/IOUtil.java
- src/tests/java/htsjdk/samtools/reference/FastaSequenceIndexTest.java
- src/tests/java/htsjdk/samtools/reference/IndexedFastaSequenceFileTest.java
This change is to make it possible to read reference sequence files (including indexes and dictionaries) from filesystems other than the local filesystem. The basic idea is to overload constructors and methods that take `java.io.File` to take `java.nio.file.Path`.
In particular, Hadoop can be supported by means of https://github.com/damiencarol/jsr203-hadoop.
Note that this requires Java 7 or above. HTSJDK currently supports Java 6, but only until October 2015, so it should be possible to use this approach after then.
> Add support for java.nio.file.Path in the reference package.

- build.sbt
adding a dependency on gov.nih.nlm.ncbi:ngs-java:1.2.2 so that it's available when released to maven central
closes #391
> adding ngs-java as a dependency for maven

- src/java/htsjdk/samtools/SAMUtils.java
In theory it should never be a problem (the BAM would have to be all sorts of f###ed up),
but in the original version the if statement could error out if the read is not paired.
> Switched around the logic if the if-else check.

- src/java/htsjdk/samtools/sra/SRAAccession.java
- src/tests/java/htsjdk/samtools/sra/SRAAccessionTest.java
We implemented several checks to see if the path looks like an SRA archive and if not fail immediately and try other readers.
This PR should address issues for users working with non-SRA data sources and limited internet connections. (for instance, that one: https://github.com/broadinstitute/picard/issues/354)
The file recognition in `SamReaderFactory` will work as follows:
1. Checks if the file is a BAM file and then loads it;
2. Checks if the file is a CRAM file and then loads it;
3. Checks if the file is:
* An existing file, then checks its header to match SRA signature. If matched - load SRA engine and pass the file to it
* Non-existing file path, then checks if it matches to SRA accession pattern (`^[SED]RR[0-9]{6,9}$`). If matched - load SRA engine and make it check if that was a …
> Added checks that can very early report that path is not an SRA archive and not load SRA engine and its libraries

- src/java/htsjdk/samtools/filter/AbstractJavascriptFilter.java
- src/java/htsjdk/samtools/filter/JavascriptSamRecordFilter.java
- src/java/htsjdk/samtools/util/RuntimeScriptException.java
- src/java/htsjdk/variant/variantcontext/filter/JavascriptVariantFilter.java
- src/tests/java/htsjdk/samtools/filter/JavascriptSamRecordFilterTest.java
- src/tests/java/htsjdk/variant/variantcontext/filter/JavascriptVariantFilterTest.java
- testdata/htsjdk/samtools/samFilter01.js
- testdata/htsjdk/samtools/samFilter02.js
- testdata/htsjdk/variant/variantFilter01.js
- testdata/htsjdk/variant/variantFilter02.js
from picard :  https://github.com/broadinstitute/picard/pull/335
> Could you move the filters into htsjdk?
here are the new sources:
* wrote an abstract javascript filter and two implementations for SAM and VCF
* wrote two Tests for both format as well as some javascript files used by the test.
> javascript filters from SAM and VCF

- src/java/htsjdk/samtools/SamFiles.java
- src/tests/java/htsjdk/samtools/SamFilesTest.java
- testdata/htsjdk/samtools/BAMFileIndexTest/symlink_with_index.bam
- testdata/htsjdk/samtools/BAMFileIndexTest/symlink_with_index.bam.bai
- testdata/htsjdk/samtools/BAMFileIndexTest/symlink_without_linked_index.bam
This is to enable a feature request from the GATK forums. 
https://github.com/broadinstitute/hellbender/issues/781
Allow htsjdk to find a bai file at the actual path of a symlinked bam without having to symlink the bai as well.  
So when looking for an index:
*  Look for the bai or bam.bai at the given file path
*  If not file was found, find the canonical path of the bam and then look there for the bam or bai
This is going to have a minor conflict with @vadimzalunin pull request so whichever goes in last will have to rebase on the other one.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/samtools/htsjdk/305)
> allow lazy symlinking of bams

- src/java/htsjdk/samtools/Cigar.java
- src/java/htsjdk/samtools/CigarElement.java
- src/java/htsjdk/samtools/CigarOperator.java
- src/tests/java/htsjdk/samtools/CigarTest.java
I've added a few functions to Cigar* . I'm working with split reads and I often need to know if the cigar is clipped, what is the nature if the 5' or 3' operator ,etc ...
in **CigarOperator**:
* isClipping
* isPadding
* isIndel
* isIndelOrSkippedRegion
* isAlign
in **Cigar**
* cigarElements is final and so it is never nulll
* now implements Iterable<CIgarElement>
* added static builder from a List of CigarOperator (it cannot be a constructor because a similar constructor exists)
* added 'containsOperator', isLeftClipped, isRightClipped, isClipped
* prevent IDE warnings in 'switch/case' by adding 'default'
* get first/last cigarElement
in **CigarElement**:
* added toString
in **CigarTest**:
added one test for the above functions.
> added utilities to Cigar*

- src/java/htsjdk/samtools/util/CollectionUtil.java
- src/java/htsjdk/variant/variantcontext/VariantContext.java
- src/java/htsjdk/variant/variantcontext/VariantContextUtils.java
- src/tests/java/htsjdk/tribble/util/ftp/FTPClientTest.java
- added isTransition to VariantContext, to tell if a VariantContext is a transition or a transversion. Works on bi-allelic SNPs.
- Added a java8 verion of CollectionUtils.partition which is much easier to use than the previous version (@Deprecated)
> Yf add istransition

- src/tests/java/htsjdk/samtools/sra/SRALazyRecordTest.java
adding code to skip an SRA test if the SRA native code is unavailable.
> skip failing SRA test native code is unavailable

- src/java/htsjdk/samtools/DiskBasedBAMFileIndex.java
I was trying to make raw access to BAIs in a downstream project (see https://github.com/HadoopGenomics/Hadoop-BAM/issues/34) and found that the [AbstractBAMFileIndex](https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/AbstractBAMFileIndex.java) has no public concrete implementations. As such, I'd like to open this class up as public.
> Open up DiskBasedBAMFileIndex as a public class.

- src/java/htsjdk/samtools/DuplicateSetIterator.java
@tfenne @yfarjoun simple change to allow a user-provided comparator, for example, if we wanted to extend `SAMRecordDuplicateComparator` with our own implementation.
> Allow the duplicate set comparator to be set.

- src/java/htsjdk/samtools/fastq/BasicFastqWriter.java
- src/java/htsjdk/samtools/fastq/FastqReader.java
- src/java/htsjdk/samtools/fastq/FastqRecord.java
- src/tests/java/htsjdk/samtools/fastq/FastqWriterTest.java
* Serialize FASTQ record (answer to https://github.com/samtools/htsjdk/issues/445 )
* clone+ copy constructor for fastq record
*  BasicFastqWriter is java.io.Flushable
* added @Override to close/flush in BasicFastqWriter and FastqReader
* added a test for fastq
> fastq serializeable

- src/java/htsjdk/variant/vcf/VCFHeaderLine.java
- src/tests/java/htsjdk/variant/vcf/VCFHeaderLineUnitTest.java
- src/tests/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
This is a small change that protects against writing unescaped quotes in VCF header lines, which can cause files written with htsjdk to fail validation.
For some attribute values in VCF header lines, htsjdk currently wraps the string value with double quotes. However, if the value passed in itself contains double quotes, this results in unquoted or unbalanced quotes in the resulting VCF header line. An example tool that can cause this issue is GATK VariantFiltration, which creates VCF header lines (of the form "GATKCommandLine=") with broken quotes if run with a JEXL expression that contains double quotes.
The VCF spec states that double quotes can be escaped with a backlash. This change automatically does this when necessary. 
Included a couple of unit tests of the functionality as well …
> Escape quotes in VCF header values

- src/java/htsjdk/samtools/CRAMContainerStreamWriter.java
- src/java/htsjdk/samtools/CRAMFileWriter.java
- src/java/htsjdk/samtools/cram/build/CramIO.java
- src/java/htsjdk/samtools/cram/common/CramVersions.java
- src/tests/java/htsjdk/samtools/CRAMContainerStreamWriterTest.java
- src/tests/java/htsjdk/samtools/CRAMFileIndexTest.java
This PR factors out the code (from CRAMFileWriter) that bundles SAMRecords into CRAM containers , and repackages it in a new class CRAMContainerStreamWriter, which exposes an API for finer grained control over the writing of the CRAM file header, SAMFileHeader, and EOF container blocks than is possible with CRAMFileWriter. There is no net  new functionality; CRAMFileWriter delegates to the new class.
> Factor out CRAM container writing code from CRAMFileWriter.

- src/java/htsjdk/variant/variantcontext/VariantContextBuilder.java
- src/java/htsjdk/variant/variantcontext/VariantContextUtils.java
I've moved a few fields in variant context from protected to private.
Those fields were used in VariantContextBuilder but a 'builder' should use the getter/setter of a variantcontext if we are using a derived class of VariantContext.
Added a few 'final' too.
> private members for variant ctx

- src/java/htsjdk/samtools/SAMFileWriterImpl.java
- src/java/htsjdk/samtools/SAMRecord.java
- src/tests/java/htsjdk/samtools/BAMFileWriterTest.java
- src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java
Includes some DRY-refactoring to support cleaning up mate/reference index state management and javadoc.
> SAM/BAM writers should always call setHeader on alignment records.

- src/java/htsjdk/samtools/util/ComparableTuple.java
- src/java/htsjdk/samtools/util/Tuple.java
- src/tests/java/htsjdk/samtools/util/ComparableTupleTest.java
- src/tests/java/htsjdk/samtools/util/TupleTest.java
- add equals, toString, and hashCode to Tuple
- extend Tuple to ComparableTuple for when the Types are themselves Comparable
This makes it possible to use ComparableTuple in the Histogram class.
> extended Tuple to a ComparableTuple so it can be used in a Histogram

- src/java/htsjdk/samtools/CRAMFileReader.java
- src/java/htsjdk/samtools/CRAMFileWriter.java
- src/java/htsjdk/samtools/SamReaderFactory.java
- src/java/htsjdk/samtools/cram/build/CramNormalizer.java
- src/java/htsjdk/samtools/cram/ref/ReferenceSource.java
- src/tests/java/htsjdk/samtools/CRAMFileReaderTest.java
- src/tests/java/htsjdk/samtools/CramFileWriterTest.java
- src/tests/java/htsjdk/samtools/SAMFileReaderTest.java
Per the discussion in https://github.com/samtools/htsjdk/issues/362, require a valid reference source for CRAMReader, CRAMWriter, CRAMIterator and CRAMNormalizer. The SAMReader factories now use a method to create a default reference source (which throws if the reference_fasta property is not set and the download services isn't enabled) if one is not supplied directly, and the CRAM* classes throw if passed a null reference source.
> Require a reference for CRAM files, add javadoc and some tests.

- src/tests/java/htsjdk/samtools/util/ComparableTupleTest.java
- src/tests/java/htsjdk/samtools/util/IupacTest.java
two tests were being skipped because they had problems with their dataproviders
IupacTest.basic() had a typo in the dataprovider name
ComparableTupleTest.testComparableTuple had a exception in the dataprovider
also renamed this to testComparableTupleNullData since it was misnamed
fixed a warning in the test class as well
> fixing tests that were being skipped

- .travis.yml
- build.xml
- src/tests/java/htsjdk/samtools/sra/AbstractSRATest.java
- src/tests/java/htsjdk/samtools/sra/SRAAccessionTest.java
- src/tests/java/htsjdk/samtools/sra/SRAIndexTest.java
- src/tests/java/htsjdk/samtools/sra/SRALazyRecordTest.java
- src/tests/java/htsjdk/samtools/sra/SRAQueryTest.java
- src/tests/java/htsjdk/samtools/sra/SRAReferenceTest.java
- src/tests/java/htsjdk/samtools/sra/SRATest.java
removing SRA tests from `ant test` and moving them to their own `ant sra-test` target
this should isolate SRA tests so that they can no longer fail during a picard release
once #461 and  #442 are fixed they should be moved back into the standard `ant test`
- added a new ant target sra-test which exclusively runs the sra tests
- made all SRA test classes descend from a new `AbstractSRATest` base class
- this ensures they are all set in the appropriate test group
- each SRA test method will run `assertSRAIsSupported()` and be skipped if it is not
- removed the newly redundant checks in every SRA test
- pulled `checkAlignedUnalignedCountsByIterator` up into the base class to remove duplicated code
- updated .travis.yml to run sra-test after the rest of the tests
fixes #436 and #459
> moving SRA tests to their own test group

- src/java/htsjdk/variant/variantcontext/Genotype.java
- src/tests/java/htsjdk/variant/variantcontext/GenotypeUnitTest.java
There was a potentially invalid case where a genotype could be constructed with an empty filter string.
This would result in `isFiltered()` returning `true` and `getFilters()` being empty.  There are explicit checks in gatk for `genotype.isFiltered() && genotype.getFilters().isEmpty()` so there must be cases where this has happened.  
I don't believe there is any case where this would be meaningful state to represent.
> Genotype now treats empty filter strings identically to null filter strings

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
created a `.github` directory containing 
* PULL_REQUEST_TEMPLATE
* ISSUE_TEMPLATE.md
as described in the github blog last week : https://github.com/blog/2111-issue-and-pull-request-templates
I didn't put a CONTRIBUTING.md because I'm not the best person to describe the code formatting style :-)
> It's hard to solve a problem when important details are missing. Now project maintainers can add templates for Issues and Pull Requests to projects, helping contributors add the right details at the start of a thread.
> .github/ directory for ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md

- src/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
Fix for perf regression described in https://github.com/samtools/htsjdk/issues/471,  which was introduced in https://github.com/samtools/htsjdk/pull/252. Affects the size of the read buffer used when reading fasta files. I don't see any obvious way to write a test to verify this programmatically.
> Fix perf bug in IndexedFastaSequenceFile.

- src/java/htsjdk/samtools/cram/build/ContainerParser.java
- src/tests/java/htsjdk/samtools/cram/build/ContainerParserTest.java
ContainerParser throws NPE when reading EOF container. The fix is to return an empty list instead.
> container parser should return empty record list from EOF container

- src/java/htsjdk/samtools/MergingSamRecordIterator.java
- src/java/htsjdk/samtools/SAMHeaderRecordComparator.java
- src/java/htsjdk/samtools/SAMRecordCoordinateComparator.java
- src/java/htsjdk/samtools/SAMRecordDuplicateComparator.java
- src/java/htsjdk/samtools/SAMRecordQueryHashComparator.java
- src/java/htsjdk/samtools/SAMRecordQueryNameComparator.java
- src/java/htsjdk/samtools/util/IntervalList.java
- src/java/htsjdk/samtools/util/LocusComparator.java
- src/java/htsjdk/samtools/util/Murmur3.java
- src/java/htsjdk/samtools/util/SortingCollection.java
- src/java/htsjdk/samtools/util/SortingLongCollection.java
- src/java/htsjdk/variant/variantcontext/VariantContextComparator.java
- src/java/htsjdk/variant/variantcontext/writer/SortingVariantContextWriterBase.java
This pull request is focused on resolving occurrences of Sonar squid:S2063 - Comparators should be "Serializable"
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2063
Please let me know if you have any questions.
M-Ezzat
> squid:S2063 - Comparators should be Serializable

- src/java/htsjdk/samtools/util/AbstractProgressLogger.java
Make field 'long processed' volatile to provide atomic read in getCount()
According to Java Language Specification, "Programmers are encouraged to declare shared 64-bit values as volatile or synchronize their programs correctly to avoid possible complications."
https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.7
It is enough to make the field 'processed' volatile in AbstractProgressLogger to provide thread safety.
> make field 'long processed' volatile

- src/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
- src/tests/java/htsjdk/variant/variantcontext/GenotypeLikelihoodsUnitTest.java
Implements https://github.com/samtools/htsjdk/issues/437.
Previously, only diploid allele pair indices could be accessed by PL index:
`GenotypeLikelihoodsAllelePair getAllelePair(final int PLindex)`
This pull request adds the ability to get the allele indices for any ploidy:
`List<Integer> GenotypeLikelihoods.getAlleles(final int PLindex, final int ploidy)`
> Handle aneuploid likelihoods

- src/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
On a recent change, a non-ascii character '…' (the character for elipsis) was inserted in a comment.
This is breaking the compile of the target compile-variant on one of our unix hosts:
> Remove non-ascii character from comment.  Was breaking compile on certain machines

- src/java/htsjdk/samtools/SAMRecord.java
- src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java
setHeaderStrict(null) isn't resetting the mHeader field, only the ref indices.
> Fix setHeaderStrict(null) bug.

- src/java/htsjdk/samtools/filter/FilteringIterator.java
- src/java/htsjdk/samtools/filter/FilteringSamIterator.java
- src/java/htsjdk/samtools/util/SamLocusIterator.java
- src/java/htsjdk/samtools/util/SamRecordIntervalIteratorFactory.java
- src/java/htsjdk/samtools/util/Tuple.java
- src/java/htsjdk/variant/variantcontext/filter/FilteringIterator.java
- src/java/htsjdk/variant/variantcontext/filter/FilteringVariantContextIterator.java
- src/tests/java/htsjdk/variant/variantcontext/filter/FilteringVariantContextIteratorTest.java
- src/tests/java/htsjdk/variant/variantcontext/filter/HeterozygosityFilterTest.java
- src/tests/java/htsjdk/variant/variantcontext/filter/JavascriptVariantFilterTest.java
There are two very different FilteringIterators in htsjdk, SAM and VariantContext flavored ones. This is confusing and can lead to very verbose code when one wants to use both in the same class. 
This PR renames these two iterators FilteringSamIterator and FilteringVariantContextIterator while keeping the "old" FilteringIterators as @Deprecated but accessible subclasses. This makes it possible to remove these classes later, once folks have shifted over to using the explicitly named iterators.
> Split the two FilteringIterators into two differently named Iterators

- src/java/htsjdk/samtools/util/Log.java
This allows one to check the VERBOSITY level of the run without instantiating a new Log. 
In a utility class I'd like to  log only if the VERBOSITY is "DEBUG" and since the code is rather "deep" I do not wish to instantiate a Log just to check the VERBOSITY.
> made 'isEnabled' static

- src/java/htsjdk/samtools/example/PrintReadsExample.java
I made a simple PrintReads program that illustrates how to use the readers and writers and also is very useful for benchmarking changes such as #515 or #78 
It's useful to have something like this in htsjdk directly rather than going through users of the library eg picard or gatk to test/benchmark reader/writer improvements.
> Added an example PrintReads

- src/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/tests/java/htsjdk/samtools/util/BlockCompressedOutputStreamTest.java
Add a method to BlockCompressedInputStream to expose whether the stream is positioned at the end of a BGZF block. This is needed by Hadoop-BAM (and GATK4 indirectly via its dependency on Hadoop-BAM) to add support for reading block compressed VCF files in parallel. See https://github.com/HadoopGenomics/Hadoop-BAM/issues/68 and https://github.com/HadoopGenomics/Hadoop-BAM/pull/70. /cc @akiezun
> Add a method to expose whether the stream is positioned at the end of a BGZF block.

- src/java/htsjdk/samtools/Defaults.java
- src/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/java/htsjdk/samtools/example/PrintReadsExample.java
- src/java/htsjdk/samtools/fastq/FastqWriterFactory.java
- src/java/htsjdk/tribble/readers/LineReaderUtil.java
- src/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/java/htsjdk/variant/variantcontext/writer/VariantContextWriterFactory.java
- src/tests/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
- src/tests/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
This PR takes over from https://github.com/samtools/htsjdk/pull/528 and splits `USE_ASYNC_IO` into 2 options, `USE_ASYNC_IO_FOR_SAMTOOLS` and `USE_ASYNC_IO_FOR_TRIBBLE` because clients like GATK want more fine grained controls and also the performance characteristics of samtools vs tribble are very different (see  https://github.com/samtools/htsjdk/pull/528) for examples and timings.
@droazen can you review? @yfarjoun FYI
> split async samtools and tribble options

- src/java/htsjdk/samtools/CRAMBAIIndexer.java
- src/java/htsjdk/samtools/CRAMContainerStreamWriter.java
- src/java/htsjdk/samtools/cram/CRAIEntry.java
- src/java/htsjdk/samtools/cram/CRAIIndex.java
- src/tests/java/htsjdk/samtools/CRAMBAIIndexerTest.java
- src/tests/java/htsjdk/samtools/CRAMComplianceTest.java
- src/tests/java/htsjdk/samtools/CRAMFileBAIIndexTest.java
- src/tests/java/htsjdk/samtools/CRAMFileWriterTest.java
- src/tests/java/htsjdk/samtools/SAMFileReaderTest.java
- src/tests/java/htsjdk/samtools/cram/CRAIEntryTest.java
- src/tests/java/htsjdk/samtools/cram/CRAIIndexTest.java
Proposed refactoring of some existing CRAM indexing code and tests, both as prep for https://github.com/samtools/htsjdk/issues/433 and to better align the CRAM test classes with the code being tested; proposed removal of some unused code; some minor test bug fixes. No net new functionality.
Summary of changes:
- CRAMIndexer - Renamed to CRAMBAIIndexer to better reflect it's intent; all of the code is for generating BAI indices from a CRAM file (and some of the test code for this class is already in a file
called CRAMBAIIndexerTest).
- CRAIIndex - Removed two public methods (findLastAlignedEntry and getLeftMost) that were only referenced by their test code in CRAIIndexTest. (Are these useful to keep as public methods - htsjdk never uses .crai indices directly other than to convert them to …
> CRAM index code/test refactoring.

- src/java/htsjdk/samtools/util/SequenceUtil.java
- src/tests/java/htsjdk/samtools/util/SequenceUtilTest.java
string usable for output in a SAM or BAM file.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/samtools/htsjdk/431)
> adding a method to convert a FASTQ header (read name) to a read name

- build.sbt
including the intel deflator in the published jar, it appears in the jar as `lib/jni/libIntelDeflator.so`
> packaging the intel deflator into the published jar

- src/java/htsjdk/variant/vcf/VCFStandardHeaderLines.java
See description is issue #544.  Briefly, VCF header used to say AD had unlimited number of values, this fixes it to correctly say it has as many values as there are alleles.
> Fixed AD number if VCF header

- src/java/htsjdk/variant/example/PrintVariantsExample.java
- src/tests/java/htsjdk/variant/PrintVariantsExampleTest.java
Similar to `PrintReadsExample`, this is a `PrintVariantsExample`. The purpose it to demonstrate how to use readers and writers but also to enable easy performance testing etc.
Run it like this
```
java -cp dist/htsjdk-2.1.1.jar htsjdk.variant.example.PrintVariantsExample file.vcf
```
optionally add output file 
```
java -cp dist/htsjdk-2.1.1.jar htsjdk.variant.example.PrintVariantsExample file.vcf out.vcf
```
> print variants example

- src/java/htsjdk/samtools/util/AbstractAsyncWriter.java
Fixes https://github.com/samtools/htsjdk/issues/564 by reverting the order of conditions in the while loop and making checking them effectively atomic (ie nothing can change the values of once the `while` condition starts being evaluated
> fix for race condition in AbstractAsyncWriter

- src/java/htsjdk/variant/variantcontext/GenotypeJEXLContext.java
- src/java/htsjdk/variant/variantcontext/JEXLMap.java
- src/java/htsjdk/variant/variantcontext/VariantJEXLContext.java
- src/tests/java/htsjdk/variant/variantcontext/VariantJEXLContextUnitTest.java
I am hoping someone more familiar with JEXL in htsjdk could do a quick review of what i'm proposing to see if this looks reasonable.  As noted in your code, genotype-level JEXL filtering is supported, but not implemented very cleanly.  I tried to improve that and also make it more consistent w/ the context available for VariantContext.
Here's a related GATK forum thread:
http://gatkforums.broadinstitute.org/gatk/discussion/comment/28654#Comment_28654
> Clean up Genotype JEXL Filtering

- src/java/htsjdk/samtools/reference/ReferenceSequence.java
I got tired of writing:
`StringUtil.bytesAsString(ref.getSubsequenceAt(chrom, start, end).getBases())`
all over the place when retrieving small sequences that need to be converted to Strings for output to various files, and decided it would be nice to be able to write:
`ref.getSubsequenceAt(chrom, start, end).getBaseString())`
> Added a method to retrieve reference sequences as Strings in addition to as byte[]s.

- build.sbt
Fixing a typo the build.sbt that causes the libIntelDeflater.so to be named incorrectly.
> fixing a spelling mistake in the packaged intel deflater path

- README.md
Adding badges for the gatk4 and picard tests running on htsjdk master's branch.  This is intended to assist with #568.  Tests should also be able to be manually invoked on a given htsjdk branch by anyone with github push access to gatk.  In the future this should be amended to include htsjdk committers but may be a setup hassle.
See also https://github.com/broadinstitute/gatk/issues/1705
> Adding downstream build badges to Readme

- src/java/htsjdk/samtools/util/CloseableIterator.java
- src/tests/java/htsjdk/samtools/util/CloseableIteratorTest.java
Scala has spoiled me, and I'm tired of Java's iterators being second class citizens.  This commit adds a pair of default methods to `CloseableIterator` which will benefit most iterators in htsjdk, and allows easy transformation to a `List` and a `Stream`.
> Utility methods on CloseableIterator to make life a little easier.

- src/java/htsjdk/samtools/BinningIndexBuilder.java
- src/java/htsjdk/samtools/CRAMBAIIndexer.java
- src/java/htsjdk/samtools/GenomicIndexUtil.java
- src/java/htsjdk/samtools/SAMRecord.java
- src/java/htsjdk/samtools/SAMUtils.java
- src/tests/java/htsjdk/samtools/GenomicIndexUtilTest.java
Moved GenomicIndexUtil.reg2bin to public
I'm inserting genomic data in a sql database just like in the UCSC tables : there is a 'bin' index ( http://genomewiki.ucsc.edu/index.php/Bin_indexing_system )
making  `GenomicIndexUtil.reg2bin` public allows me to get the 'bin' index . 
- [ x] Code compiles correctly
- [ x] New tests covering changes and new functionality
- [ x] All tests passing
- [ x] Extended the README / documentation, if necessary
> public reg2bin

- src/java/htsjdk/samtools/BAMFileReader.java
- src/java/htsjdk/samtools/BAMIndexMetaData.java
- src/java/htsjdk/samtools/SAMFileReader.java
- src/java/htsjdk/samtools/SamReaderFactory.java
To help with implementing asynchronous BAM decompression (see https://github.com/samtools/htsjdk/pull/576), I added a flag to SamReaderFactory. Previously the synchronous/asynchronous status was always taken from `Defaults.USE_ASYNC_IO_FOR_SAMTOOLS` which did not provide enough control to clients. In particular, in GATK we do want asynchronous BAM decompression when reading from regular file system but not from HDFS.
This functionality setting on the factory already exists for `SAMFileWriterFactory` and `FastqWriterFactory`. 
This PR is a bit unusual in that it does not actually add asynchronous reading. It only enables the flag to be set on the factory rather than be always taken from `Defaults`. The actual implementation will be in https://github.com/samtools/htsjdk/pull/576. This PR …
> adding a useAsynchronousIO flag to SamReaderFactory

- building.html
Updating the documentation site to say we need java 1.8 instead of 1.6.
- [ x ] Extended the README / documentation, if necessary
> Updating docs to replace outdated java 1.6 -> 1.8

- build.gradle
This should fix a gradle issue that can manifest in forks of htsjdk.  Fix for #605 
adding an explicit check for null when determining isRelease
this happens in the case of a fork of the repo with no tags
> adding null check when determining isRelease

- src/main/java/htsjdk/variant/variantcontext/VariantContextBuilder.java
Changed VariantContextBuilder.attributes() to copy the supplied map in order to avoid:
1) Modification of the map after it is passed to VariantContextBuilder
2) Storing an unmodifiable map that cannot be added to later
Picard's LiftoverIntervalList currently fails if `WRITE_ORIGINAL_POSITION` is set to `true` because it calls `VariantContextBuilder.atttributes(oldContext.getAttributes())` which sets an `UnmodifiableMap` on the builder, which on subsequent calls to `attribute(key, value)` fails with this exception:
```
Exception in thread "main" java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
at htsjdk.variant.variantcontext.VariantContextBuilder.attribute(VariantContextBuilder.java:212)
at …
```
> Changed VariantContextBuilder.attributes() to copy the supplied map

- .travis.yml
- README.md
- build.gradle
This PR adds coverage collection (offline using jacoco and online using coveralls) and a coverage badge to the README. Now that we're on gradle this was super easy.
The online coverage reports are here: https://coveralls.io/github/samtools/htsjdk
To collect coverage offline use `./gradlew jacocoTestReport` and then open `build/reports/jacoco/test/html/index.html`
> add coverage reports, online and offline. Add coveralls badge

- build.gradle
The current build.gradle adds a ".dirty" to the jar name when
running "gradle jar" when there are untracked files, even if there
are no uncommitted changes and the working directory is otherwise
clean. This is misleading, since "dirty" implies that the build
contains uncommitted changes, but untracked files do not affect
the build at all. Rather than cause confusion, let's just strip
out ".dirty" from the name for now.
> Remove the ".dirty" from htsjdk jar names

- build.gradle
- src/main/java/htsjdk/samtools/util/zip/DeflaterFactory.java
- src/test/java/htsjdk/samtools/util/IntelDeflaterTest.java
The necessary code is still intact, albeit commented out, so it's easy to re-enable in branches for experimentation purposes.
> Disable the IntelDeflater for now, since we can't publish to maven central with a dependency on an intel-gkl snapshot

- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/main/java/htsjdk/samtools/util/SamLocusIterator.java
- src/test/java/htsjdk/samtools/util/SamLocusIteratorTest.java
Added indel tracking to `SamLocusIterator` (as discussed in issue #387) and some tests. The default behaviour is still do not keep reads spanning indels.
> Added indel support to SamLocusIterator

- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/main/java/htsjdk/samtools/metrics/MetricsFile.java
- src/main/java/htsjdk/samtools/util/Histogram.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
- src/test/java/htsjdk/samtools/util/HistogramTest.java
Fixes #630. Fixes to Histogram - made it not extend TreeSet but use a TreeSet, made Bin static, add many tests, cleanup generics use.
Not backward compatible because Histogram does not extend TreeSet anymore and Bin is a static class. Some changes in clients look like this `Histogram<Integer>.Bin` -> `Histogram.Bin<Integer>`
> Histogram - made not extend TreeSet, make Bin static, add tests

- src/main/java/htsjdk/samtools/util/SamLocusIterator.java
- src/test/java/htsjdk/samtools/util/SamLocusIteratorTest.java
This PR fixes issue #611 by checking for the missing base quality string "*" when using SamLocusIterator to iterate over SAMRecords. There's also a new test that targets this scenario.
> Fix SamLocusIterator when missing base quality string is provided

- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/main/java/htsjdk/samtools/SamStreams.java
- src/main/java/htsjdk/samtools/seekablestream/SeekableStreamFactory.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
- src/test/java/htsjdk/samtools/SamStreamsTest.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamFactoryTest.java
Fix for https://github.com/samtools/htsjdk/issues/614
…t
> SamReaderFactory fixes for SAM/CRAM files on URL and SeekableStream input resources.

- src/main/java/htsjdk/samtools/util/OverlapDetector.java
- src/test/java/htsjdk/samtools/util/OverlapDetectorTest.java
There's often a need to quickly find a Locatable that overlaps a given static set of Locatables (eg, exons overlapping a given read, or variants overlapping a given read etc). I adapted the OverlapDetector APIs to this usecase. Thanks to @tfenne for pointing me to it and providing examples.
(Note: comments below reflect an old state of this PR - when there was a SkipList implementation competing with the OverlapDetector)
> Cleaner API in OverlapDetector + added tests

- build.gradle
- src/main/java/htsjdk/samtools/Defaults.java
- src/main/java/htsjdk/samtools/SRAFileReader.java
- src/main/java/htsjdk/samtools/SRAIterator.java
- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/main/java/htsjdk/samtools/sra/ReferenceCache.java
- src/main/java/htsjdk/samtools/sra/SRAAccession.java
- src/main/java/htsjdk/samtools/sra/SRAAlignmentIterator.java
- src/main/java/htsjdk/samtools/sra/SRAIndexedSequenceFile.java
- src/test/java/htsjdk/samtools/sra/SRAReferenceTest.java
- src/test/java/htsjdk/samtools/sra/SRATest.java
This PR implements optional SRA native libraries auto-download, as requested in #414
In case, when ngs-java fails to locate/load native libraries, we throw a subclass of java.lang.Error with details of what went wrong and a recommendation on how to fix the problem.
In ngs-java 1.2.4 we also improved version checking of native libraries before loading them and addressed issue #462 
We also fixed an issue with keeping references to SRA objects forever, which prevented them from being garbage collected and sometimes produced issues with reaching a limit of opened file handlers.
> Provided an option to disable auto-download of SRA native libraries

- src/main/java/htsjdk/samtools/util/Histogram.java
Minor change to fix the fact that after making Bin a static inner class it's type parameter no longer had Comparable as a bound, which it did before because Histogram's type parameter was bounded.
> Carried over "extends Comparable" from Histogram<K> to Bin<K>.

- src/main/java/htsjdk/samtools/util/SortingCollection.java
Replaced with direct usage of TreeSet.pollFirst(). One advantage (other than removing unneeded code) is that this now only has to search the tree once, instead of twice for poll() then remove().
This also resolved a bug I was experiencing where the `remove()` call was getting a NoSuchElementException that I couldn't figure out.
> Removed PollableTreeSet in SortingCollection as it was no longer necessary.

- src/main/java/htsjdk/samtools/liftover/LiftOver.java
- src/test/java/htsjdk/samtools/liftover/LiftOverTest.java
This method will give the destination contigs are used when mapping positions in a source contig.  This method allows `LiftoverVcf` to be more intelligent about memory usage (https://github.com/broadinstitute/picard/pull/525).
> Provide a method that for each source contig gives the set of destination contigs used in liftover.

- src/main/java/htsjdk/samtools/Defaults.java
- src/main/java/htsjdk/samtools/SAMFileReader.java
- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/main/java/htsjdk/samtools/fastq/FastqWriterFactory.java
- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterFactory.java
- src/test/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
- src/test/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
This PR splits the flags that control the async behavior to read/write to give more fine-grained control to clients. This will be important when hooking up #576 and make multi-threaded reading an opt-in option.
Not backward compatible because I removed the master option `USE_ASYNC_IO` - having that option conflicts with the opt-in requirement. I think an uber  `USE_ASYNC_IO` is just too broad. Note that there's no `USE_ASYNC_IO_READ_FOR_TRIBBLE` because we have no asynch tribble readers right now.
@droazen can you review?
> split async flags for read and write

- src/main/java/htsjdk/samtools/util/BlockGunzipper.java
This is a simple change to expose the `unzipBlock` method, and is useful for folks that are de-compressing gzip blocks, for example specialty tools built for BAM files.
@tfenne @akiezun care to take a look?
> Make unzipBlock in BlockGunzipper public.

- src/main/java/htsjdk/samtools/util/Lazy.java
The LazyInitilizer class can use java8 sugar but only if it's annotated correctly. This one-line PR makes that change.
> made LazyInitializer a @FunctionalIterface to enable java8 sugar.

- src/main/java/htsjdk/samtools/util/SamLocusIterator.java
- src/test/java/htsjdk/samtools/util/SamLocusIteratorTest.java
This is useful if we want to quickly know how many records overlap this
position but do not want to get all those records.
> Add a size method to SamLocusIterator.LocusInfo.

- src/main/java/htsjdk/variant/vcf/VCFStandardHeaderLines.java
User [reports] (https://github.com/broadinstitute/gsa-unstable/issues/1413) that for `VariantFiltration` in GATK3 with genotype filters, the Number tag in the description of FT in the output VCF should be "." rather than 1.
This is actually caused by htsjdk.
This fix tries to deal with that.
> Number tag in header line for GENOTYPE_FILTER

- src/main/java/htsjdk/variant/vcf/VCFStandardHeaderLines.java
- src/test/java/htsjdk/variant/vcf/VCFStandardHeaderLinesUnitTest.java
This PR includes some code clean up and updated unit tests for `VCFStandardHeaderLines`.
> Add unitest for vcf standard header lines following #654

- src/main/java/htsjdk/variant/variantcontext/FastGenotype.java
- src/main/java/htsjdk/variant/variantcontext/GenotypeBuilder.java
- src/test/java/htsjdk/variant/variantcontext/GenotypeBuilderTest.java
Fixing `GenotypeBuilder`, that generates mutable `Genotypes` (regarding extended attributes). Found in #580.
> GenotypeBuilder.makeWithShallowCopy() for safely re-use it

- src/main/java/htsjdk/variant/variantcontext/Genotype.java
- src/test/java/htsjdk/variant/variantcontext/GenotypeUnitTest.java
A Genotype always has filters. If there are no non-PASS filters, it's PASS. Genotype.getAnyAttribute() currently will never return a value for "FT", which I dont think is the right behavior.  This also means you cant use GATK's JEXL select/filtering based on the genotype's filters. This is a minor change to Genotype to support this.  It includes a simple unit test.
…ibute
> Genotype attributes

- build.gradle
- src/main/java/htsjdk/samtools/SRAFileReader.java
- src/main/java/htsjdk/samtools/sra/SRAAccession.java
- src/test/java/htsjdk/samtools/sra/AbstractSRATest.java
- src/test/java/htsjdk/samtools/sra/SRAAccessionTest.java
- src/test/java/htsjdk/samtools/sra/SRAIndexTest.java
- src/test/java/htsjdk/samtools/sra/SRALazyRecordTest.java
- src/test/java/htsjdk/samtools/sra/SRATest.java
These changes are intended to resolve most of previously reported SRA-related issues:
- #442 - updated tests to use much smaller files, so that footprint by SRA cache on Mac OS X is about 30 Mb (on other OS issue does not exist, since we use sparse files there and footprint is even smaller)
- #459, #461 - now each network-related test checks if it can resolve an accession, and skips the test in case of failure
- #460, #545 - updated error message in SRAFileReader, so that it tells about a possibility of a connection problem
> Improved SRA tests, corrected error message

- src/main/java/htsjdk/samtools/SAMRecordUtil.java
- src/test/java/htsjdk/samtools/SAMRecordUtilTest.java
Expose the set of tags to reverse and reverse complement as parameters, so that reads can be reverse complemented and all tags that are one-value-per-base in the read can be kept in sync.
> Expose the set of tags to reverse and reverse complement as parameters.

- src/main/java/htsjdk/samtools/filter/IntervalFilter.java
- src/main/java/htsjdk/samtools/filter/IntervalKeepPairFilter.java
- src/test/java/htsjdk/samtools/filter/IntervalKeepPairFilterTest.java
The current Interval Filter did not work 'paired' filtering. Recently, we needed to use an interval list to filter a bam, but keep both the read and its mate if either of them overlapped with the interval. The IntervalKeepPairFilter does this using an overlap detector on a coordinate sorted bam and sorted interval list.
> Interval Filter that Keeps Pairs

- src/main/java/htsjdk/samtools/util/TestUtil.java
- src/test/java/htsjdk/samtools/BAMRemoteFileTest.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamFactoryTest.java
- src/test/java/htsjdk/tribble/AbstractFeatureReaderTest.java
- src/test/java/htsjdk/tribble/readers/TabixReaderTest.java
Tests are breaking on master because of changed broad made to our webhosting
~~- [ ] New tests covering changes and new functionality~~  
~~- [ ] Extended the README / documentation, if necessary~~  
~~- [ ] Is not backward compatible (breaks binary or source compatibility)~~  
broad changed its website's urls from http://www.broadinstitute.org/~picard -> https://personal.broadinstitute.org/picard
there are redirects in place that work in most browsers, but our implementation of http can't follow the redirects
> updating urls in tests to point to new locations

- src/main/java/htsjdk/samtools/util/AbstractAsyncWriter.java
- src/test/java/htsjdk/samtools/util/AsyncWriterTest.java
Any exception thrown during synchronousWrite() by the underlying thread
is typically rethrown during write()'s invocation of checkAndRethrow().
However, subsequent calling of close() (e.g. by try-with-resources) results
in an attempt to throw the same exception instance while it is already 
being thrown, which triggers an additional exception from Java (Self-suppression 
not permitted).
This commit ensures that the underlying exception is only thrown once,
by clearing the reference to the Throwable before throwing.
> Fix self-suppression problem with exception handling in AbstractAsyncWriter

- src/main/java/htsjdk/tribble/AbstractFeatureCodec.java
- src/main/java/htsjdk/tribble/BinaryFeatureCodec.java
- src/main/java/htsjdk/tribble/FeatureCodec.java
- src/main/java/htsjdk/tribble/bed/BEDCodec.java
- src/main/java/htsjdk/tribble/index/IndexFactory.java
- src/main/java/htsjdk/variant/vcf/AbstractVCFCodec.java
- src/test/java/htsjdk/tribble/BinaryFeaturesTest.java
- src/test/java/htsjdk/tribble/bed/BEDCodecTest.java
- src/test/java/htsjdk/variant/vcf/AbstractVCFCodecTest.java
Current implementation of tabix indexing requires a `TabixFormat`, which should be defined by the API user outside the codecs except for the static instances inside the class (VCF and BED). Due to this, `IndexFactory` requires always to provide the `TabixFormat` when creating a new index, not allowing the creation of indexes with a common interface.
Nevertheless, when developers implements a new `FeatureCodec`, they know how the format for tabix is specified (if it is possible), and others could use it without the need to implement it by themselves.
Here I implemented a new default method for `FeatureCodec` for retrieve the `TabixFormat` associated, and added some static methods to `IndexFactory` to use it. This could be useful in GATK4 tool `IndexFeatureFile`, which only supports tabix …
> FeatureCodec.getTabixFormat() to encapsulate tabix formatting

- src/main/java/htsjdk/samtools/DuplicateScoringStrategy.java
When evaluating error rates in data with UMIs and contrasting different approaches to duplicate marking, it is useful to have an unbiased read picked as the representative for a duplicate set instead of some heuristic for "best".
> Added a "RANDOM" duplicate scoring strategy.

- src/main/java/htsjdk/samtools/cram/encoding/reader/DataReaderFactory.java
- src/main/java/htsjdk/samtools/cram/structure/CompressionHeader.java
Fixes https://github.com/samtools/htsjdk/issues/549. Change the CRAM reader to throw when it sees an encoding tag it doesn't recognize.
The CRAM code currently logs and ignores unrecognized encoding tags, but we really should throw if we ever see one of these.
This is a purely defensive change - I don't really know of a way to force this condition.
> Throw on unrecognized CRAM encoding tag.

- src/main/java/htsjdk/samtools/SAMUtils.java
- src/test/java/htsjdk/samtools/SAMUtilsTest.java
I've added a new function `getOtherCanonicalAlignments` in SAMUtils. This function is used to extract the 'SA' tag of a SAMRecord as a `List<SAMRecord>`of supplementary alignements. 
* 
```   
/**
* Extract a List of 'other canonical alignments' from a SAM record. Those alignments are stored as a string in the 'SA' tag as defined
* in the SAM specification.
* Each record in the List is a non-paired read.
* The name, sequence and qualities are copied from the original record
* The SAM flag is set to <code>SUPPLEMENTARY_ALIGNMENT (+ READ_REVERSE_STRAND )</code>
* @param record must be non null and must have a non-null associated header.
* @return a list of 'other canonical alignments' SAMRecords. The list is empty if the 'SA' attribute is missing.
*/
public static List<SAMRecord> …
```
> SAMUtils:getOtherCanonicalAlignments extract 'SA' tag  and return a list of supplementary alignments

- src/main/java/htsjdk/tribble/bed/BEDCodec.java
- src/test/java/htsjdk/tribble/bed/BEDCodecTest.java
When using `canDecode("filename.bed.gz")` it will return false, but the `AbstractFeatureReader` could support block-compressed bed files. This could cause problems when trying to find the codec for a file (for instance, https://github.com/broadinstitute/gatk/pull/2131).
I added here a check for block-compression extensions and tests for them.
> Fix BEDCodec.canDecode() to handle block-compressed extensions

- src/main/java/htsjdk/variant/variantcontext/GenotypeJEXLContext.java
- src/main/java/htsjdk/variant/variantcontext/JEXLMap.java
- src/main/java/htsjdk/variant/variantcontext/VariantContextUtils.java
- src/main/java/htsjdk/variant/variantcontext/VariantJEXLContext.java
- src/test/java/htsjdk/variant/variantcontext/VariantJEXLContextUnitTest.java
* `GenotypeJEXLContext.get()` currently potentially throws `NullPointerException`, triggered by a design choice in `Genotype.getFilters()`, which explicitly returns `null` (genotype considered to be filter passing in such case according to documentation). This fix temporarily fixes that exception (1st commit, by Louis).
* Class `CommonInfo`, which holds "Common utility routines for VariantContext and Genotype", contains such a constant 
private static Set<String> NO_FILTERS = Collections.emptySet();
`VariantContext` uses this constant in its own `getFilters()` (it has a separate method `getFiltersMaybeNull()`), but `Genotype` doesn't use such constant. A choice has to be made to whether make `Genotype` resemble `VariantContext`'s behavior (a backward non-compatible change) or keep things …
> Fix JexlMap and GenotypeJEXLContext NullPtrException

- src/main/java/htsjdk/samtools/SAMFileHeader.java
- src/main/java/htsjdk/samtools/util/IntervalList.java
I find myself writing these three lines of code again and again and again to initialize an IntervalList since it requires a `SAMFileHeader` with a useful `SAMSequenceDictionary` and there's no way to create a header from a dictionary as an expression.
> Added a secondary constructor to IntervalList that takes a dict.

- src/main/java/htsjdk/samtools/AbstractBAMFileIndex.java
- src/main/java/htsjdk/samtools/AbstractSAMHeaderRecord.java
- src/main/java/htsjdk/samtools/MergingSamRecordIterator.java
- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
- src/main/java/htsjdk/samtools/SAMUtils.java
- src/main/java/htsjdk/samtools/SamFileHeaderMerger.java
- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/main/java/htsjdk/samtools/sra/SRAAccession.java
- src/main/java/htsjdk/samtools/util/TestUtil.java
Some methods are documented as being `/** @deprecated */` but are missing a `@Deprecated tag`
This causes tools to not correctly identify them as being deprecated.
also updating documentation of deprecated methods to point to the replacement method with a valid `{@link}`
> annotating deprecated methods with @Deprecated

- src/main/java/htsjdk/samtools/SAMUtils.java
- src/test/java/htsjdk/samtools/SAMUtilsTest.java
Previously when encountered with a '*' in the last field of an SA tag for getOtherCannonicalAlignments() method would throw an exception. It will now gracefully allow for an empty NM field in the new field.
> Added support for an empty NM tag in SA tag fields using '*' character

- src/main/java/htsjdk/tribble/index/AbstractIndex.java
- src/main/java/htsjdk/tribble/index/Index.java
- src/main/java/htsjdk/tribble/index/IndexFactory.java
- src/main/java/htsjdk/tribble/index/tabix/TabixIndex.java
- src/test/java/htsjdk/tribble/FeatureReaderTest.java
- src/test/java/htsjdk/tribble/index/IndexFactoryTest.java
- src/test/java/htsjdk/tribble/index/IndexTest.java
- src/test/java/htsjdk/tribble/index/tabix/TabixIndexTest.java
> Fix IndexFactory.writeIndex for tabix indexes

- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/TextTagCodec.java
- src/test/java/htsjdk/samtools/SAMIntegerTagTest.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
Enables the reading and writing of sam/bam/cram records with empty string tags as required by https://github.com/samtools/hts-specs/issues/135
added tests to cover this functionality
> Yf add test empty string sam tag

- src/main/java/htsjdk/samtools/util/PositionalOutputStream.java
- src/main/java/htsjdk/tribble/index/IndexCreator.java
- src/main/java/htsjdk/tribble/index/TribbleIndexCreator.java
- src/main/java/htsjdk/variant/variantcontext/writer/IndexingVariantContextWriter.java
- src/test/java/htsjdk/samtools/util/PositionalOutputStreamTest.java
> IndexingVariantContextWriter cleanup

- src/test/java/htsjdk/samtools/util/RelativeIso8601DateTest.java
After overhaul the tests in `RelativeIso8601DateTest` because of test failures due to #578, I found that some of the `getTime()` asserts does not contain a delta value when one of them does. Thus, I added a delta value for all the tests to try to solve this issue.
Because the test failure is not deterministic, I don't know how to tests this. But at least it is a good practice to test always with the same delta value. This is a very simple patch that does not change anything important in the code.
> Adding delta for getTime assert to fix #578

- src/main/java/htsjdk/samtools/CRAMFileReader.java
- src/test/java/htsjdk/samtools/CRAMFileReaderTest.java
Fix for issue [#574](https://github.com/broadinstitute/picard/issues/574) (picard):
ViewSam works very slowly with CRAM files even if index file .crai exists. It turns out, in the case the index is not set explicitly CRAMFileReader does not try to find CRAM index file. We propose improvements in htsjdk project that make CRAMFileReader works with CRAM index automatically. To achieve this, we have expanded constructors in CRAMFileReader as follows: if indexFile is null try to find it using method findIndex in SamFiles class. All proposed improvements include unit tests to validate the results.
> Fix for picard issue 574: cram reader should look for the index file automatically

- src/main/java/htsjdk/samtools/SAMSequenceDictionary.java
- src/test/java/htsjdk/samtools/SAMSequenceDictionaryTest.java
This adds a static function that can merge two SamSequenceDictionaries into one. The problem it's solving is that in MergeBamAlignment the reference dictionary and the aligned Bam dictionary, while having the same sequences, may have different tags. In particular, the reference dictionary has lots of interesting tags like MD, SP, UR etc. and the (bwa) dictionary in the aligned bam may contain AH which informs us that the sequence is an Alternative Haplotype. 
This PR enables MergeBamAlignment to merge the two dictionaries rather than only use the reference one (as it currently does)
> Yf add tag aware merge samdictionary

- src/main/java/htsjdk/variant/variantcontext/StructuralVariantType.java
- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/main/java/htsjdk/variant/vcf/VCFConstants.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
- src/test/resources/htsjdk/variant/structuralvariants.vcf
As I'm playing with structural variation and the tool 'lumpy-sv', this PR introduces a new enum htsjdk.variant.variantcontext.StructuralVariantType describing the SV types defined in the VCFSpec 4.2:
```
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
Value should be one of DEL, INS, DUP, INV, CNV, BND. 
```
- A constant SVTYPE was added in VCFConstants
- getStructuralVariantType() was added to VariantContext
- I've added a test and a test file src/test/resources/htsjdk/variant/structuralvariants.vcf that could become more complicated in the future (e.g: decoding the BND data).
> new enum htsjdk.variant.variantcontext.StructuralVariantType describing the SV types 

- src/main/java/htsjdk/samtools/util/Log.java
Implements https://github.com/samtools/htsjdk/issues/739.
Do not want to get DEBUG messages by default.
> Change default logging level to INFO

- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
We represent PR that contains increased test coverage for `SamFileValidator` class with the following changes in `ValidateSamFileTest`:
- Make simple refactoring for `executeValidation` method
- Add new test for `validateBamFileTermination` method
- Add new test and new data provider for validating E2 tag and U2 tag process correctness.
Also, we suggest the following changes in `SamFileValidator` class:
- Initialize `SamFileValidator`'s fields by constructor instead of using default values
- Add getter for `errorsByType` field with package access for testing.
> Increased test coverage for SamFileValidator

- src/main/java/htsjdk/variant/variantcontext/CommonInfo.java
- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
- Fixes #371 including list getters as String, Integer and Double.
> More getters for VariantContext

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
making the changes requested in #657
Fixes for broadinstitute/picard#519
> Kt varient context change

- src/main/java/htsjdk/variant/vcf/VCFFilterHeaderLine.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
Using a VCFFilterHeaderLine as a java-bean, I was surprised to see that there is no (?) public/easy way to get the "Description" of a VCFFilterHeaderLine . This PR adds the method `getDescription()` ; It returns the ID if the description is empty. 
I've also added some `final` keywords and the `serialVersionUID`
> Added getDescription() in VCFFilterHeaderLine

- src/main/java/htsjdk/samtools/util/CustomGzipOutputStream.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
There is a `CustomGzipOutputStream` in HTSJDK for setting the compression level at construction, which is used in `IOUtils.openGzipFileForWriting(File file, boolean append)`. But if you want to wrap an `OutputStream` from other sources (like a `Path`) using the `Defaults.COMPRESSION_LEVEL` or other compression, it is impossible to set unless this class is coded again.
> Public CustomGzipOutputStream

- src/main/java/htsjdk/samtools/SAMSequenceDictionaryCodec.java
- src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/test/java/htsjdk/samtools/SAMSequenceDictionaryCodecTest.java
We introduce two pull requests to Htsjdk and Picard Tools(https://github.com/broadinstitute/picard/pull/687) to resolve the issue https://github.com/broadinstitute/picard/issues/432 .
Original version of CreateSequenceDictionary creates and stores all reference sequences entirely in memory in a SAMHeader object and then writes it to a file.
In order to check sequence's names for uniqueness, they are added to a HashSet. This might lead to "Out of memory" exceptions for files with a large number of sequences .
**Changes in Htsjdk:**
In our implementation we introduce a new "on fly" codec SAMSequenceDictionaryCodec, which encodes each sequence and directly writes it to the Dictionary file. This allows us not to store sequences in memory.
**Changes in Picard Tools:**
CreateSequenceDictionary …
> Fix for issue #432 in Picard Tools. CreateSequenceDictionary stalls indefinitely with large genomes 

- src/main/java/htsjdk/samtools/SamPairUtil.java
- src/main/java/htsjdk/samtools/util/CollectionUtil.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/IntervalList.java
- src/main/java/htsjdk/tribble/Feature.java
- src/main/java/htsjdk/tribble/SimpleFeature.java
- src/main/java/htsjdk/tribble/bed/SimpleBEDFeature.java
- src/main/java/htsjdk/tribble/example/CountRecords.java
- src/main/java/htsjdk/tribble/example/ExampleBinaryCodec.java
- src/main/java/htsjdk/tribble/gelitext/GeliTextFeature.java
- src/main/java/htsjdk/tribble/index/IndexFactory.java
- src/main/java/htsjdk/tribble/index/interval/IntervalIndexCreator.java
- src/main/java/htsjdk/tribble/index/linear/LinearIndexCreator.java
- src/main/java/htsjdk/tribble/index/tabix/TabixIndexCreator.java
- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/main/java/htsjdk/variant/variantcontext/VariantContextComparator.java
- src/main/java/htsjdk/variant/variantcontext/VariantJEXLContext.java
- src/main/java/htsjdk/variant/variantcontext/writer/BCF2FieldWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/BCF2Writer.java
- src/main/java/htsjdk/variant/variantcontext/writer/SortingVariantContextWriterBase.java
- src/main/java/htsjdk/variant/vcf/VCFEncoder.java
- src/main/java/htsjdk/variant/vcf/VCFFileReader.java
- src/test/java/htsjdk/samtools/sra/AbstractSRATest.java
- src/test/java/htsjdk/tribble/bed/BEDCodecTest.java
- src/test/java/htsjdk/tribble/gelitext/GeliTextTest.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextTestProvider.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
I explore some of the deprecated classes/methods when cleaning some of my own code, and I found that there are usages of some of this methods in other parts of htsjdk. This is a PR to clean the usages and to ask for removal of some deprecated classes/methods no longer used. This includes:
- ~~Fixes #330~~ Already fixed in other PR
- Changed all `Feature.getChr()` to `Feature.getContig()` usages in htsjdk.
- Remove `SRAAccession.isSupported()` usages in the tests and change for the recomended one.
- Annotating some deprecated methods with `@Deprecated` and `/** @deprecated */`
- Adding javadoc `{@link }` for pointing to new/correct usage.
- ~~Asking for removal of classes and methods for different packages, including gelitext support, `VariantContextWriterFactory` and others.~~ Edited: …
> Clean some deprecated classes/methods usages in htsjdk

- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
Added support for use case where index is a file, and the source stream is a seekable path.  This is important to allow users to pull down an index locally while querying a BAM in GCS.  Currently the performance of leaving the index in GCS in unacceptable.
> Fixed bug disallowing file-based index and seekable path based source

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
Implements https://github.com/samtools/htsjdk/issues/757.
Need to validate the number of elements in AC and AF without genotypes.
> Validate VariantContext AC and AF without genotypes

- src/main/java/htsjdk/variant/variantcontext/JEXLMap.java
- src/main/java/htsjdk/variant/variantcontext/JexlMissingValueTreatment.java
- src/main/java/htsjdk/variant/variantcontext/VariantContextUtils.java
- src/test/java/htsjdk/variant/variantcontext/VariantJEXLContextUnitTest.java
adding the ability to control how jexl expressions are handled when the expression contains literals that are not present in the context
it is now possible to have a jexl expression either match, not match, or throw an exception if there is a missing value
did some refactoring of JexlMap to make methods less stateful
> adding ability to control jexl expression behavior when missing values

- src/main/java/htsjdk/samtools/reference/AbstractFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java
- src/test/java/htsjdk/samtools/reference/ReferenceSequenceFileFactoryTests.java
Changes for https://github.com/broadinstitute/picard/pull/712 and https://github.com/broadinstitute/gatk/pull/2243
> Methods for default sequence dictionary name

- .travis.yml
- README.md
- build.gradle
- codecov.yml
codecov seems to be more accurate since it incorporates a notion of "partially covered lines"
it also makes reviewing pr's easier since coverage can be shown inline during reviews with a browser plugin
> switching from coverals to codecov

- src/main/java/htsjdk/samtools/DuplicateScoringStrategy.java
DuplicateScoringStrategy is a class used by Picard's MarkDuplicates for the purpose of choosing the "best" read/read-pair from a duplicate set. It has multiple strategies, but they all ignore the filter-flag. This means (as mentioned in https://github.com/broadinstitute/picard/issues/690) that in some cases a duplicate-set will end up being represented by a filter-failing read, which will then be ignored by most downstream tools. 
To fix this problem, this PR discounts the score of reads if they are failing the vendor flag. The other scores are capped to guarantee that the discount is large enough.
> Discounts reads that are non-filter-passing in DuplicateScoringStrategy 

- src/main/java/htsjdk/tribble/TribbleIndexedFeatureReader.java
- src/test/java/htsjdk/tribble/TribbleIndexFeatureReaderTest.java
Removed unused package-specific (visible for testing) deprecated method. Found in #707.
> Removing TribbleIndexedFeatureReader.isGZIPPath deprecated method

- src/main/java/htsjdk/samtools/SamInputResource.java
- src/main/java/htsjdk/samtools/util/Lazy.java
- src/main/java/htsjdk/variant/variantcontext/VariantContextUtils.java
Lazy previously accepted a custom interface called LazyInitializer which is redundant with Supplier since java 8
made LazyInitializer extend Supplier
changed the constructor to take generic Supplier instead of only LazyInitializers
> refactoring Lazy to take a Supplier()

- src/test/java/htsjdk/samtools/util/PositionalOutputStreamTest.java
> Fixed unmappable character for encoding ASCII

- build.gradle
- src/main/java/htsjdk/samtools/SamInputResource.java
- src/main/java/htsjdk/samtools/seekablestream/SeekableStreamFactory.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/tribble/util/ParsingUtils.java
- src/main/java/htsjdk/variant/vcf/AbstractVCFCodec.java
- src/test/java/htsjdk/tribble/util/ParsingUtilsTest.java
Added support for java.util.nio.Path for some more code pathways.
This is to support loading of Features with Spark in GATK.
> Support use of Path in ParsingUtils, SeekableStreamFactory, AbstractVCFCodec

- src/main/java/htsjdk/samtools/util/DateParser.java
- src/main/java/htsjdk/samtools/util/IntervalTree.java
- src/main/java/htsjdk/samtools/util/SequenceUtil.java
- src/test/java/htsjdk/samtools/BAMFileIndexTest.java
- src/test/java/htsjdk/samtools/util/DateParserTest.java
- src/test/java/htsjdk/samtools/util/IntervalTreeMapTest.java
- src/test/java/htsjdk/samtools/util/IntervalTreeTest.java
- src/test/java/htsjdk/samtools/util/SequenceUtilTest.java
- added tests to the most egregious classes (regarding test coverage) I could find.
- found a tiny bug in the logic of overlaps in the Node class.
> Increase Test Coverage, fix tiny bug in Node class (regarding OVERLAPS)

- src/main/java/htsjdk/samtools/SAMRecord.java
Clarify SAMRecord documentation so that users are not confused by thinking the opposite of what is meant.
- Three variable descriptions changed: getAlignmentStart, setAlignmentStart and getAlignmentEnd. Before, each read, "position of the clipped sequence," and now each reads, "position of the sequence remaining after clipping," for all three variable descriptions. 
- In addition, took liberty to clarify "or 0 if there is no position" further. Now reads, "If no position, as would occur e.g. for the unmapped mate of a singly mapping pair, returns 0." Talked briefly to LB and agreed _not_ to link to GATK documentation within htsjdk given it is a standalone project.
> Shl edit samrecord docs

- src/main/java/htsjdk/samtools/SamInputResource.java
- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/main/java/htsjdk/samtools/seekablestream/SeekablePathStream.java
- src/test/java/htsjdk/samtools/PathInputResourceTest.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
- src/test/java/htsjdk/samtools/SamReaderTest.java
Extend optional wrapping to the index.
> wrap both path and index

- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
Simple PR for retrieve the defaults that were set in the `SAMFileWriterFactory`class.
__Motivation:__ API clients may want to request which defaults were set for re-use then in other classes or log them.
> Add getters for defaults SAMFileWriterFactory fields

- src/main/java/htsjdk/samtools/BAMFileReader.java
- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/main/java/htsjdk/samtools/util/AsyncBlockCompressedInputStream.java
- src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/main/java/htsjdk/samtools/util/BlockGunzipper.java
- src/main/java/htsjdk/samtools/util/zip/InflaterFactory.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
- src/test/java/htsjdk/samtools/util/BlockCompressedInputStreamTest.java
- src/test/java/htsjdk/samtools/util/BlockCompressedOutputStreamTest.java
Created the `InflaterFactory` class and added a `defaultInflaterFactory` to `BlockGunzipper`. By default, the `defaultInflaterFactory` creates a Java `Inflater`, so `htsjdk` default behavior remains the same.
The `InflaterFactory` enables the use of accelerated `Inflater` implementations, like the one in an upcoming release of [GKL](https://github.com/Intel-HLS/GKL).
Applications can set the default `InflaterFactory` using this static method:
```java
BlockGunzipper.setDefaultInflaterFactory(myInflaterFactory);
```
Applications can override the default `InflaterFactory` using:
```java
SamReader reader = SamReaderFactory.makeDefault().inflaterFactory(myInflaterFactory);
```
> Add InflaterFactory

- src/main/java/htsjdk/samtools/util/BlockGunzipper.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
- src/test/java/htsjdk/samtools/util/BlockCompressedInputStreamTest.java
A few remaining tweaks to the custom InflaterFactory support left over from the
final review round of https://github.com/samtools/htsjdk/pull/771
> Small patches to custom InflaterFactory support left over from code review

- src/main/java/htsjdk/samtools/util/CustomGzipOutputStream.java
I made public the `CustomGzipOutputStream` in #746 to use it outside `IOUtils`, but I forgot to made the constructors public too. This fix the problem and makes the custom gzip wrapper available for use it outside the package.
> Make public constructors in CustomGzipOutputStream

- src/main/java/htsjdk/samtools/BAMFileReader.java
- src/main/java/htsjdk/samtools/BAMFileSpan.java
- src/main/java/htsjdk/samtools/SamReader.java
- src/test/java/htsjdk/samtools/BAMFileSpanTest.java
... and expose methods for iterating over a part of a BAM file (needed for Hadoop-BAM,
which processes BAM files in parallel, see https://github.com/HadoopGenomics/Hadoop-BAM/issues/91).
Also, add BAMFileSpan#removeContentsAfter method to mirror
removeContentsBefore.
> Make BAMFileReader and some related classes public

- src/main/java/htsjdk/samtools/util/Md5CalculatingOutputStream.java
Very simple patch to allow writing the MD5 digest file to a path.
> Md5CalculatingOutputStream support for Path

- src/main/java/htsjdk/samtools/CRAMFileReader.java
- src/main/java/htsjdk/samtools/CRAMIterator.java
- src/test/java/htsjdk/samtools/CRAMFileReaderTest.java
- src/test/java/htsjdk/samtools/SamReaderSortTest.java
Currently, SAMRecordIterator implementations in CRAMFileReader don't implement assertSorted method correctly. Firstly, in CRAMFileReader.CRAMIntervalIterator this method always returns null. Secondly, in CRAMIterator class this method just throws a runtime exception.
In case of CRAMIterator the solution is implementing this method using wrapping with SamReader.AssertingIterator class. The second class for CRAM iteration is inner private class CRAMFileReader.CRAMIntervalIterator. We changed its interface to CloseableIterator<SAMRecord>, since it allows us to keep all current functionality and this class is never used as SamRecordIterator, so assertSort method is useless for it. Also, we added new unit test to check code correctness.
> Fix for issue #547

- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
fixing the 4 annoying warnings that pop up whenever you compile tests
I also added a test case that seems to have been accidentally forgotten, the variable was constructed but not added to the dataprovider.
the first commit just fixes the extraneous <type>, the second commit has the casts and the extra test case
> fixing vararg warnings on test compilation

- src/main/java/htsjdk/tribble/Feature.java
As pointed out in #813, the `Feature` interface is meant to be a marker for a `Locatable` with tribble support. This is a simple documentation patch to:
1.  point out what is the purpose of this class.
2. add a date note to the deprecation of  `getChr()`. Because of the move to the gradle structure, I cannot pinpoint the exact date of deprecation, but at least we know that is before 2016 May.
The first point is to clarify why tribble is using `Feature` instead of `Locatable` (and avoid proposals like #812), and the second is to help in the API evolution (to be able to remove at some point deprecated methods).
> Update javadoc for Feature

- src/main/java/htsjdk/samtools/AbstractSAMHeaderRecord.java
- src/main/java/htsjdk/samtools/SAMFileHeader.java
- src/main/java/htsjdk/samtools/SAMProgramRecord.java
- src/main/java/htsjdk/samtools/SAMReadGroupRecord.java
- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
- src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/test/java/htsjdk/samtools/SAMProgramRecordTest.java
- src/test/java/htsjdk/samtools/SAMReadGroupRecordTest.java
- src/test/java/htsjdk/samtools/SAMSequenceRecordTest.java
Fairly minor, this just allows programmatic access to the string representation of a read group, in much the same way as SAMRecord.getSAMString(). AFAIK there currently isn't really a non-convoluted way to get this. This is useful for displaying to the end user a problematic SAM read group.
> Allow the use of getSAMString on SAMReadGroupRecord objects

- src/main/java/htsjdk/samtools/BAMRecord.java
- src/main/java/htsjdk/samtools/BAMRecordCodec.java
- src/main/java/htsjdk/samtools/SAMUtils.java
- src/test/java/htsjdk/samtools/SAMUtilsTest.java
Fixes https://github.com/broadinstitute/picard/issues/781.
Added the `base` and `read` names to the exception message in `SAMUtils.charToCompressedBase`.
> Make exception message informative in SAMUtils.charToCompressedBase

- src/test/java/htsjdk/samtools/util/DateParserTest.java
Several of the DateParserTest unit tests were failing in my locale due to their use of the deprecated Date.parse() method. It seems to me that the existing steps of Date.parse(date.toString()) weren't really accomplishing anything related to htsjdk code (perhaps it was required in past JREs in order to get unix timestamps), so have simplified the assertion to just compare the time stamps directly.
> Fix DateParserTest unit tests that were failing in my locale.

- src/main/java/htsjdk/variant/vcf/VCFUtils.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
Implements https://github.com/samtools/htsjdk/issues/847.
> Maintain ordering of header

- src/main/java/htsjdk/samtools/util/AbstractRecordAndOffset.java
- src/main/java/htsjdk/samtools/util/EdgingRecordAndOffset.java
- src/test/java/htsjdk/samtools/util/AbstractRecordAndOffsetTest.java
In current version of master branch there is a problem with SamLocusIterator.RecordAndOffset class. This class inherits public method getRefPos that always returned -1.
We suggest to remove this method from AbstractRecordAndOffset class and replace it in abstract class EdgingRecordAndOffset, which heritors use this method.
> Fix for SamLocusIterator.RecordAndOffset

- src/main/java/htsjdk/samtools/CigarElement.java
- src/test/java/htsjdk/samtools/util/CigarElementUnitTest.java
Class `CigarElement` currently doesn't check for the length provided in its ctor. This PR adds that check.
- [NA] Extended the README / documentation, if necessary
> check for negative length in CigarElement ctor

- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
Count the number of warnings and errors so Picard's ValidateSamFile can determine the appropriate exit code described in https://github.com/broadinstitute/picard/issues/794.
> Count the number of warnings and errors during SAM file validation

- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/IntervalList.java
- src/test/java/htsjdk/samtools/util/IntervalListTest.java
I added a `fromPath` method that is analogous to the `fromFile` static method in `IntervalList`.  I added a simple test to make both behave similarly.
> Add fromPath to IntervalList.

- src/main/java/htsjdk/samtools/fastq/FastqReader.java
Simple patch for a more informative `IOException` handling in `FastqReader`, by including the message and the line.
> More informative IO error for FASTQ reader

- src/main/java/htsjdk/samtools/SAMFileHeader.java
- src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/main/java/htsjdk/samtools/SAMValidationError.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
- src/test/java/htsjdk/samtools/cram/lossy/QualityScorePreservationTest.java
Adds validation to the values in the SO and GO tags in the SAM header.
> Yf add unknown so

- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/main/java/htsjdk/samtools/SAMFileWriterImpl.java
- src/test/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
Several constructors don't do what they should regarding tmpDir.
Ensured that both initWriter and initializeBAMWriter both call setTempDirectory() when needed, and made one of the existing constructors make use of initWriter() (This private method had an unused parameter, which has been removed)
We encountered this by running out of disk space while sorting a file during output.
> Obey the tmpDir setting in several constructors that currently ignore it

- src/test/java/htsjdk/samtools/util/AsyncBufferedIteratorTest.java
AsyncBufferedIteratorTest.testBackgroundBlocks() is subject to a race condition as it is a testing the async loading of records in AsyncBufferedIterator, but is not privy to the internal state of the iterator. Additional logic has been added such that the test case race condition is now extremely unlikely to be encountered.
> Defensive programming around test case race condition to address #776

- .travis.yml
Added OpenJDK8 as a build configuration to be tested via Travis.
> Adding OpenJDK8 to travis configuration

- src/main/java/htsjdk/samtools/fastq/FastqReader.java
- src/test/scala/htsjdk/samtools/fastq/FastqReaderWriterTest.scala
FastQReader doesn't handle leading blank lines correctly in all constructors.
- [x ] Code compiles correctly
- [x ] New tests covering changes and new functionality
- [x ] All tests passing
> Fix ordering of assignments in FastQReader constructor.

- src/main/java/htsjdk/samtools/util/Md5CalculatingOutputStream.java
> - fixed a small NPE in MD5CalculatingOutputStream

- src/main/java/htsjdk/tribble/index/AbstractIndex.java
- src/main/java/htsjdk/tribble/index/Index.java
- src/main/java/htsjdk/tribble/index/tabix/TabixIndex.java
- src/test/java/htsjdk/tribble/index/IndexTest.java
> Index.writeBasedOnFeaturePath should throw instead of silently Failing

- src/main/java/htsjdk/samtools/SamReaderFactory.java
Reverts samtools/htsjdk#879
Somehow this broke the build. Reverting until further investigation.
> Revert "The existing code was throwing a NPE when using a CRAMFileReader for …"

- src/main/java/htsjdk/samtools/util/IntervalList.java
- src/test/java/htsjdk/samtools/util/IntervalListTest.java
Finds all intervals in the first list that overlap any interval in the
second list.
@yfarjoun  would you have a chance to review?  I know @tfenne is on vacation this week and I know you are familiar with this code.  Otherwise, I can ask @lbergelson or @jacarey to review?
Relates to https://github.com/nh13/picard/pull/7
> Adding an overlaps function to IntervalList.

- src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/test/java/htsjdk/samtools/util/BlockCompressedTerminatorTest.java
BlockCompressedInputStream.checkTerminator only worked on files.  Gatk4 needs it to accept Paths and ideally SeekableByteChannels directly.  Adding overloads that take Path and SeekableByteChannel and refactoring the internals to use SeekableByteChannel instead of RandomAccessFile.
> overloading BlockCompressedInputStream.checkTerminator to support NIO

- src/main/java/htsjdk/samtools/util/IntervalTreeMap.java
I've changed the signature of four functions in **IntervalTreeMap**. Instead of using a concrete class  'Interval', they will use 'Locatable'. It shouldn't break the code.
Furthermore it avoids to create a new Interval for each query. 
```
map.containsOverlapping( new Interval(variantContext.getContig(), variantContext.getStart(), variantContext.getEnd()));
```
it's now
```
map.containsOverlapping(variantContext)
```
- [x ] Code compiles correctly
> IntervalTreeMap: use Locatable interface

- build.gradle
* the Broad artifactory moved from a self hosted repository at artifactory.broadinstitute.org
to a web based artifactory at broadinstitute.jfrog.io/broadinstitute/
this was causing our snapshot uploads to fail
* updating our snapshot repository to point to the new link
* the old artifactory has a redirect in place to the new artifactory so
artifacts relying on the old url should still resolve.  For unknown
reasons this redirect doesn't work with gradle uploads, probably a
gradle bug.
> updating artifactory link to point to new artifactory

- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/util/StringUtil.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
Fixes https://github.com/samtools/htsjdk/issues/297.
Fixed SAMRecord.getReadLength by not calling getReadBases().length read bases is null.
Added a unit test.
Made private unit tests public so they can be run.
> Fix SAMRecord.getReadLength() so it does not throw an exception if null bases

- src/main/java/htsjdk/samtools/DuplicateScoringStrategy.java
- src/test/java/htsjdk/samtools/DuplicateScoringStrategyTest.java
Fixes https://github.com/samtools/htsjdk/issues/256.
The read comparing duplicates, if one of the reds is not paired, the first read in the comparison should return -1 if it is paired, not 1.
> Fixed flipped sign when comparing read paired flags

- src/main/java/htsjdk/samtools/util/BlockCompressedOutputStream.java
On some systems `BlockCompressedOutputStream.close()` will try to open `/dev/stdout` for reading in order to check that it wrote the terminator block correctly.  This attempts to prevent that.
> A little more caution when checking terminator blocks on close of BlockCompressedOutputStream

- src/main/java/htsjdk/samtools/AbstractSAMHeaderRecord.java
- src/main/java/htsjdk/samtools/SAMFileHeader.java
- src/test/java/htsjdk/samtools/SAMFileHeaderTest.java
@yfarjoun could you take a look since this fixes a bug you introduced, and @tfenne can a maintainer take a look?
The issue was that folks can call `setAttribute("SO", "queryname")` and the cached sort order introduced in ad8aa02aa2ed02b9cb2bb8801c3e6897e91ec3f6 would not get updated.  Similarly for the group order.
> Sort and group order not updated when using setAttribute.

- src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/test/java/htsjdk/samtools/util/BlockCompressedOutputStreamTest.java
> Make stream seek error message informative

- README.md
Updated the readme to include more information on licensing, updated links to documentation and suggestions on how to interact with the project.
> Updates to readme about documentation, communication & license.

- src/test/java/htsjdk/samtools/BAMFileSpanTest.java
- src/test/java/htsjdk/samtools/DuplicateScoringStrategyTest.java
- src/test/java/htsjdk/samtools/PathInputResourceTest.java
- src/test/java/htsjdk/samtools/SAMProgramRecordTest.java
- src/test/java/htsjdk/samtools/SAMReadGroupRecordTest.java
- src/test/java/htsjdk/samtools/SAMSequenceRecordTest.java
- src/test/java/htsjdk/samtools/fastq/FastqEncoderTest.java
- src/test/java/htsjdk/samtools/util/CigarElementUnitTest.java
Some tests were not running because they lack the HtsjdkTest marker. This PR adds the missing marker to these classes, which now are executed by the test task.
> Fix no running tests due to lack of HtsjdkTest marker

- src/main/java/htsjdk/samtools/util/Log.java
- src/test/java/htsjdk/samtools/util/LogTest.java
Clients, such as GATK, want to capture the htsjdk output log data to a file. This capability is required for fully implementing https://github.com/broadinstitute/gatk/pull/2751.
> Add ability to log to file

- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/variant/variantcontext/writer/IndexingVariantContextWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/test/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
Related to: https://github.com/broadinstitute/picard/issues/863
If we call `.setOutputFile` with `"/dev/stdout"`, then `this.outputStream` is `null`, this.outFile` is `File("/dev/stdout")`, and `this.outType` is `OutputType.VCF_STREAM`.  When calling `build()`, it will throw a NPE!
> Write vcf to stdout

- src/main/java/htsjdk/variant/vcf/VCFFileReader.java
Updated the javadocs so that it's clear that an error will be thrown without an index.
Based on recommendations from https://github.com/broadinstitute/picard/issues/814.
Note that this was implemented by @ben10wald who doesn't have push access to this repo.
> Updated javadocs for query method

- src/main/java/htsjdk/samtools/util/IOUtil.java
I want to use the individual constants outside of the list, so need them broken out.
> Broke out the static variables so that they can be used separately.

- src/main/java/htsjdk/tribble/index/IndexFactory.java
closing a stream in `IndexFactory` that was previously leaked
* `IndexFactory.FeatureIterator.initIndexableBlockCompressedStream` left an unused stream open
it's now automatically closed
* made two private methods static
- [ x ] Code compiles correctly
- [  ] All tests passing
> close stream in IndexFactory

- src/main/java/htsjdk/variant/vcf/VCFHeader.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
Interim fix for https://github.com/samtools/htsjdk/issues/934. https://github.com/samtools/htsjdk/pull/835 has a more permanent fix but is a much bigger change.
Whenever a new contig header line is added to a VCFHeader (i.e. during file parsing), the implementation looks for duplicates by comparing the new id with every contig header line already in the header, which is very slow on large headers. Replaced the brute force search with a hash lookup.
PrintVariantsExample running time for the test case provided in https://github.com/samtools/htsjdk/issues/934 (which is a 32k line, header-only file) goes from 30 seconds to .5 seconds.
> Fix performance issue when creating a VCF header with a large number of contigs

- src/main/java/htsjdk/samtools/FixBAMFile.java
The `FixBAMFile` is an undocumented and untested feature that does not add anything to the HTSJDK as a library. I propose to deprecate this class and remove it eventually.
> Proposal: deprecate FixBAMFile.java

- src/main/java/htsjdk/samtools/cram/ref/ReferenceSource.java
making field `rsFile` final and removing the private no-arg constructor
making the other constructors chain
@pshapiro4broad  Please review since you pointed this change out :)
> cleaning up constructors in ReferenceSource

- src/main/java/htsjdk/samtools/BAMFileWriter.java
- src/main/java/htsjdk/samtools/BAMIndexer.java
- src/main/java/htsjdk/samtools/BinaryBAMIndexWriter.java
- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/main/java/htsjdk/samtools/StreamInflatingIndexingOutputStream.java
- src/main/java/htsjdk/samtools/util/BinaryCodec.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/test/java/htsjdk/samtools/BAMIndexWriterTest.java
- src/test/java/htsjdk/samtools/CRAMComplianceTest.java
- src/test/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
- src/test/java/htsjdk/samtools/util/IoUtilTest.java
Add overloads to SAMFileWriterFactory that take `Path` as input instead of `File`. The old version that took `File` now just redirect to their `Path` equivalent, so there's the same amount of code to test.
The motivation for this change is to support Java NIO's pluggable file systems. This change (in combination with Google's NIO provider) allows one to directly write a SAM, BAM, or CRAM file to a Google Cloud Storage bucket. See eg. [GATK's matching issue](https://github.com/broadinstitute/gatk/issues/2422).
> add Path options for SAMFileWriterFactory

- src/main/java/htsjdk/samtools/BAMFileReader.java
- src/main/java/htsjdk/samtools/QueryInterval.java
- src/test/java/htsjdk/samtools/CRAMIndexQueryTest.java
- src/test/java/htsjdk/samtools/QueryIntervalTest.java
Optimizing intervals in `QueryInterval` class works incorrectly: intervals are considered abutting only if they overlap each other by a single base.
Need bug fix for current implementation of abuts(): `QueryInterval[]` array still contains two initial intervals after invoking `optimizeIntervals()` method, even though they touch. [Github issue](https://github.com/samtools/htsjdk/issues/971).
* `abuts()` method has been fixed. It used to return `true` only in case if one of them starts exactly where other ends. Now it returns `true` if one of the given intervals ends just before another one starts;
* `equals()` and `hashcode()` methods were overridden in `QueryInterval` class for using `assert` in TestNg;
* `testOptimizeIntervals()` was added to the `CRAMFileBAIIndexTest` class to test 3 …
> Optimize intervals falls to merge abutting intervals

- src/main/java/htsjdk/variant/variantcontext/writer/AsyncVariantContextWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/BCF2Writer.java
- src/main/java/htsjdk/variant/variantcontext/writer/SortingVariantContextWriterBase.java
- src/main/java/htsjdk/variant/variantcontext/writer/VCFWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriter.java
- src/test/java/htsjdk/variant/bcf2/BCF2WriterUnitTest.java
- src/test/java/htsjdk/variant/variantcontext/writer/AsyncVariantContextWriterUnitTest.java
- src/test/java/htsjdk/variant/variantcontext/writer/VCFWriterUnitTest.java
This PR addresses Issue #902.
Added support for setting and writing the header in two different steps for the classes derived from `VariantContextWriter`.
> Support for partial VCF writing

- build.gradle
- src/main/java/htsjdk/samtools/util/SnappyLoader.java
- src/main/java/htsjdk/samtools/util/TempStreamFactory.java
Upgrade snappy-java to the latest released version.  The version in HTSJDK was no longer working on macs as best I can tell (I only have one to test on).  The new version appears to work fine on my mac, and also on a single linux machine I tested on.
I've also added the option in SnappyLoader to log failures but be quiet on successes.
I also manually tested the loader with and without native libraries available, and it works as expected, which is nice as I was able to simplify quite a bit.
> Upgraded snappy-java to the latest released version.

- src/main/java/htsjdk/tribble/readers/TabixReader.java
- src/test/java/htsjdk/tribble/readers/TabixReaderTest.java
the main motivation of this small PR was to remove the  line.toCharArray() in TabixReader https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/tribble/readers/TabixReader.java#L419
```
char[] str = s.toCharArray();
(...)
if (str.length == 0 || str[0] == mMeta) continue;
```
replaced with:
```
if (s.isEmpty() || s.charAt(0) == mMeta) continue;
```
while I was here, I've added a few  `final`, fixed the name of some variables (e.g: 's' -> 'contig').
I've also added a variable `longestLineLength` that is used to allocate the capacity in the function:
```
private static String readLine(final InputStream is,final int bufferCapacity) throws IOException {
```
> TabixReader : delete s.toCharArray()

- src/main/java/htsjdk/variant/variantcontext/writer/SortingVariantContextWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/SortingVariantContextWriterBase.java
* deprecating the classes `SortingVariantContextWriter` and `SortingVariantContextWriterBase`
* these classes are completely untested and unused in htsjdk, picard, and gatk, we should either deprecate them or add tests and support them, but unless anyone has any use case I'd recommend deprecating
- [ x ] Is not backward compatible (breaks binary or source compatibility)
> deprecating SortingVariantContextWriter

- src/main/java/htsjdk/samtools/Defaults.java
- src/main/java/htsjdk/samtools/util/SnappyLoader.java
- src/test/java/htsjdk/samtools/util/SnappyLoaderUnitTest.java
There were a few changes I wanted to make to the previous snappy pull request but it seemed better to get the main part of that merged in and then deal with them rather than sit in limbo forever.
There are a 2 commits, hopefully the first is uncontroversial:
1st Commit: 
* move the system properties to Defaults to be consistent with the rest of the htsjdk system properties
* produce a more specific error message when failing to wrap a stream with snappy, and refactor to avoid duplicating the error message logic, the refactoring here might be overkill, but it seemed slightly cleaner to me than just duplicating the code, happy to roll that bit back though if it's too java8 for people's taste
* adding a few finals and try-with-resources to taste
2nd commit:
* removes the newly added …
> minor changes to snappy

- src/main/java/htsjdk/variant/variantcontext/writer/AsyncVariantContextWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/BCF2Writer.java
- src/main/java/htsjdk/variant/variantcontext/writer/SortingVariantContextWriterBase.java
- src/main/java/htsjdk/variant/variantcontext/writer/VCFWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriter.java
- src/test/java/htsjdk/variant/bcf2/BCF2WriterUnitTest.java
- src/test/java/htsjdk/variant/variantcontext/writer/AsyncVariantContextWriterUnitTest.java
- src/test/java/htsjdk/variant/variantcontext/writer/VCFWriterUnitTest.java
this seems cleaner, since we've never released this change it should be
ok to change the name without a deprecation process
> renaming VariantContextWriter.setVCFHeader -> setHeader

- src/main/java/htsjdk/samtools/util/AbstractAsyncWriter.java
This removes the explicit thread.interrupt() call from AbstractAsyncWriter close method. We're seeing this failure with GATK: if the close method is called while the writer thread is still executing code that is inside a try block that has a catch Exception clause (like [this block](https://github.com/samtools/htsjdk/blob/1ade6c921628e540f1cab0dfadfbdc536f702d73/src/main/java/htsjdk/samtools/BAMFileWriter.java#L133)), and that code is using NIO, an InterruptedException is thrown on the writer thread, and ultimately re-thrown as a SAMException, which causes the calling code to fail.
It looks like this can only happen if the queue is empty at the time the close method checks, but the writer thread is still processing the last item in the queue. Removing the interrupt call (and shortening …
> Don't generate interrupt on close in AbstractAsyncWriter.

- src/main/java/htsjdk/samtools/BAMFileWriter.java
- src/test/java/htsjdk/samtools/util/BinaryCodecTest.java
These DataOutputStream objects are being created needlessly and
confusingly (I suspect they are vestigial). BinaryCodec states that it
is responsible for ensuring the endian-ness (which it does internally
via its ByteBuffer).
This PR is just a minor cleanup that removes the redundant and confusing calls.
> Remove redundant use of DataOutputStream when passing to BinaryCodec.

- src/main/java/htsjdk/samtools/cram/ref/EnaRefService.java
- src/test/java/htsjdk/samtools/cram/ref/EnaRefServiceTest.java
- It seems that the ENA has moved to https which is why tests are failing. 
- This probably also affected cram access to ena resources. fixed.
- Reformated tests to use a data provider
> Fixed ENA url to use https (instead of http) 

- src/main/java/htsjdk/variant/variantcontext/Allele.java
We are currently defining the <NON_REF> allele in GATK (3 & 4) and Picard....it seems more reasonable to do it here in htsjdk.
> Defining <NON_REF> allele in htsjdk, where it belongs.

- src/main/java/htsjdk/samtools/NotPrimarySkippingIterator.java
- src/main/java/htsjdk/samtools/SAMFlag.java
- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/SAMRecordQueryNameComparator.java
- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/main/java/htsjdk/samtools/SAMUtils.java
- src/main/java/htsjdk/samtools/SamFlagField.java
- src/main/java/htsjdk/samtools/SecondaryAlignmentSkippingIterator.java
- src/main/java/htsjdk/samtools/SecondaryOrSupplementarySkippingIterator.java
- src/main/java/htsjdk/samtools/SecondarySkippingIterator.java
- src/main/java/htsjdk/samtools/cram/build/Cram2SamRecordFactory.java
- src/main/java/htsjdk/samtools/cram/build/Sam2CramRecordFactory.java
- src/main/java/htsjdk/samtools/filter/SecondaryAlignmentFilter.java
- src/main/java/htsjdk/samtools/filter/SecondaryOrSupplementaryFilter.java
- src/main/java/htsjdk/samtools/sra/SRALazyRecord.java
- src/test/java/htsjdk/samtools/SAMFlagTest.java
- src/test/java/htsjdk/samtools/SAMRecordQueryNameComparatorTest.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
- src/test/java/htsjdk/samtools/filter/IntervalKeepPairFilterTest.java
- src/test/java/htsjdk/samtools/filter/SecondaryAlignmentFilterTest.java
- src/test/java/htsjdk/samtools/sra/SRATest.java
The term "not-primary alignment" used in HTSJDK is confusing, because it refers only to "secondary alignment" but not "supplementary alignments". This commit deprecate classes/methdos using "not-primary" in favor of the "secondary" option (implemented if not already included).
> Deprecate 'not-primary' in favor of secondary along HTSJDK

- .gitignore
Building with Intellij 2017.2 generates an /out directory instead of
using the build/ folder from gradle. This commit remove this directory
from the tracked files.
This folder cannot be changed, even if the compiler output is changed (see CrazyCoder comment in https://stackoverflow.com/questions/45174989/building-with-intellij-2017-2-out-directory-duplicates-files-in-build-director).
> Add out/ to .gitignore

- src/main/java/htsjdk/variant/variantcontext/filter/VariantContextFilter.java
small simplication : `VariantContextFilter` is just a  `Predicate<VariantContext>`.
We can now use this in a `stream().filter(ctxFilter)`
> VariantContextFilter extends Predicate<VariantContext>

- src/main/java/htsjdk/variant/vcf/VCFFileReader.java
Fixed a resource leak in VCFFileReader.getSequenceDictionary(), the vcfFileReader was not closed, replace with a try-with-resource
> fixing resource leak in VCFFileReader.getSequenceDictionary()

- src/main/java/htsjdk/samtools/liftover/LiftOver.java
- src/test/java/htsjdk/samtools/liftover/LiftOverTest.java
Liftover currently logs each time an interval fails liftOverMinMatch.  This can result in a lot of logging, and callers cannot current control this behavior.  This adds a setLogFailedIntervals(), so callers can optionally turn off this logging.  It's opt-in and will not change current behavior for any callers.
> Ability to opt-out of logging all failed intervals for LiftOver

- src/main/java/htsjdk/samtools/util/BufferedLineReader.java
- src/test/java/htsjdk/samtools/util/BufferedLineReaderTest.java
LineNumberReader.read() compresses multiple-character line terminators into a single \n character. Thus, a single-character mark is insufficient in the peek() method, resulting in "Mark invalid" exceptions being thrown when a Windows line ending is encountered. The existing unit tests have been extended to check that peek() does not throw, and these fail when using the original 1 character mark.
> Fix BufferedLineReader peek() at end of line with Windows line endings.

- src/main/java/htsjdk/samtools/util/AbstractProgressLogger.java
- src/main/java/htsjdk/tribble/AsciiFeatureCodec.java
- src/main/java/htsjdk/utils/ClassFinder.java
- src/test/java/htsjdk/TestClassDependenceTest.java
- src/test/java/htsjdk/TestDataProviders.java
- src/test/java/htsjdk/samtools/BAMRemoteFileTest.java
- src/test/java/htsjdk/samtools/CRAMIndexQueryTest.java
- src/test/java/htsjdk/samtools/CRAMSliceMD5Test.java
- src/test/java/htsjdk/samtools/QueryIntervalTest.java
- src/test/java/htsjdk/samtools/cram/build/Sam2CramRecordFactoryTest.java
- src/test/java/htsjdk/samtools/cram/ref/ReferenceSourceTest.java
- src/test/java/htsjdk/samtools/metrics/MetricBaseTest.java
- src/test/java/htsjdk/samtools/util/BufferedLineReaderTest.java
- src/test/java/htsjdk/samtools/util/LocatableUnitTest.java
- src/test/java/htsjdk/tribble/AbstractFeatureReaderTest.java
- src/test/java/htsjdk/tribble/AsciiFeatureCodecTest.java
- src/test/java/htsjdk/utils/ClassFinderTest.java
- src/test/java/htsjdk/utils/TestNGUtils.java
(otherwise the dependent tests will be silently skipped)
Adds a test that makes sure that the @DataProviders are not failing. This is important since A failing data-provider causes the dependent tests to fail **silently** which means that an api change could cause parts of the code to be untested even though we have tests for them...
> Test that all the @DataProviders are successful 

- src/main/java/htsjdk/samtools/util/DiskBackedQueue.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/SortingCollection.java
- src/main/java/htsjdk/samtools/util/SortingLongCollection.java
- src/test/java/htsjdk/samtools/util/IoUtilTest.java
- New methods in IOUtil to support Paths
- Change DiskBackedQueue to use Paths
- Change SortingCollection to use Paths
- Change SortingLongCollection to use Paths
> More support for java.nio.Path: DiskBackedQueue and SortingCollection 

- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/test/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
Auth-related auth errors [would be easier to debug](https://github.com/broadinstitute/gatk/issues/2422#issuecomment-342255531) if our error message included something about the cause.
This change adds this bit of text for those errors with `SamFileWriterFactory`, and a test to make sure it's there. It only addresses the concern about clarity of the error, not about the correct display of the file name.
> Add a mention of the cause to SAMFileWriterFactory error messages

- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
Added an option to the SAM validator to skip mate validation.
Mate validation is an extremely expensive operation memory-wise for certain classes of data.  Specifically, inputs that either have duplicate sets with many millions of reads or that have high rates of chimerism will trigger terrible edge case behavior requiring the tool to maintain many (many, many) reads in memory.  This just provides a simple way for one to generally validate those files without requiring the massive memory footprint (or ripping the guts out and rewriting it all).
> Adds option to validator to skip mate validation

- src/main/java/htsjdk/samtools/util/AbstractLocusIterator.java
Optimization of the iteration algorithm of the `AbstractLocusIterator`. 
When we use `SamLocusIterator` iteration over read that contains a long skipped region is very slow (about 27 seconds to skip 500 kbp - measurement from [issue](https://github.com/samtools/htsjdk/issues/838)).
Method `populateCompleteQueue()` used to remove empty regions from the `accumulator` by multiple invocations of the 'ArrayList' method  `remove()` (which uses System.arrayCopy() on each invocation). 
Empty regions now removed from accumulator with `ArrayList` method `removeIf()`.
Test from issue took 1,6 sec. in our environment (in old realization it took 120 sec under the same conditions).
Other performance measurements:
| Cigar | Old method (ops/ms) | New method (ops/ms) |
| ------ | ------ | ------ |
| …
> Fix very slow iteration over single read

- build.gradle
- src/main/java/htsjdk/samtools/util/SortingCollection.java
Fix Issue #1030 by restoring `SortingCollection.newInstance()` to its behavior before PR #910.
It compiles.
Wasn't tested before. Isn't tested now.
They pass, but the JVM throws on shutdown as before. See Issue #1029.
> Issue #1030: Restore default tmpdir for SortingCollection before PR #910.

- src/main/java/htsjdk/samtools/util/IOUtil.java
fixing the crash on shutdown introduced in #910 by changin the command
that gets run on deleteOnExit
Files.delete() -> Files.deleteIfExists()
this will prevent the jvm from crashing on shutdown if the temporary
files get cleaned up before it closes
This still leaves open the possibilty of crash on shutdown if the
temporary file is unable to be removed for some other reason.  That's
subtly different than the File version of deleteOnExit, but it may be
useful to get these error messages in the unusual case of failing to
delete a file that exists.
fixes #1029
> fixing crash on shutdown hook #1029

- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileWalker.java
- src/test/java/htsjdk/samtools/reference/ReferenceSequenceFileWalkerTest.java
All `File`s are `Path`s, but not vice versa (paths can point to e.g. cloud storage). Hence it's important to have a version of the `ReferenceSequenceFileWalker` constructor that accepts a `Path` for ease of use (even though, now that I look at the code carefully, I see the caller could work around this by constructing their own `ReferenceSequenceFile` first).
This came up while working on an aspect of [Cloud support for GATK](https://github.com/broadinstitute/gatk/pull/3921).
> ReferenceSequenceFileWalker ctor accepts Path

- src/main/java/htsjdk/samtools/Defaults.java
The EBI CRAM reference registry has been recently changed to use https instead of http.
The EBI_REFERENCE_SERVICE_URL_MASK should be changed to reflect this.
Best Regards,
Rasko Leinonen
European Nucleotide Archive (ENA)
> EBI_REFERENCE_SERVICE_URL_MASK to use https.

- src/main/java/htsjdk/samtools/DownsamplingIteratorFactory.java
replaced ">=" with "more than" in the description of Chained downsampling strategy so that it's possible to render it using the javadoc ''@value' pragma.
> - replaced ">=" with "more than" in the description

- src/main/java/htsjdk/samtools/util/MergingIterator.java
- src/test/java/htsjdk/samtools/util/MergingIteratorTest.java
`MergingIterator.close()` could throw `ConcurrentModificationException` when called mid-iteration with at least three sub-iterators as described in https://github.com/samtools/htsjdk/issues/1055.
This PR changes the `close()` method to remove iterators from `MergingIterator`'s internal queue via an iterator rather than from the collection directly.
> Fix MergingIterator.close() to avoid ConcurrentModificationException

- src/main/java/htsjdk/tribble/AbstractFeatureReader.java
- src/test/java/htsjdk/tribble/AbstractFeatureReaderTest.java
Fixes htsjdk issue #1021
minor refactor of https://github.com/samtools/htsjdk/pull/1022 by @jrobinso 
added a test for the string case
> strip query from URL before testing extension

- src/main/java/htsjdk/samtools/filter/ReadNameFilter.java
- src/main/java/htsjdk/samtools/filter/TagFilter.java
- src/test/java/htsjdk/samtools/filter/TagFilterTest.java
Some people would like to select reads based on tag values and not just filter.  This allows this filter to both pass and filter reads.
> Modify FilterTag to Pass or Filter reads

- src/main/java/htsjdk/tribble/TabixFeatureReader.java
In `readHeader()` and `iterator()` methods, use `SeekableStreamFactory` instance to read the feature file instead of `ParsingUtils`. This brings them into line with how it's accessed via `TabixReader` everywhere else in this class. The reason it's not just foolish consistency is explained in #1042; i.e. if you implement your own `ISeekableStreamFactory` to handle some special protocol then that will be used everywhere that the URL is opened in `TabixFeatureReader`, not just in some places.
> fix for #1042

- src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/test/java/htsjdk/samtools/util/BlockCompressedInputStreamTest.java
BlockCompressedInputStream can be constructed directly from an
InputStream, and in such cases mFile is null. However, several exception
messages try to use mFile.getSource() in the message, which triggers a
NullPointerException rather than the intended type of exception.
> Don't attempt mFile.getSource() in BlockCompressedInputStream when mFile is null.

- src/main/java/htsjdk/samtools/seekablestream/SeekableStream.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableMemoryStreamTest.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamTest.java
`SeekableStream` is a random access implementation of `InputStream`, which conceptually is able to support marking in any case. This PR adds mark support to the abstract class `SeekableStream`, to allow every implementation to support marks.
In addition, it improves the seekable stream documentation.
> Add mark support for SeekableStream

- src/main/java/htsjdk/samtools/util/SortingCollection.java
- src/test/java/htsjdk/samtools/util/SortingCollectionTest.java
In parallel implementation of `MarkDuplicates` (https://github.com/broadinstitute/picard/pull/1036)  there is need to free up RAM held by `SortingCollection` with saving the ability to add records later.
There is such a functionality in `SortingCollection`: `spillToDisk()` method. But the method is encapsulated as private. To keep this encapsulation (we sure there could be no usage of the method out of the package) yet to provide public interface to this fully functional behavior, we introduce a new util class in the same package.
> SortingCollection: freeUpMemory util method

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
Request is associated with Htsjdk's issue: https://github.com/samtools/htsjdk/issues/833
The problem was that VariantContext.toString() doesn't output anything about filter status. I`ve solved it by changing toString() method in VariantContext class.
> Added information about applied filters in result of VariantContext.toString()

- src/main/java/htsjdk/samtools/SAMRecord.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
Removed MISMATCH_CIGAR_SEQ_LENGTH validation check when no read sequence is defined.
When bwa reports split read alignments it only includes read sequence for the primary alignment record. Omitting the read sequence at the supplementary alignment reduces the file size without loss of information as the read sequence for the supplementary alignment records can be reconstructed from the primary alignment record and the supplementary alignment CIGAR.
> Fix for incorrect MISMATCH_CIGAR_SEQ_LENGTH check

- src/main/java/htsjdk/samtools/seekablestream/SeekableStream.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamGZIPinputStreamIntegrationTest.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamTest.java
Addresses #898 by using a common `SeekableStream` available implementation. This is necessary to fix problems while reading (b)gzip compressed files with a wrapped `SeekableStream` in a `GZIPInputStream`.
> Implement SeekableStream.available

- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/nio/DeleteOnExitPathHook.java
- src/test/java/htsjdk/samtools/util/IoUtilTest.java
After https://github.com/samtools/htsjdk/pull/910, I introduced an crash while deleting on exit a `java.nio.Path`. This was fixed by https://github.com/samtools/htsjdk/pull/1032, but I explore a bit the java base code to check what the `File` version is handling the deletion on exit.
It turns out that it is also using a shutdown hook, but a common one for all the registered files (see [`java.io.DeleteOnExitHook`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/io/DeleteOnExitHook.java)). Here, I mimic that class to register for deletion the `java.nio.Path` in `IOUtils` and run a single shutdown hook for all of them, ignoring any `IOException` or `RuntimeException`. I think that this will be more consistent with the behaviour expected by …
> Add DeleteOnExitPathHook to register java.nio.Path for deletion

- src/main/java/htsjdk/variant/variantcontext/writer/VCFWriter.java
- src/test/java/htsjdk/variant/variantcontext/writer/VCFWriterUnitTest.java
Issue: https://github.com/samtools/htsjdk/issues/1008
This issue is associated with few different errors that occurs when trying to write VCF with empty header. According to an issue, currently there isn't any check in VCFWriter.add that the header has been set. If you try to add a variant with an unset header you get a variety of unhelpful error messages.
So, we've added 
- check for empty header in add() method;
- corresponding test with .vcf and .vcf.gz input files.
> VCFWriter.add() exception when no header has been set

- src/main/java/htsjdk/variant/vcf/VCFCompoundHeaderLine.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderLineUnitTest.java
A header with a incorrect count number can be created but after that is not readable anymore with htsjdk itself. Adding a exception to prevent this from happening.
> Adding check on validator on VCFHeadLineCount

- build.gradle
The motivation for this PR is updating the version of JaCoCo to 0.8.0, which filter out some artifacts generated on the reports and producing the coverage to be reduced (e.g., empty private constructors).
> Set explicitly jacoco version to 0.8.0

- src/main/java/htsjdk/samtools/util/SortingCollection.java
- src/main/java/htsjdk/samtools/util/StringUtil.java
Added debugging messages that estimate the size per record for further tweaking if needed.
Use java 8 parallel sort.
These changes address issues seen in https://broadinstitute.atlassian.net/browse/DSDEGP-2232
> Have SortingCollection check prior to final sort to adjust file buffer size given the amount of memory we have left.

- src/main/java/htsjdk/samtools/util/BlockCompressedFilePointerUtil.java
Make a method in BlockCompressedFilePointerUtil public so that other libraries (Hadoop-BAM, Squark) can use it. Also add an overloaded version for convenience. See #1112
> Make BlockCompressedFilePointerUtil#makeFilePointer public

- src/main/java/htsjdk/samtools/SamInputResource.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
Based on @tfenne 's branch #1118 
includes:
- Test that piping works for both File and Path (using mkfifo and a second thread)
- Fixed .of(Path) to call .of(File) when the input is not a regular file.
- Lots of whitespace changes (sorry)
- Closed readers (in the tests) using try-with-resources
> Fix regression regarding pipeing

- src/main/java/htsjdk/samtools/seekablestream/SeekableBufferedStream.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableBufferedStreamTest.java
This is an optimization to avoid unnecessary seeks (which can be expensive when reading from cloud stores, or Hadoop). See #1112
> Seeks within SeekableBufferedStream's buffer do not need to create a new buffer

- src/main/java/htsjdk/samtools/SamInputResource.java
- According to @droazen: "This operation is expensive over certain NIO… filesystems (eg., takes on the order of seconds over GCS), so forcing it at reader creation time could potentially add hours to the wall-clock time of a task that needed to access many bams over GCS.
It's also not particularly logical to go to the else clause here if the file doesn't exist -- if it's a non-existent GCS file, PathInputResource is better equipped to produce a more relevant error message."
> Remove Files.exist from the .of(Path) method in SamInputResource

- src/main/java/htsjdk/samtools/CRAMFileWriter.java
- src/main/java/htsjdk/samtools/SAMFileWriterImpl.java
- src/main/java/htsjdk/samtools/SAMTextWriter.java
This PR addresses two issues with `SAMFileWriterImpl`:
* When sub-classing, it is difficult to access to some important features unless the class lives in the same pacakge. Concretely, this are the maximum records in RAM and the temporary directory. This PR makes this methods and the getters protected.
* While adding a header to the writer the current implementation generates the text header always, even if it is not used. This is rather inefficient for writers where the header should not be written down for whatever reason. This PR deprecates the abstract method `writeHeader` for a `String`in favor of a new one with a `Supplier` (which defaults in the previous one).
> SAMFileWriterImpl improvements for subclasses

- src/main/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFile.java
* a number of methods that were previously non final when they were
defined in IndexFastaSequenceFile were made final when they moved to
AbstractIndexedFastaSequenceFile
* this was an overlooked API change that causes problems for existing
subclasses of IndexFastaSequenceFile
* removing final from all newly final methods except for isIndexed()
> removing new finals in AbstractIndexedFastaSequenceFile

- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/tribble/AbstractFeatureReader.java
- src/main/java/htsjdk/tribble/TribbleIndexedFeatureReader.java
- src/main/java/htsjdk/tribble/bed/BEDCodec.java
- src/main/java/htsjdk/tribble/index/IndexFactory.java
- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
- src/test/java/htsjdk/tribble/AbstractFeatureReaderTest.java
- src/test/java/htsjdk/tribble/bed/BEDCodecTest.java
- src/test/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
* Move `AbstractFeatureReader.hasBlockCompressedExtension` methods to `IOUtil`
* Move `AbstractFeatureReader.BLOCK_COMPRESSED_EXTENSIONS` field to `IOUtil`
* Deprecate `AbstractFeatureReader` methods/field in favor of the `IOUtil` counterparts
* Change usages of `AbstractFeatureReader` methods/field for the `IOUtil` counterparts
* Add `IOUtil.isBlockCompressed` method to check for a block-compressed file (with or without extension check)
Closes #1130 
Related to https://github.com/broadinstitute/gatk/issues/3792
> Add utilities for check block-compressed files in IOUtils

- src/main/java/htsjdk/samtools/BAMFileWriter.java
- src/test/java/htsjdk/samtools/BAMFileWriterTest.java
Make BAMFileWriter public so that other libraries (Hadoop-BAM, Squark) can use it. See #1112
> Make BAMFileWriter public to expose code to write a BAM header to a stream.

- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
Fix for GATK issue https://github.com/broadinstitute/gatk/issues/3669. Testing the change requires opening a CRAM through a Path that is backed by something that isn't a File. The newly added test, which simulates this condition, fails without this change. Is there a better way to force execution of this code path without adding any additional dependencies ?
> Fix reading a CRAM with an index from a non-File Path.

- build.gradle
* the underlying ngs-java library that supplies SRA support required updating in order to continue connecting to the SRA servers
* fixes SRA tests and restores support
* update ngs-java 1.2.4 -> 2.9.0
> restoring SRA support by updating the backing library

- src/main/java/htsjdk/samtools/fastq/FastqRecord.java
- src/test/java/htsjdk/samtools/fastq/FastqRecordTest.java
The current implementation of `FastqRecord.toString()` is using a FASTQ-formatted String. Usually, the `toString()` method should implement a description of the object that should be useful for the developer, but not for rely on it for usage on other parts of the code (such a writer). Because there is a TODO for changing the method for something more simple, this PR deprecates the current implementation to warn the users to use the `FastqRecord.toFastQString()` method instead, and change the behaviour in a future release.
In addition, this PR includes changes in the javadoc to point out where a null value could be returned and adds tests for a "null" record.
> Deprecate FastqRecord.toString to warn users for a future change in behaviour

- src/main/java/htsjdk/samtools/SamReader.java
Currently, `SamReader` cannot be implemented for other "types" of data, unless the `getType`method returns any of the supported type implementations (SAM/BAM/CRAM/SRA). Other abstractions are impossible to implement unless some of the method of `Type` are implemented, and this is not possible because they aren't public.
> Make public SamReader.Type methods to allow other implementations

- src/main/java/htsjdk/tribble/index/IndexFactory.java
- src/test/java/htsjdk/tribble/index/IndexTest.java
Make it possible to load a tribble index from a stream, not just a file. This is needed for #1112.
The change is covered by existing tests.
> Load tribble index from a stream.

- src/main/java/htsjdk/variant/utils/VCFHeaderReader.java
- src/test/java/htsjdk/variant/utils/VCFHeaderReaderTest.java
- src/test/resources/htsjdk/variant/corrupt_file_that_starts_with_#.vcf
* adding a new class VCFHeaderReader to read a VCFHeader from a stream without knowing in advance if the file is VCF or BCF, or compressed or not.
resolving a few minor additional comments that I had on https://github.com/samtools/htsjdk/pull/1122
> Add new class VCFHeaderReader

- src/main/java/htsjdk/samtools/CRAMFileReader.java
- src/test/java/htsjdk/samtools/CRAMFileCRAIIndexTest.java
Expose a method to create a CRAMIntervalIterator to get reads overlapping intervals, much like BAMFileReader#createIndexIterator. See #1112
> Public method for CRAMIntervalIterator for overlapping intervals

- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/test/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
- src/test/java/htsjdk/samtools/SAMIntegerTagTest.java
More `java.nio.Path` support for `SAMFileWriterFactory` methods, in this case for supporting referenceFile paths for CRAM.
> Add SAMFileWriterFactory methods for java.nio.Path referenceFile

- src/main/java/htsjdk/samtools/reference/AbstractFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/FastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/FastaSequenceIndex.java
- src/main/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java
- src/main/java/htsjdk/samtools/seekablestream/ReadableSeekableStreamByteChannel.java
- src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java
- src/test/java/htsjdk/samtools/reference/FastaSequenceFileTest.java
- src/test/java/htsjdk/samtools/reference/FastaSequenceIndexTest.java
Add a method to open a reference sequence by passing an input stream to a FASTA (and to its index). This would allow reading from Hadoop filesystems without having to use the file NIO library. See #1112
> Use ReferenceSequenceFileFactory with streams

- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/test/java/htsjdk/samtools/CRAMComplianceTest.java
- src/test/java/htsjdk/samtools/SAMFileWriterFactoryTest.java
* deprecating overloads of SAMFileWriterFactory.makeCRAMWriter that took a mix of Path and File as inputs
these were needed when we supported Path for the CRAM but not the reference
* removing one overload that seems redundant and hasn't been in any htsjdk release yet
> deprecating overloads makeCRAMWriter with mixed Path/File

- src/main/java/htsjdk/samtools/CachingBAMFileIndex.java
- src/test/java/htsjdk/samtools/CachingBAMFileIndexTest.java
* fixing several related bugs in CachingBAMFileIndex
* fixed an issue where cache hits in contigs with indexes higher than 127 could result in null values being returned incorrectly
* fixed a memory leak where we never released contigs with indexes 0 -> 127 from the cache
* fixes #1127
The underlying issue was confusion over how WeakHashMap interacts with Integer.
> Fixes for CachingBAMFileIndex

- src/main/java/htsjdk/samtools/SAMRecord.java
* previously it only said if it was mapped or not, now it includes the position if it's mapped
> adding position to SAMRecord.toString()

- src/main/java/htsjdk/variant/vcf/VCFHeader.java
Fix a simple copy-paste error in documentation that clearly doesn't say what the method is doing.
@lbergelson should I do more?
> fix an copy-paste error in VCFHeader

- src/main/java/htsjdk/samtools/cram/build/CramContainerIterator.java
- src/test/java/htsjdk/samtools/CramContainerHeaderIteratorTest.java
Fixes a bug from #1129, and added a test to check for the error (which fails without the fix).
> Fix CRAM container offset calculation

- src/main/java/htsjdk/samtools/seekablestream/SeekableBufferedStream.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableBufferedStreamTest.java
Fix a bug where invalid bytes in BufferedInputStream's buffer were being accessed.
Only bytes up to BufferedInputStream's `count` field in its internal buffer
are valid; this change ensures accesses are limited to this range.
The new test ensures that the internal buffer is not completely filled, and without the fix it fails.
The problem has been present for a long time, but possibly has only been exposed since #1121 in some circumstances. I encountered the bug while running the GATK test suite with Disq (which uses SeekableBufferedStream extensively) - see https://github.com/broadinstitute/gatk/pull/5138.
> Invalid buffer access in SeekableBufferedStream

- src/main/java/htsjdk/samtools/BAMFileWriter.java
- src/main/java/htsjdk/samtools/BamFileIoUtils.java
- src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/main/java/htsjdk/samtools/util/BlockCompressedOutputStream.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/tribble/index/tabix/TabixIndex.java
- src/main/java/htsjdk/variant/variantcontext/writer/BCF2Writer.java
- src/main/java/htsjdk/variant/variantcontext/writer/IndexingVariantContextWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/VCFWriter.java
- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/test/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
VCFWriter accepts Path, and associated changes necessary for this to happen.
I also added a Path test to VariantContextWriterBuilderUnitTest (using JimFS).
The benefit of this change is that a Path can point to files on the cloud (e.g. via [GCloud's NIO Filesystem Provider for Google Cloud Storage](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-contrib/google-cloud-nio)). So htsjdk users can now easily write VCF files on the cloud.
For example, with this change, I was able to change GATK to write VCF output
to the cloud:
`$ ./gatk GatherVcfsCloud -I ./sample.vcf -O gs://jps_bucket/out.vcf`
> VCFWriter accepts Path

- src/main/java/htsjdk/variant/vcf/AbstractVCFCodec.java
This change adds getters for the version and header fields in AbstractVCFCodec. Access to these fields is needed by Disq, see https://github.com/broadinstitute/gatk/pull/5138.
> Expose VCFCodec version and header fields.

- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
* VariantContextWriterBuilder.build() was replaced by a varargs version of itself in a previous commit
While this is a source compatible change it's not binary compatible and since it's a commonly used function it breaks a lot of libaries
* add a parameterless build() which just calls through to the varargs version with an empty array
> restore no-args VariantContextWriterBuilder.build()

- src/main/java/htsjdk/samtools/BinaryBAMIndexWriter.java
- src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
- src/main/java/htsjdk/samtools/SamFiles.java
- src/main/java/htsjdk/samtools/SamInputResource.java
- src/main/java/htsjdk/samtools/cram/ref/ReferenceSource.java
- src/main/java/htsjdk/samtools/reference/AbstractFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/FastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/FastaSequenceIndex.java
- src/main/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java
- src/main/java/htsjdk/samtools/util/BinaryCodec.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/IntervalList.java
- src/main/java/htsjdk/samtools/util/Md5CalculatingOutputStream.java
- src/main/java/htsjdk/tribble/index/AbstractIndex.java
- src/main/java/htsjdk/tribble/index/DynamicIndexCreator.java
- src/main/java/htsjdk/tribble/index/Index.java
- src/main/java/htsjdk/tribble/index/interval/IntervalIndexCreator.java
- src/main/java/htsjdk/tribble/index/linear/LinearIndex.java
- src/main/java/htsjdk/tribble/index/linear/LinearIndexCreator.java
- src/test/java/htsjdk/samtools/SamFilesTest.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
this method converts a `File` to a `Path`, but passes a null through unchanged instead of crashing with an NPE
it is useful when adapting existing code that takes `File`s into code that takes `Path`s and should help avoid introducing new NPEs when converting code
updated existing uses of `file.toPath()` to `IOUtil.toPath(file)`
- [ x ] Code compiles correctly
- [ X ] New tests covering changes and new functionality
- [ x ] All tests passing
> adding new method IOUtil.toPath(File)

- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/test/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
@droazen I was readying the htjsdk release when I decided to run an automatic binary compatibility checker tool on it since we'd already found one issue before.  Of course it found another issue.  So here's a patch for it.  
I refactored the relevant test because it was so awful...
> adding back deleted method and refactoring test

- src/main/java/htsjdk/samtools/seekablestream/SeekableHTTPStream.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableBufferedStreamTest.java
* a bug in `SeekableHttpStream` could cause clients to go into an infinite loop because read would return 0 when trying to read one byte past the end of the file
* fixes #1181
> fixing bug in SeekableHttpStream.read

- src/main/java/htsjdk/samtools/util/AbstractProgressLogger.java
- src/main/java/htsjdk/samtools/util/ProgressLoggerInterface.java
I have two uses for this method:
1. I may create a `ProgressLogger` earlier, but want to set the `startTime` so it is right before the logger is being used.  Yes, I can create the `ProgressLogger` at the last minute.
2. I may want to reuse a progress logger.
> Add a reset() method to ProgressLoggerInterface.

- src/main/java/htsjdk/samtools/util/BinaryCodec.java
- src/test/java/htsjdk/samtools/util/BinaryCodecTest.java
I ran into this bug when writing an empty string as the last element into a byte buffer (ex `binaryCodec.writeString("", true, false)`) and then trying to read it back in (ex. `binaryCodec.readLengthAndString(false)`).  The main issue is that `InputStream.read` will return `-1` even if the maximum number of bytes to read is zero (i.e. `InputStream.read(buffer, 0, 0)` will return `-1`).
I made a commit with a test to show the bug and a commit to fix it.
> BinaryCodec.readBytesOrFewer fails if no data is requested AND no date is available in the underlying input stream

- src/main/java/htsjdk/variant/variantcontext/Allele.java
- src/main/java/htsjdk/variant/variantcontext/StructuralVariantType.java
__Simple__ alt allele constants for SV.
Two implementations, not sure which one is preferred.
> Simple sv alt allele

- src/main/java/htsjdk/samtools/CRAMIterator.java
- src/test/java/htsjdk/samtools/CRAMEdgeCasesTest.java
- src/test/java/htsjdk/samtools/CRAMFileReaderTest.java
- src/test/java/htsjdk/samtools/CRAMTestUtils.java
* fixing a bug in CRAMIterator which previously threw if next() was called without first calling hasNext()
* adding CRAMTestUtils and extracting a method to it from CramEdgeCasesTest
> fix CRAMIterator when next() is called without hasNext()

- src/main/java/htsjdk/variant/vcf/VCFStandardHeaderLines.java
@lbergelson 
Motivated by https://github.com/broadinstitute/gatk/pull/5318
I am happy to change the language as folks see fit.
> Add the PS FORMAT VCF standard header field

- src/main/java/htsjdk/samtools/AbstractSAMHeaderRecord.java
- src/main/java/htsjdk/samtools/SAMSequenceDictionary.java
- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
- src/main/java/htsjdk/samtools/cram/structure/EncodingParams.java
- src/test/java/htsjdk/samtools/SAMSequenceDictionaryTest.java
Removes JAXB annotations.   These were not used anywhere except 1 unit test which was also removed.
4 unit tests are failing,  but the same tests failed before the changes.   See screenshot.
> Remove JAXB.  See issue #1204

- src/main/java/htsjdk/samtools/AbstractSAMHeaderRecord.java
- src/main/java/htsjdk/samtools/SAMFileHeader.java
- src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/test/java/htsjdk/samtools/SAMFileHeaderTest.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
Request is associated with Picard's issue https://github.com/broadinstitute/picard/issues/796
As said in that issue MergeSamFiles can't accept SAM-file with SO:UNKNOWN. That behavior is expected, because tag's value is in improper case(in accordance with SAM-format specification, SO value must be in lowercase). We've found that wrong tag case also provides an exception.
The idea of implementation is that htsjdk must check case of header's tags and values. If tag/value itself is valid, but in improper case(e.g. lowercase instead of uppercase) - it should be converted to proper case before sending the result to output(without changing the source file). Also, there must be a message if that conversion was made.
> MergeSamFiles accept SO:UNKNOWN

- src/main/java/htsjdk/samtools/cram/build/CompressionHeaderFactory.java
- src/main/java/htsjdk/samtools/cram/encoding/EncodingFactory.java
- src/main/java/htsjdk/samtools/cram/encoding/ExternalIntegerCodec.java
- src/main/java/htsjdk/samtools/cram/encoding/huffman/codec/CanonicalHuffmanByteEncoding.java
- src/main/java/htsjdk/samtools/cram/encoding/huffman/codec/CanonicalHuffmanIntegerEncoding.java
- src/main/java/htsjdk/samtools/cram/io/CramIntArray.java
- src/main/java/htsjdk/samtools/cram/io/ITF8.java
- src/main/java/htsjdk/samtools/cram/io/LTF8.java
- src/main/java/htsjdk/samtools/cram/structure/EncodingID.java
- src/test/java/htsjdk/samtools/cram/encoding/BetaIntegerCodecTest.java
- src/test/java/htsjdk/samtools/cram/encoding/ExternalByteArrayCodecTest.java
- src/test/java/htsjdk/samtools/cram/encoding/ExternalByteCodecTest.java
- src/test/java/htsjdk/samtools/cram/encoding/ExternalIntegerCodecTest.java
- src/test/java/htsjdk/samtools/cram/io/CramIntArrayTest.java
- src/test/java/htsjdk/samtools/cram/io/CramIntTest.java
- src/test/java/htsjdk/samtools/cram/io/IOTestCases.java
- src/test/java/htsjdk/samtools/cram/io/ITF8Test.java
- src/test/java/htsjdk/samtools/cram/io/LTF8Test.java
External*CodecTests
ByteArrayLenCodec test
ITF8 and LTF8 updates
> More CRAM Encoding tests + updates

- src/main/java/htsjdk/samtools/cram/encoding/ByteArrayLenEncoding.java
- src/main/java/htsjdk/samtools/cram/structure/Block.java
- src/main/java/htsjdk/samtools/cram/structure/BlockCompressionMethod.java
- src/main/java/htsjdk/samtools/cram/structure/BlockContentType.java
- src/main/java/htsjdk/samtools/cram/structure/CompressionHeader.java
- src/main/java/htsjdk/samtools/cram/structure/EncodingID.java
Using `ordinal()` is brittle because code will break mysteriously if the orders of enums ever change.  These Encoding, Block Compression Method, and BlockContentType IDs are mandated by the spec.
> CRAM: Be explicit about spec IDs instead of using ordinal()

- src/main/java/htsjdk/variant/vcf/VCFSimpleHeaderLine.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
Setting a getter for accessing to values like "Description" 
- [] Code compiles correctly
- [] New tests covering changes and new functionality
- [] All tests passing
- [] Extended the README / documentation, if necessary
- [] Is not backward compatible (breaks binary or source compatibility)
> Getter for generic fields in VCFSimpleHeaderLine

- src/main/java/htsjdk/samtools/SAMFileHeader.java
- src/test/java/htsjdk/samtools/ValidateSamFileTest.java
- src/test/resources/htsjdk/samtools/SamFileHeaderMergerTest/case1/expected_output.sam
- src/test/resources/htsjdk/samtools/SamFileHeaderMergerTest/case2/chr11sub_file1.sam
- src/test/resources/htsjdk/samtools/SamFileHeaderMergerTest/case2/expected_output.sam
- src/test/resources/htsjdk/samtools/roundtrip.sam
* Htsjdk has techinically been producing Sam version 1.6 since support for long cigars was added.
* Updating that list of acceptable versions to include 1.6 and setting the header version of new bams to 1.6
> Changing htsjdk to produce sam version 1.6

- README.md
* The existing examples of how to run single tests are broken, updating
them with working examples.
* Closes #984
> Update the README with working test examples

- src/main/java/htsjdk/samtools/LinearIndex.java
- src/main/java/htsjdk/samtools/cram/common/Version.java
- src/main/java/htsjdk/samtools/cram/encoding/huffman/codec/CanonicalHuffmanIntegerEncoding.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/BaseQualityScore.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/Bases.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/Deletion.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/HardClip.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/InsertBase.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/Insertion.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/Padding.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/ReadBase.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/RefSkip.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/Scores.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/SoftClip.java
- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/Substitution.java
- src/main/java/htsjdk/samtools/cram/structure/AlignmentSpan.java
- src/main/java/htsjdk/samtools/cram/structure/CramHeader.java
- src/main/java/htsjdk/samtools/cram/structure/ReadTag.java
- src/main/java/htsjdk/tribble/index/Block.java
- src/main/java/htsjdk/tribble/index/linear/LinearIndex.java
- src/test/java/htsjdk/samtools/cram/encoding/ReadFeaturesTest.java
`equals()` without `hashCode()` is bad news.  Also, some `equals()` have problems too.
> Add hashCode() to classes with equals() and clean up equals()

- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
- src/test/java/htsjdk/samtools/SAMSequenceRecordTest.java
* The @SQ DS header field was added to the 1.6 bam spec, this adds a getter and setter for it.
* We do not correctly support UTF-8 characters in description due to https://github.com/samtools/htsjdk/issues/1202
> Adding first class Description field to SAMSequenceRecord

- src/main/java/htsjdk/samtools/SAMSequenceDictionary.java
- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
There were some things that could be cleaned up after removing JAXB support for SAMSequenceRecord.
> Removing cruft leftover from JAXB

- src/main/java/htsjdk/samtools/BAMRecord.java
- src/main/java/htsjdk/samtools/SAMBinaryTagAndUnsignedArrayValue.java
- src/main/java/htsjdk/samtools/SAMBinaryTagAndValue.java
- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/main/java/htsjdk/samtools/SAMTag.java
- src/main/java/htsjdk/samtools/SAMTagUtil.java
- src/main/java/htsjdk/samtools/SAMTextWriter.java
- src/main/java/htsjdk/samtools/SAMUtils.java
- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/main/java/htsjdk/samtools/cram/digest/ContentDigests.java
- src/main/java/htsjdk/samtools/cram/encoding/BitCodec.java
- src/main/java/htsjdk/samtools/cram/encoding/huffman/codec/CanonicalHuffmanByteEncoding.java
- src/main/java/htsjdk/samtools/cram/structure/ReadTag.java
- src/main/java/htsjdk/samtools/cram/structure/Slice.java
- src/main/java/htsjdk/samtools/cram/structure/SliceIO.java
- src/main/java/htsjdk/samtools/sra/SRALazyRecord.java
- src/test/java/htsjdk/samtools/SAMBinaryTagAndValueUnitTest.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
- src/test/java/htsjdk/samtools/SAMUtilsTest.java
This PR does several things:
1.  It updates the list of tags in SAMTags and SAMTagUtils to include all the tags currently in the spec
2.  It deprecates tags that are listed as "for backwards compatibility only", this should hopefully signal to downstream users that they should no longer be generating these tags but may still support them for backwards compatibility.  
3.  It makes all methods in SAMTagUtil static and makes the class final.  This will break any existing subclasses.  Searching github and google for "extends SAMTagUtil" results in 0 results so it's unlikely that anyone will be impacted negatively by this. 
4.  Refactoring to make use of newly static SAMTagUtil methods.
> Updating SAMTag and SAMTagUtils

- src/main/java/htsjdk/samtools/SAMBinaryTagAndUnsignedArrayValue.java
- src/main/java/htsjdk/samtools/SAMBinaryTagAndValue.java
- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/SAMTag.java
- src/main/java/htsjdk/samtools/SAMTagUtil.java
- src/main/java/htsjdk/samtools/SAMTextWriter.java
- src/main/java/htsjdk/samtools/cram/digest/ContentDigests.java
- src/main/java/htsjdk/samtools/cram/structure/ReadTag.java
- src/main/java/htsjdk/samtools/cram/structure/Slice.java
- src/main/java/htsjdk/samtools/cram/structure/SliceIO.java
- src/main/java/htsjdk/samtools/sra/SRALazyRecord.java
- src/test/java/htsjdk/samtools/SAMBinaryTagAndValueUnitTest.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
* reverting the change from constants to static variables, deprecating
the constants instead
> more changes to SAMTagUtil

- src/main/java/htsjdk/samtools/cram/encoding/core/BetaIntegerEncoding.java
- src/test/java/htsjdk/samtools/cram/encoding/core/BetaIntegerCodecTest.java
- src/test/java/htsjdk/samtools/cram/encoding/core/BetaIntegerEncodingTest.java
I recently added a check to protect against creating Beta Encodings with bitLength 0.  This was mistaken, and causes problems reading CRAMs with this parameter - such as those created by htslib for zero-length or constant data series.
This PR reverts that check.
> Relax Beta Encoding requirement to allow 0 bits

- src/main/java/htsjdk/variant/variantcontext/Genotype.java
- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
These are micro optimizations that add up to a pretty small change in the HaplotypeCaller (Exome +GVCF) profile when they are implemented. Here are some profiling snippets:
Before: 
After:
Then some runtime examples on my laptop just chromosome 15 of the same bam:
Before:  `4m26s, 4m16s, 4m18s, 4m15s, 4m28s`
After:     `4m04s, 4m09s, 4m15s, 4m11s, 4m07`
> Replaced several for-each loops in VariantContext.Make() based on HaplotypeCaller profiling

- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
- src/test/java/htsjdk/samtools/SAMSequenceRecordTest.java
- src/test/java/htsjdk/samtools/SequenceNameTruncationAndValidationTest.java
https://github.com/samtools/hts-specs/pull/333
> - implementing the spec change in 

- src/main/java/htsjdk/samtools/CRAMIterator.java
Add a few finals, pre request during review of https://github.com/samtools/htsjdk/pull/1091.
> Add finals for issues raised during review of PR 1091.

- src/main/java/htsjdk/samtools/util/HttpUtils.java
- src/test/java/htsjdk/samtools/util/HttpUtilsTest.java
Minor change: in httpUtils `getHeaderField` I set the Http-method to '**HEAD**'  instead of '**GET**' in order to only fetch the header fields.
I also added a test file for HttpUtils.
> HttpUtils: set Method to HEAD for HttpUtils.getHeaders

- src/main/java/htsjdk/samtools/SamStreams.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/variant/utils/VCFHeaderReader.java
- src/main/java/htsjdk/variant/vcf/VCFIteratorBuilder.java
- src/test/java/htsjdk/samtools/SamStreamsTest.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
resolving some nitpicks left over from pr #1245
> resolving some nitpicks from pr #1245

- src/main/java/htsjdk/samtools/apps/TimeChannel.java
- src/main/java/htsjdk/samtools/apps/TimeRandomAccessFile.java
* deprecated TimeChannel and TimeRandomAccesFile
* these are two tools which were probably used for testing at some point but should not be part of the htsjdk distribution
> Deprecated htsjdk.samtools.apps package.

- src/main/java/htsjdk/samtools/filter/IntervalKeepPairFilter.java
- src/test/java/htsjdk/samtools/filter/IntervalKeepPairFilterTest.java
When a BAM contains both single ended and paired ended reads this filter throws an exception (`java.lang.IllegalStateException: Inappropriate call if not paired read`). Since the filter is only meant to keep paired reads it now also filters out single ended reads and doesn't throw an exception.
> Makes IntervalKeepPairFilter filter out single ended reads

- src/test/java/htsjdk/samtools/filter/IntervalKeepPairFilterTest.java
@meganshand I've responded to my own nitpick, could you review?
> Fix nitpick in IntervalKeepPairFilterTest

- src/main/java/htsjdk/samtools/seekablestream/SeekableStream.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamTest.java
For files that are larger than 2GB (e.g. an uncompressed FASTA) it is possible that
`length - position` in `SeekableStream#available()` overflows an int, resulting in a negative value being returned.
This fixes the problem described here: https://github.com/broadinstitute/gatk/issues/5547
> Fix to ensure that SeekableStream#available() never returns a negative value

- src/main/java/htsjdk/tribble/readers/TabixReader.java
- src/test/java/htsjdk/tribble/readers/TabixReaderTest.java
Follow up to #908.
Move the bad coordinates check to the root method, `public Iterator query(final String reg)`. If this public method is used by an application, the bad coordinates will return an `EOF_ITERATOR;`
> Move bad coordinates check

- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/main/java/htsjdk/samtools/cram/CRAIEntry.java
- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java
- src/main/java/htsjdk/samtools/util/TestUtil.java
- src/main/java/htsjdk/samtools/util/ftp/FTPClient.java
- src/main/java/htsjdk/tribble/index/interval/IntervalIndexCreator.java
- src/main/java/htsjdk/tribble/index/linear/LinearIndexCreator.java
- src/main/java/htsjdk/tribble/index/tabix/TabixFormat.java
- src/main/java/htsjdk/tribble/util/ParsingUtils.java
- src/test/java/htsjdk/tribble/TestUtils.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
Fixes some of the issues reported in #1267
> Fix fields that should be final, as reported by SpotBugs

- build.gradle
- src/test/java/htsjdk/samtools/util/HttpUtilsTest.java
* HttpUtilsTest is flakey because it connects to remote web servers.
Moved it to the testExternalAPIs test task
* changed a broken link so that the tests pass again
> moving HttpUtilsTest to externalApi test task

- build.gradle
- src/main/java/htsjdk/samtools/SAMSequenceDictionaryCodec.java
- src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/main/java/htsjdk/samtools/reference/FastaReferenceWriter.java
- src/main/java/htsjdk/samtools/reference/FastaReferenceWriterBuilder.java
- src/test/java/htsjdk/samtools/util/HttpUtilsTest.java
* make sure the OutputStreams are always buffered
* change close behavior to be more likely to close all output streams in
the event of an early shutdown
* loosen restriction from BufferedWriter to Writer in
SAMSequenceDictionaryCodec and SAMTextHeaderCodec
> Changes to FastaReferenceWriter

- src/main/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
Minor cleanup/removal of unused of code I noticed during a code review.
> Remove redundant and unused BAM_FLAGS from CRAM code.

- src/main/java/htsjdk/samtools/CRAMContainerStreamWriter.java
- src/main/java/htsjdk/samtools/cram/build/CramNormalizer.java
- src/main/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
- src/main/java/htsjdk/samtools/cram/structure/Slice.java
- src/test/java/htsjdk/samtools/cram/build/ContainerFactoryTest.java
- src/test/java/htsjdk/samtools/cram/build/ContainerParserTest.java
- src/test/java/htsjdk/samtools/cram/structure/CramCompressionRecordTest.java
- src/test/java/htsjdk/samtools/cram/structure/SliceTests.java
isPlaced() was not checking for the APDelta flag, thus inappropriately marking some records as unplaced.
Error introduced on 1/30 with #1266
> update CramCompressionRecord.isPlaced() to make it APDelta-aware

- README.md
The readme had inaccurate information about which versions we support.
> Update java version information in the README

- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
Add Path overloads of some functions in IOUtil that were missing them.
Fixes #1294
> adding new overloads to IOUtils with Path for some file only methods

- build.gradle
Htsjdk is no longer a subproject of the Picard team and it's published pom should reflect that it has it's own team of developers.
> Changing the team name/url in the maven pom

- src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/util/GZIIndex.java
- src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java
- src/test/java/htsjdk/samtools/util/GZIIndexTest.java
This enables fasta.gz files to be loaded from streams (not just path objects), which is needed for https://github.com/disq-bio/disq/issues/75.
See original bug report in https://github.com/broadinstitute/gatk/issues/5547
> Load BlockCompressedIndexedFastaSequenceFile and GZIIndex from streams

- src/main/java/htsjdk/variant/variantcontext/Allele.java
- src/main/java/htsjdk/variant/vcf/AbstractVCFCodec.java
- src/test/java/htsjdk/variant/variantcontext/AlleleUnitTest.java
This replaces https://github.com/samtools/htsjdk/pull/1264 and responds to my own comments.
> remove caching of alleles in AbstractVCFCodec

- src/main/java/htsjdk/samtools/CRAMIterator.java
- src/main/java/htsjdk/variant/utils/SAMSequenceDictionaryExtractor.java
Slightly more idiomatic CRAM sequence dictionary extractor. Rather than introduce a new method and fake reference in CRAMIterator, this retrieves the CRAM header and sequence dictionary using existing code that doesn't require a reference.
> Simplify CRAM sequence dictionary extractor to not require a fake reference.

- src/main/java/htsjdk/samtools/cram/encoding/readfeatures/Substitution.java
- src/main/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
- src/main/java/htsjdk/samtools/reference/FastaSequenceIndex.java
- src/main/java/htsjdk/samtools/util/AsyncBlockCompressedInputStream.java
- src/main/java/htsjdk/samtools/util/CigarUtil.java
- src/main/java/htsjdk/tribble/readers/PositionalBufferedStream.java
- src/main/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
- src/test/java/htsjdk/samtools/cram/encoding/ReadFeaturesTest.java
- src/test/java/htsjdk/samtools/cram/structure/CramCompressionRecordTest.java
> A few fixes for issues found by spotbugs

- src/main/java/htsjdk/samtools/CRAMContainerStreamWriter.java
- src/main/java/htsjdk/samtools/cram/build/ContainerParser.java
- src/main/java/htsjdk/samtools/cram/build/CramNormalizer.java
- src/main/java/htsjdk/samtools/cram/encoding/reader/CramRecordReader.java
- src/main/java/htsjdk/samtools/cram/encoding/reader/MultiRefSliceAlignmentSpanReader.java
- src/main/java/htsjdk/samtools/cram/encoding/writer/CramRecordWriter.java
- src/main/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
- src/main/java/htsjdk/samtools/cram/structure/Slice.java
- src/test/java/htsjdk/samtools/CRAMBAIIndexerTest.java
- src/test/java/htsjdk/samtools/cram/encoding/CramRecordTestHelper.java
- src/test/java/htsjdk/samtools/cram/encoding/CramRecordWriterReaderTest.java
- src/test/java/htsjdk/samtools/cram/encoding/MultiRefSliceAlignmentSpanReaderTest.java
- src/test/java/htsjdk/samtools/cram/structure/CramCompressionRecordTest.java
- src/test/java/htsjdk/samtools/cram/structure/SliceTests.java
Use alignmentStart as the sole source of truth, avoiding messy APDelta logic for isPlaced() and elsewhere.
Largely a reversion of and better solution to #1284
> CRAM: Only calculate alignmentDelta as needed for records

- src/main/java/htsjdk/samtools/CRAMFileReader.java
- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/main/java/htsjdk/samtools/cram/ref/ReferenceSource.java
- src/main/java/htsjdk/samtools/reference/FastaReferenceWriter.java
- src/main/java/htsjdk/samtools/reference/FastaReferenceWriterBuilder.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/SequenceUtil.java
- src/main/java/htsjdk/samtools/util/TestUtil.java
- src/test/java/htsjdk/samtools/CRAMFileWriterTest.java
- src/test/java/htsjdk/samtools/SAMReadGroupRecordTest.java
- src/test/java/htsjdk/samtools/SAMRecordSetBuilderTest.java
- src/test/java/htsjdk/samtools/SamStreamsTest.java
- src/test/java/htsjdk/samtools/reference/FastaReferenceWriterTest.java
In order to test cram files we need a way to write a reference that agrees with the samDictionary that the SAMRecordSetBuilder has in mind. By default it is quite large, and so this enables us to generate a random one (deterministic) on the fly.
> Yf add get reference to sam set builder

- src/main/java/htsjdk/samtools/util/IntervalList.java
- src/main/java/htsjdk/samtools/util/IntervalTree.java
- src/main/java/htsjdk/samtools/util/OverlapDetector.java
- src/test/java/htsjdk/samtools/util/IntervalTreeTest.java
- src/test/java/htsjdk/samtools/util/OverlapDetectorTest.java
Two separate changes which should reduce the in-memory size of IntervalList and OverlapDetector.
1: Cache the last seen contig name when loading IntervalLists and reuse the same String to avoid keeping many duplicate copies of "chr1" in memory. This should have very minor overhead since interval files are sorted it should be about as effective as a more complicated caching scheme.
2.  Use SingletonSets as the leaf objects in OverlapDetector when constructing it.  These are substantially smaller than HashSets of the same size.  Change to HashSet only when we find 2 or more identically positioned elements.  This will have a minor performance cost while constructing the OverlapDetector but should result in dramatically decreased size in memory.
> making changes to reduce size of giant interval lists

- src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java
- src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java
* There was a bug that prevented loading an indexed bgzip fasta file if the index location was specified but wasn't next to the fasta in the file system.
* Fixes #1290
> Fix bug when loading indexed bgzip fasta file.

- src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
- src/test/java/htsjdk/samtools/SeekableByteChannelFromBuffer.java
- src/test/java/htsjdk/samtools/util/BlockCompressedTerminatorTest.java
- src/test/java/htsjdk/testutil/streams/OneByteAtATimeChannel.java
- src/test/java/htsjdk/testutil/streams/SeekableByteChannelFromBuffer.java
* Fixing a bug in BlockCompressedInputStream.checkTermination()
The internal method readFully would throw in cases where less bytes were read than were available in the stream.
We haven't observed this in practice but it's a valid behavior of SeekableByteChannel.read() so we should honor it.
* Fixes #1251
> Fix bug in BlockCompressedInputStream.checkTermination()

- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
* A trivial optimization to use a singletonList instead of an ArrayList in SamRecordSet builder broke downstream tests because SamFileHeader.setReadGroups explicitly doesn't copy the list.
* Tests downstream expect the list to be mutable.
* Fixes https://github.com/samtools/htsjdk/issues/1316
> Revert singletonList optimization in SamRecordSetBuilder

- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/TestUtil.java
* I deprecated this method since it's been replaced.
> Deprecate TestUtil.deleteRecursively

- src/main/java/htsjdk/samtools/util/IntervalList.java
- src/test/java/htsjdk/samtools/util/IntervalListTest.java
* Fixing a bug in IntervalList.merge() that caused it to break when merging 0 length intervals
* Improving tests for merge
* The bug was introduced in #1265 and hasn't been in any release
> Fixing zero-length interval bug in IntervalList.merge

- src/main/java/htsjdk/samtools/util/IntervalList.java
* Adding back an accidentally removed an overload of IntervalList.getUniqueIntervals().
* This fixes a compatibility problem revealed in the pre-release checks.
> Adding back a removed method

- src/main/java/htsjdk/samtools/cram/encoding/reader/CramRecordReader.java
- src/main/java/htsjdk/samtools/cram/encoding/writer/CramRecordWriter.java
- src/main/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
- src/main/java/htsjdk/samtools/cram/structure/DataSeries.java
- src/test/java/htsjdk/samtools/cram/encoding/external/ExternalCodecEquivalenceTest.java
- src/test/java/htsjdk/samtools/cram/io/IOTestCases.java
- src/test/java/htsjdk/samtools/cram/io/ITF8Test.java
- src/test/java/htsjdk/samtools/cram/io/LTF8Test.java
Also add a test demonstrating that the old byte-based code did not cause problems because byte and int codecs are identical for the full range of the fields
> CRAM: correct CT and MF encoding datatypes from byte to int

- build.gradle
* Fix the signing task configuration in build.gradle so that releases are signed.
I had to do this for the 2.19.0 release.
> Fix signing task in build.gradle

- src/test/java/htsjdk/TestDataProviders.java
- src/test/java/htsjdk/samtools/CSIIndexTest.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
- src/test/java/htsjdk/samtools/reference/SamLocusAndReferenceIteratorTest.java
- src/test/java/htsjdk/samtools/util/BlockCompressedOutputStreamTest.java
- src/test/java/htsjdk/samtools/util/CigarElementUnitTest.java
- src/test/java/htsjdk/tribble/index/interval/IntervalTreeTest.java
- src/test/java/htsjdk/variant/bcf2/BCF2EncoderDecoderUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFCompoundHeaderLineUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
copy of https://github.com/samtools/htsjdk/pull/1277 with a fix for the dataprovider meta test
Addresses #1267 for the tests (except for some valid violation that will be excluded in another PR).
> Spotbugs fix tests

- .travis.yml
- build.gradle
- gradle/spotbugs-exclude.xml
- src/main/java/htsjdk/samtools/MergingSamRecordIterator.java
- src/main/java/htsjdk/samtools/TextualBAMIndexWriter.java
- src/main/java/htsjdk/samtools/cram/compression/rans/E14.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/main/java/htsjdk/samtools/util/SortingCollection.java
- src/main/java/htsjdk/tribble/readers/AsciiLineReaderIterator.java
Rebase of https://github.com/samtools/htsjdk/pull/1303
> Spotbugs remaining fixes

- src/main/java/htsjdk/samtools/cram/structure/Container.java
- src/main/java/htsjdk/samtools/cram/structure/ContainerIO.java
- src/test/java/htsjdk/samtools/cram/structure/ContainerTest.java
Problem:
calculateSliceOffsetsAndSizes() was calculating Slice.size incorrectly.
Impact: 
Slices created via ContainerIO.readContainer() would produce incorrect sliceByteSize values for their CRAI entries.
> Test ContainerIO.calculateSliceOffsetsAndSizes() and fix the slice size calculation

- src/main/java/htsjdk/samtools/util/SortingCollection.java
A utility like SortingCollection should not fill log output with unnecessary output by default.  Caller can enable debug output if they want to see these messages.  We sometimes create a lot of SortingCollections, and these messages become annoying.
> SortingCollection logging should only be if DEBUG

- src/main/java/htsjdk/samtools/BAMIndexMetaData.java
- src/main/java/htsjdk/samtools/CRAMBAIIndexer.java
- src/main/java/htsjdk/samtools/CRAMCRAIIndexer.java
- src/main/java/htsjdk/samtools/CRAMContainerStreamWriter.java
- src/main/java/htsjdk/samtools/CRAMFileReader.java
- src/main/java/htsjdk/samtools/CRAMIterator.java
- src/main/java/htsjdk/samtools/cram/CRAIEntry.java
- src/main/java/htsjdk/samtools/cram/CRAIIndex.java
- src/main/java/htsjdk/samtools/cram/build/ContainerFactory.java
- src/main/java/htsjdk/samtools/cram/build/ContainerParser.java
- src/main/java/htsjdk/samtools/cram/build/CramContainerHeaderIterator.java
- src/main/java/htsjdk/samtools/cram/build/CramContainerIterator.java
- src/main/java/htsjdk/samtools/cram/build/CramIO.java
- src/main/java/htsjdk/samtools/cram/build/CramSpanContainerIterator.java
- src/main/java/htsjdk/samtools/cram/structure/Container.java
- src/main/java/htsjdk/samtools/cram/structure/ContainerHeaderIO.java
- src/main/java/htsjdk/samtools/cram/structure/ContainerIO.java
- src/main/java/htsjdk/samtools/cram/structure/Slice.java
- src/test/java/htsjdk/samtools/CRAMBAIIndexerTest.java
- src/test/java/htsjdk/samtools/CRAMSliceMD5Test.java
- src/test/java/htsjdk/samtools/CramContainerHeaderIteratorTest.java
- src/test/java/htsjdk/samtools/cram/CRAIEntryTest.java
- src/test/java/htsjdk/samtools/cram/VersionTest.java
- src/test/java/htsjdk/samtools/cram/build/ContainerFactoryTest.java
- src/test/java/htsjdk/samtools/cram/build/ContainerParserTest.java
- src/test/java/htsjdk/samtools/cram/structure/CRAMStructureTestUtil.java
- src/test/java/htsjdk/samtools/cram/structure/ContainerTest.java
- src/test/java/htsjdk/samtools/cram/structure/SliceTests.java
- Encapsulate Container.byteOffset and distribute to Slices on set
- enforce prerequisites to index entry creation
> Follow-up to #1276: Remove multiple versions of Slice/Container getCRAIEntries()

- src/main/java/htsjdk/samtools/BAMIndexMetaData.java
- src/main/java/htsjdk/samtools/CRAMBAIIndexer.java
- src/main/java/htsjdk/samtools/CRAMFileReader.java
- src/main/java/htsjdk/samtools/cram/CRAIEntry.java
- src/main/java/htsjdk/samtools/cram/CRAIIndex.java
- src/main/java/htsjdk/samtools/cram/build/CramContainerHeaderIterator.java
- src/main/java/htsjdk/samtools/cram/build/CramIO.java
- src/main/java/htsjdk/samtools/cram/structure/Container.java
- src/main/java/htsjdk/samtools/cram/structure/ContainerHeaderIO.java
- src/main/java/htsjdk/samtools/cram/structure/ContainerIO.java
- src/main/java/htsjdk/samtools/cram/structure/Slice.java
- src/main/java/htsjdk/samtools/cram/structure/SliceIO.java
- src/test/java/htsjdk/samtools/CRAMBAIIndexerTest.java
- src/test/java/htsjdk/samtools/CramContainerHeaderIteratorTest.java
- src/test/java/htsjdk/samtools/cram/CRAIEntryTest.java
- src/test/java/htsjdk/samtools/cram/structure/CRAMStructureTestUtil.java
- src/test/java/htsjdk/samtools/cram/structure/ContainerTest.java
> CRAM: revert #1326 and fix tests and comments

- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
I, and fellow developers, hit this exception when we've accidentally used an improper VCF extension in an output file path (our most common mistake is using `.gvcf`). I think the exception message needs to be improved so it is clear that Picard is dynamically changing output file type based on the extension of a file path in most cases.
I think the exception bites new users and could be improved so the issue is easier to resolve.
What do you think? Happy to amend!
Current behavior:
```
❯ picard VcfFormatConverter I=/dev/stdin O=demo.gvcf REQUIRE_INDEX=false
[Sun Apr 14 10:14:39 PDT 2019] picard.vcf.VcfFormatConverter INPUT=/dev/stdin OUTPUT=demo.gvcf REQUIRE_INDEX=false VALIDATION_STRINGENCY=SILENT CREATE_INDEX=true    VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 …
```
> Improve exception message for unset VCF output type

- src/main/java/htsjdk/variant/bcf2/BCF2Codec.java
- src/main/java/htsjdk/variant/bcf2/BCFVersion.java
- src/test/java/htsjdk/variant/bcf2/BCF2VersionTest.java
- src/test/java/htsjdk/variant/bcf2/BCFCodecTest.java
Fix/workaround for https://github.com/broadinstitute/gatk/issues/5839. Allows BCFCodec subclasses to override the default version compatibility policy.
> Allow BCFCodec subclasses to provide custom version compatibility.

- src/main/java/htsjdk/samtools/cram/build/CompressionHeaderFactory.java
- src/main/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
> CRAM tiny refactor: remove CramCompressionRecord.tagIds

- src/main/java/htsjdk/samtools/SamPairUtil.java
This PR was inspired by https://github.com/broadinstitute/picard/issues/201 where the error doesn't allow the user to investigate the offending record. By adding the record name to the exception message, the user can investigate more easily and fix the input.
> Added name of offending record to error message in SamPairUtil

- src/main/java/htsjdk/samtools/cram/build/CompressionHeaderFactory.java
- src/main/java/htsjdk/samtools/cram/encoding/external/ExternalByteEncoding.java
- src/main/java/htsjdk/samtools/cram/encoding/external/ExternalEncoding.java
- src/main/java/htsjdk/samtools/cram/encoding/external/ExternalIntegerEncoding.java
- src/main/java/htsjdk/samtools/cram/encoding/external/ExternalLongEncoding.java
> Small CRAM refactor: common ExternalEncoding Abstract Base Class

- src/main/java/htsjdk/samtools/AbstractCRAMIndexer.java
- src/main/java/htsjdk/samtools/CRAMBAIIndexer.java
- src/main/java/htsjdk/samtools/CRAMCRAIIndexer.java
- src/main/java/htsjdk/samtools/CRAMContainerStreamWriter.java
- src/main/java/htsjdk/samtools/CRAMIndexer.java
- src/test/java/htsjdk/samtools/CRAMContainerStreamWriterTest.java
This is to make it possible to write CRAI indexes from `CRAMContainerStreamWriter`, not just BAI indexes (as is the case currently). This is needed by https://github.com/disq-bio/disq/pull/97.
This PR introduces `AbstractCRAMIndexer` that is the common base class of `CRAMBAIIndexer` and `CRAMCRAIIndexer`; and adds a constructor to `CRAMContainerStreamWriter` that takes an `AbstractCRAMIndexer`.
> Support writing a CRAI index from CRAMContainerStreamWriter

- src/main/java/htsjdk/samtools/util/IOUtil.java
Cloud paths are slow to provide readability. This PR removes a readability check that comes right before opening a file. A failure to read the file will result in an error in both cases.
> Removed redundant readability test in unrollPaths method

- src/main/java/htsjdk/samtools/reference/FastaReferenceWriter.java
- src/main/java/htsjdk/samtools/reference/FastaReferenceWriterBuilder.java
- src/main/java/htsjdk/samtools/util/BlockCompressedOutputStream.java
- src/main/java/htsjdk/samtools/util/GZIIndex.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/test/java/htsjdk/samtools/reference/FastaReferenceWriterTest.java
- src/test/java/htsjdk/samtools/util/GZIIndexTest.java
Added the ability for the FastaReferenceWriterBuilder to emit block compressed output streams. Hooked up some basic checks for this into the existing test code as well.
> Added fasta.gz write support to FastaReferenceWriterBuilder

- .travis.yml
With the travis builds now running on multiple Java versions, whichever one finishes last wins at publishing the snapshot build.  This is problematic as there are situations where compiling on Java10 (targeting Java 1.8) still causes issues.  Specifically there are changes to `ByteBuffer` to make some methods return `ByteBuffer` where in Java 8 they returned `Buffer`, and at runtime this causes link/no-such-method problems running on Java 8!
The solution is only to publish if the Java Home is set to openjdk-8.
> Fix to ensure we only publish snapshots compiled with openjdk-8.

- .travis.yml
I think I missed a few semi-colons, I didn't realize I needed those on multi-line shell scripts in the travis config.  Going to merge this as it only tries to publish on master, and see if that fixes things.
> Adding a few more semi-colons in shell in travis config.

- README.md
Updating the readme to mention that we can read 4.3.
> update readme with info about reading vcf 4.3

- src/main/java/htsjdk/samtools/util/Interval.java
- src/test/java/htsjdk/samtools/util/IntervalTest.java
This fixes a regression introduced in https://github.com/samtools/htsjdk/pull/1356. We should get this in before we release. Caught by Picard test `IntervalListTool` testActionsWithInvert.
> Prevent integer overflow in Interval countBases method.

- src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java
- src/test/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilderUnitTest.java
This is the first stage in resolving https://github.com/broadinstitute/gatk/issues/5779. Currently in when we provide a stream (or any non-regular file to resolve) to the `VariantContextWriterBuilder` we set `.setOutputFileType(OutputType.VCF)`. This sidesteps the code in the switch statement designed to this case and throw an exception if indexing on the fly is enabled. It turns out to be a pain point for the users because indexing on the fly is enabled by default. I propose that we push the responsibility of deciding if the output is a stream up to gatk, and then make the stream code in `VariantContextWriterBuilder` consistent with the BAM writer, which only warns and disables indexing if it suspects the file might be a stream.
> Make VariantContextWriterBuilder warn when indexing-on-the-fly is enabled for stream output

- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/main/java/htsjdk/samtools/SAMUtils.java
- src/main/java/htsjdk/samtools/util/SequenceUtil.java
- src/test/java/htsjdk/samtools/SAMUtilsTest.java
The OA tag can be used to record the previous ("Original") alignment information in a SAM record. This PR add a method that will construct the contents of the OA tag from a record, to make the creation of the OA tag easy and uniform.
> - Add a function to calculate the value of the OA tag

- java-style-eclipse.xml
- java-style-intellij.xml
I recently submitted my first PR to this project. I find that the code style is heterogenous which sometimes distracts me from working.
I am used to having an IDE format things but I realize this may not work for everybody. I see some discussion already in #1196 about enforcing certain styles.
My proposal is the following:
- Add a non-binding style guide and people can adopt it if they like.
- This is stolen from [Google's styleguide](https://github.com/samtools/htsjdk/issues/1196) with one mofication => change indent size from 2 to 4 which seem to be the default here.
I'm relying on inertia, with the assumption that people won't reformat files that's already reformatted, and new changes will mostly be in-line with the proposed format.
Hopefully in the long run the style will converge, …
> add style guide for IDE's

- README.md
Adding a statement about code style to the readme.
> adding readme section about style guides

- CODE_OF_CONDUCT.md
I think it's good to explicitly state that we intend to be an inclusive and welcoming project and that part of the responsibility of the maintainers is to maintain a positive community as well as just functional code.
This is the Contributor Covenant code of conduct which is the same one adopted by htsjdk-next.
> Adding a code of conduct document for htsjdk.

- src/main/java/htsjdk/variant/vcf/VCFEncoder.java
- src/test/java/htsjdk/variant/vcf/VCFEncoderTest.java
* Previously vcf genotype fields with a specific number of elements were output as a comma separated list of dots
* This is valid, but uneccessarily long and doesn't provide any additional information.
* Now only a single dot will be emitted.
* ex:  .,.,. -> .
This is a follow up to #1371
> Output missing vcf fields as a single .

- src/main/java/htsjdk/samtools/SAMValidationError.java
Validation errors are not helpful for figuring out how to ignore or fix the problem. 
By emitting the Type of the validation error, this PR helps the user know which validation error needs to be ignored, or search the code to understand the problem.
> Make Validation error emit the validation type that was violated

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
The VCF spec allows `POS` column to take value 0 (or chromosome length + 1), when the event is at a telomere.
Currently the documentation for `public int VariantContext.getStart()` claims it returns a 1-based value, where it seems that 0 is an invalid value.
This PR intends to clarify that, by adding documentation.
(Documentation change, most of the following does not apply)
> add documention for VariantContext.getStart() regarding telomeric events

- src/main/java/htsjdk/samtools/AbstractBAMFileIndex.java
- src/main/java/htsjdk/samtools/CSIIndex.java
- src/test/java/htsjdk/samtools/CachingBAMFileIndexTest.java
Adding a test to https://github.com/samtools/htsjdk/pull/1396
> Optimize AbstractBAMFileIndex#query with test

- src/main/java/htsjdk/samtools/util/AbstractLocusIterator.java
- src/main/java/htsjdk/samtools/util/SamLocusIterator.java
- src/test/java/htsjdk/samtools/util/SamLocusIteratorTest.java
The current version of `AbstractLocusIterator` class works the following way: when new read comes, it completes all accumulated loci with position to the left of the read start. When the flag `includeIndels` is specified, the read starting with insertions won't complete the locus at the position to the left of the read start. So, iterator will keep previous locus, which will store insertion info. 
The bug appears when a read that does not start with insertion(REC1) comes before the read that does start with insertion (REC2) at the same position:
```
REF                     :  ATGC....TGCATGCATGC
REC (Pos=5, CIGAR: 3M)  :          TGC
REC (Pos=5, CIGAR: 3I3M):      TGCATGC
```
In this case the first read without insertion will complete all loci at the previous positions. As a result there …
> Insertions accumulating in AbstractLocusIterator bugfix

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/main/java/htsjdk/variant/variantcontext/VariantContextBuilder.java
- src/main/java/htsjdk/variant/vcf/VCFEncoder.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextBuilderTest.java
- clean up braces while I'm at it.
> fix small bug in VariantContextBuilder

- src/main/java/htsjdk/samtools/reference/AbstractFastaSequenceFile.java
See explanation at https://github.com/EsotericSoftware/kryo/issues/469
This change is a fix for https://github.com/broadinstitute/gatk/issues/6091, which is a regression in GATK running on Spark. I've tested the fix manually with GATK.
/cc @lbergelson
> Make AbstractFastaSequenceFile serializable by Kryo for Spark.

- src/main/java/htsjdk/samtools/util/nio/DeleteOnExitPathHook.java
* Currently we were not catching some commonly thrown exceptions like RuntimeIOException while deleting files at shutdown.
This results in confusing error messages at program exit which can mask the actual cause of failures.
Now we catch all exceptions and output a log message at debug level in case anyone is interested in seeing the failures.
> Suppress all exceptions during DeleteOnExitPathHook

- src/main/java/htsjdk/samtools/SAMRecord.java
I'm processing some data with a reference sequence that has long chromosomes, over the BAI limit.  I ran into this issue where one (likely chimeric) read-pair has an insert size of over 536,870,912 (aka `1<<29`), which causes HTSJDK to throw validation errors.
I looked at the spec and can find nothing supporting a limit on insert size this low.  The SAM section defines it as between `[−2^31 + 1, 2^31 − 1]`, and the BAM section dedicates a full `int32 t` for tlen.
> Updated the max isize to be Integer.MAX_VALUE.

- src/main/java/htsjdk/samtools/util/AbstractRecordAndOffset.java
- src/main/java/htsjdk/samtools/util/SamLocusIterator.java
- src/test/java/htsjdk/samtools/util/SamLocusIteratorTest.java
- as requested per Picard pull request https://github.com/broadinstitute/picard/pull/1370
- necessary to determine whether a RecordAndOffset object is an
(alignment) match, insertion, or deletion when queried by a
SamLocusIterator
- default behavior is preserved by overloading the default constructor
> Added alignment type to RecordAndOffset class

- src/main/java/htsjdk/samtools/util/DiskBackedQueue.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
* The method `IOUtil.deletePaths(Iterable<Path>)` had pathological behavior.
* A `Path` is an `Iterable<Path>` which iterates over the subpaths in the Path.
Therefore, this version was binding instead of the varargs version that takes `Path...`
Then the method would try to delete all of the subpaths in the path which doesn't delete the intended target and could delete random files.
* This is obviously bad behavior.  Fixed by adding an explicit check to see if it's called with a single Path.
* Extracted a new method `deletePath` which is used for deleting a single path.
* Fixes #https://github.com/samtools/htsjdk/issues/1414
> Fixing bad behavior in IOUtil.deletePaths

- src/main/java/htsjdk/samtools/util/CodeUtil.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/test/java/htsjdk/samtools/util/CodeUtilTest.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
> Add a method to conditionally apply a Consumer on a nullable input

- src/main/java/htsjdk/variant/vcf/VCFContigHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFHeader.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
`VCFHeader.getSequenceDictionary` currently throws an exception if one or more of the `Contig` header lines does not have a length field, despite the fact that:
- The VCF spec (v 4.2 and 4.3) does not require a length field (although it states that they are typically present)
- If contig lines are not present in the header it simply returns null
This generally has the effect of making htsjdk tools unable to process files missing length fields without re-headering, which is not always feasible, for example in the case of large multi-sample files in cloud storage.
Fixes https://github.com/samtools/htsjdk/issues/389
- …
> Make VCFHeader not throw exception if contig header lines lack length field

- src/main/java/htsjdk/tribble/util/FTPHelper.java
- src/main/java/htsjdk/tribble/util/HTTPHelper.java
- src/main/java/htsjdk/tribble/util/ParsingUtils.java
- src/main/java/htsjdk/tribble/util/RemoteURLHelper.java
- src/main/java/htsjdk/tribble/util/URLHelper.java
- src/main/java/htsjdk/tribble/util/URLHelperFactory.java
This PR adds a URLHelper factory interface and function on ParsingUtils to set the factory.   It is a replacement or alternative to the previous implementation which used reflection to accomplish the same thing.  Reflection won't work for Java 11 clients,  its illegal across module boundaries for the most part, and bad practice as well.   The reflection API was left in place in case anyone is using it with Java 8.
> Add a URLHelper factory API to ParsingUtils 

- src/main/java/htsjdk/tribble/index/IndexFactory.java
- src/test/java/htsjdk/tribble/index/IndexFactoryTest.java
Prerequisite for https://github.com/broadinstitute/gatk/issues/6161.
> Path-enable IndexFactory.

- src/main/java/htsjdk/samtools/GenomicIndexUtil.java
- src/main/java/htsjdk/samtools/TextualBAMIndexWriter.java
- src/main/java/htsjdk/samtools/util/BlockCompressedFilePointerUtil.java
- src/test/java/htsjdk/samtools/GenomicIndexUtilTest.java
- src/test/java/htsjdk/samtools/util/BlockCompressedFilePointerUtilTest.java
This adds a couple of utility methods to GenomicIndexUtil for use with TextualBAMIndexWriter for easier index debugging. The new output includes the bin level for a given bin, and the genomic territory covered by that bin (along with a minor formatting tweak to put line breaks in the right spot).
Previous output:
```
Reference 0 has n_bin= 2
Ref 0 bin 5291 has n_chunk= 1     Chunk: 1837:0-1837:1 start: 72d0000 end: 72d0001
Ref 0 bin 37450 has n_chunk= 2     Chunk:  start: 68d end: 68d
Chunk:  start: 0 end: 0
```
with this:
```
Reference 0 has n_bin= 2
Ref 0 bin 5291 (bin=5291, level=5, first bin=4681, bin size=16,384 bin range=(9,994,240-10,010,624)) has n_chunk= 1
Chunk: 1837:0-1837:1 start: 72d0000 end: 72d0001
Ref 0 bin 37450 has n_chunk= 2
Chunk:  start: 68d end: 68d
Chunk:  start: 0 …
```
> Improve TextualBAMIndexWriter text output.

- build.gradle
Updating versions of commons-compress and xz library
* update commons-compress 1.4.1 -> 1.19
* update xz 1.5 -> 1.8
> Updating versions of commons-compress and xz library

- src/main/java/htsjdk/samtools/util/SortingCollection.java
SortingCollection keeps insisting that it doesn't have enough memory to buffer files for reading. But this is testably false - if you keep the same number of items in memory, same number of files, and increase the heap size, it continues to insist there is not enough space to buffer.
The existing implementation uses a method that returns the amount of free memory _in the currently allocated heap_.  It does not take into account that the heap may not have been expanded to it's max size as specified by `-Xmx`.
- Breaking changes …
> Improve calculation of available memory when sizing buffers in SortingCollection

- src/test/java/htsjdk/samtools/reference/FastaReferenceWriterTest.java
- src/test/java/htsjdk/samtools/util/BlockCompressedInputStreamTest.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextTestProvider.java
We're within about 20k of the 5MB log output limit on travis - with my cram branch we go way over. A lot of it is the expansion of test method arg values. This change suppresses about 500k of output by wrapping large list inputs in a `Supplier`.
> Reduce test output from BlockCompressedInputStreamTest test method args.

- src/main/java/htsjdk/samtools/SAMFileWriterImpl.java
In case an IOException is encountered during closing of the SAMFileWriter the contained alignment sorter is not properly closed and as a result temporary sorting files potentially end up being left behind. This is fixed by putting the cleanup of the alignment sorter within a finally block.
> SAMFileWriter does not do proper cleanup on IOException

- src/main/java/htsjdk/tribble/index/IndexFactory.java
- src/test/java/htsjdk/tribble/AbstractFeatureReaderTest.java
- src/test/java/htsjdk/tribble/TestUtils.java
- src/test/java/htsjdk/tribble/index/IndexFactoryTest.java
Fixes the issue seen [here](https://github.com/broadinstitute/gatk/issues/6348), along with a new test that fails without the fix. The actual fix is a one line change, the rest of the changes are to fix error messages, and there is a second commit with some other redundant code removed.
> Fix IndexFactory on non-default file system.

- src/main/java/htsjdk/variant/vcf/VCFFileReader.java
small fix: close VCFFileReader in VCFFileReader.getSequenceDictionary(File) using try-with-resource
> fix resource leak in VCFFileReader.getSequenceDictionary

- src/main/java/htsjdk/tribble/readers/TabixReader.java
- src/test/java/htsjdk/tribble/readers/TabixReaderTest.java
I added AutoCloseable to TabixReader so it can be used in a try-with-resource statement.
> TabixReader implements Autoclose

- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
- src/test/java/htsjdk/samtools/SAMSequenceRecordTest.java
This PR only makes the coding easier.
I often find myself testing if a  `Locatable` overlaps a `SamSequenceRecord` . 
`interval.overlaps(new Interval(ssr.getSequenceName(),1,ssr.getSequenceLength()));`
This PR adds the interface 'Locatable' to `SamSequenceRecord` (with start=1 && end=sequenceLength()).
`interval.overlaps(ssr);`
> SamSequenceRecord implements Locatable

- src/main/java/htsjdk/samtools/util/CigarUtil.java
- src/test/java/htsjdk/samtools/util/CigarUtilTest.java
@lbergelson here is the replacement PR for #1453 we discussed earlier today.
@fleharty, @lbergelson and I talked about how to get hard clipping merged ASAP, given that I do not have permissions to push directly to htsjdk, and so cannot make modifications directly to your branch.  He suggested opening up a new PR to replace the old one, which is what this PR is.
> Add option to hard clip read in CigarUtils (replacement for #1453)

- src/main/java/htsjdk/variant/variantcontext/writer/VCFWriter.java
This replaces an operation which does an array copy and then writes the array to an output stream with one that directly writes the array to the output stream without copying anything.  It should help reduce memory load when writing very wide VCFs like in Evoquer.
> Remove unecessary Array copy during VCF write

- src/main/java/htsjdk/variant/vcf/VCFHeader.java
I recently got burned (my own fault) using VCFHeader.getSampleNamesInOrder().  In retrospect I should have seen it, but 'InOrder' could reasonably be interpreted to mean 'VCF order' instead of 'sorted'.  This PR adds javadoc to this method to clarify.
> Add VCFHeader javadoc

- src/main/java/htsjdk/variant/vcf/VCFFileReader.java
- src/main/java/htsjdk/variant/vcf/VCFReader.java
I created a  new ` interface VCFReader  extends Closeable, Iterable<VariantContext>` and I changed VCFFileReader to `class VCFFileReader extends VCFReader` 
The idea is to  use an interface instead of a File-based class to read+query the VCF files
``` 
public interface VCFReader extends Closeable, Iterable<VariantContext> {
public VCFHeader getHeader();
public CloseableIterator<VariantContext> query(final String chrom, final int start, final int end); 
public default CloseableIterator<VariantContext> query(final Locatable locatable) {...}
public boolean isQueryable();
public CloseableIterator<VariantContext> iterator();
}
```
I would like to be able to use some different sources of VCF (one could imagine a **SQL** database, plink ... ) with the same interface. 
My current need is to use a …
> new interface VCFReader (+ VCFFIleReader implements VCFReader)

- src/main/java/htsjdk/tribble/gff/Gff3BaseData.java
- src/main/java/htsjdk/tribble/gff/Gff3Codec.java
- src/main/java/htsjdk/tribble/gff/Gff3Feature.java
- src/main/java/htsjdk/tribble/gff/Gff3FeatureImpl.java
- src/test/java/htsjdk/tribble/gff/Gff3CodecTest.java
- src/test/java/htsjdk/tribble/gff/Gff3FeatureTest.java
- src/test/resources/htsjdk/tribble/gff/canonical_gene.gff3
Four basic changes:
1) Since Gff3BaseData hash is based only on final fields, compute hash once when object is initialized.  This speeds up any code which uses Gff3Feature or Gff3BaseData as a key in a HashMap.
2) Make Gff3BaseData constructor public, (previously package-private) fields private, and add public getter methods to access those fields.
3) Add `decodeShallow` method, which returns only a flat Gff3Feature, which is NOT linked to parent/child/cofeatures.  While this method should not be used for general analysis, it is necessary to preprocess (specifically to add flush directives to) large gff3 files which do not already have flush directives.  Otherwise, the standard decode method will lead to the entire file being held in memory, and GC overhead problems.  
4) Adds score field …
> Gff3BaseData precompute hash and Gff3Codec decodeShallow method

- src/main/java/htsjdk/tribble/gff/Gff3BaseData.java
- src/main/java/htsjdk/tribble/gff/Gff3Codec.java
- src/main/java/htsjdk/tribble/gff/Gff3Constants.java
- src/main/java/htsjdk/tribble/gff/Gff3Feature.java
- src/main/java/htsjdk/tribble/gff/Gff3FeatureImpl.java
- src/main/java/htsjdk/tribble/gff/Gff3Writer.java
- src/main/java/htsjdk/tribble/gff/SequenceRegion.java
- src/test/java/htsjdk/tribble/gff/Gff3CodecTest.java
- src/test/java/htsjdk/tribble/gff/Gff3FeatureTest.java
- src/test/java/htsjdk/tribble/gff/Gff3Writer.java
- src/test/java/htsjdk/tribble/gff/Gff3WriterTest.java
- src/test/resources/htsjdk/tribble/gff/feature_extends_past_circular_region.gff3
- src/test/resources/htsjdk/tribble/gff/url_encoding.gff3
Adds a Gff3 Writer to write out Gff3 files.  Also adjusts the attributes field to account for the fact that attributes map a key to a list of strings, which are separated by commas.  As previously written, the comma separated list was left as a single string, which could later be processed into a list by the user.  This was vulnerable to situations where one of the entries in the list contained an encoded comma (ie %2C), so that after decoding the decoded comma could not be differentiated from the list separating commas.
> Gff3 Writer

- README.md
Removing downstream status badges which haven't been working for a while due to me not fixing our jenkins server configuration.  We shut down the server for now rather than burning money on it.  I should fix it but I'm hoping Carrot will fix the problem for us soon.
> Remove inaccurate downstream status badges

- build.gradle
Currently, htsjdk cannot be built as a submodule of a parent project that also uses gradle. This happens because Gradle only supports the use of the Gradle "wrapper" in a root project, and not in child projects.
See:  https://github.com/gradle/gradle/issues/5816
This change puts conditional logic around the `wrapper` task configuration in the `build.gradle` file so that
it is only invoked when htsjdk is built as a root project (this is applying the workaround suggested in the issue above).
- [X ] Make sure your changes compile and new tests pass locally.
- [ X] Add new tests or update existing ones:
- [ X] Extended …
> only set wrapper version when htsjdk is root project

- src/main/java/htsjdk/samtools/util/FileExtensions.java
The set of recognized file extensions for the FASTA format was  extended, adding in
.fas and .fas.gz.
.fas is a widely used extension for FASTA-formatted files. In previous htsjdk releases, the set of
file extensions used to be modifiable, so we could add additional suffices at runtime. Since this has
been changed to an unmodifiable set, this is no longer an option. .fas (and .fas.gz) are pretty 
common enough to warrant inclusion into the set of predefined extensions.
- The …
> Extend set of valid FASTA format file extensions

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
Actually report the VC alleles as the VC alleles, not the genotype alleles. Current error message is incorrect and not helpful.
> Fix genotype validation error message

- src/main/java/htsjdk/samtools/fastq/BasicFastqWriter.java
- src/test/java/htsjdk/samtools/fastq/BasicFastqWriterTest.java
`PrintStream.checkError()` is called on every write(). Since this flushes the underlying stream, performance when writing fastq files is very poor.
This change defers the call to `checkError()` to `flush()` and `close()` operations.
> BasicFastqWriter: no longer flushing on every write

- src/main/java/htsjdk/samtools/metrics/MetricsFile.java
There's a weird failure state in CrosscheckFingerPrints where it ends without an exception but writes no metrics.  One possible explanation is that the order of exception suppression is suppressing the causal exception and then we're discarding the new exception.
This cleans up the code and changes the order of suppression to match what we want.
> Change try-finally to try-with-resources in MetricsFile.write

- src/main/java/htsjdk/samtools/AbstractSAMHeaderRecord.java
- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/SAMRecordQueryNameComparator.java
- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/main/java/htsjdk/samtools/SAMUtils.java
- src/main/java/htsjdk/samtools/SAMValidationError.java
- src/main/java/htsjdk/samtools/SamFileValidator.java
- src/main/java/htsjdk/samtools/SamPairUtil.java
- src/main/java/htsjdk/samtools/fastq/FastqEncoder.java
- src/main/java/htsjdk/samtools/util/CigarUtil.java
- src/main/java/htsjdk/samtools/util/SequenceUtil.java
- src/test/java/htsjdk/samtools/BAMFileWriterTest.java
- src/test/java/htsjdk/samtools/MergingSamRecordIteratorGroupCollisionTest.java
- src/test/java/htsjdk/samtools/SAMRecordQueryNameComparatorTest.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
- src/test/java/htsjdk/samtools/SAMTextReaderTest.java
- src/test/java/htsjdk/samtools/SAMUtilsTest.java
- src/test/java/htsjdk/samtools/fastq/FastqEncoderTest.java
- src/test/java/htsjdk/samtools/util/CigarUtilTest.java
- src/test/java/htsjdk/samtools/util/SequenceUtilTest.java
... so that callers do not need to adorn their code with useless .name() or .getBinaryTag() calls.
- remove superfluous .name() and .getBinaryTag() calls
> - Make get/set attributes methods take a SAMTag input

- src/main/java/htsjdk/samtools/SAMSequenceDictionary.java
- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
- src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/main/java/htsjdk/samtools/SAMValidationError.java
- src/test/java/htsjdk/samtools/SAMSequenceDictionaryTest.java
- src/test/java/htsjdk/samtools/SAMSequenceRecordTest.java
- src/test/resources/htsjdk/samtools/SamSequenceRecordTest/alternate_contig_names.sam
This is a replacement of PR #956 
see discussion and comments there....
one major difference from that PR: 
- I removed potential problem when providing list of SAMSequenceRecords (didn't make a private copy of list) in commit 30181fb
> Add support for SQ-AN in SAMSequenceDictionary #956

- scripts/htsget-scripts/start-htsget-test-server.sh
The name of the ga4gh reference server docker seems to have changed from ga4gh/htsget-ref to ga4gh/htsget-refserver.  This points to the working image name.
> Fixing htsget-server docker pull

- src/main/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
- src/test/java/htsjdk/variant/variantcontext/GenotypeLikelihoodsUnitTest.java
Instead of requiring anyploidy PLIndex caches to be initialized by an external call to `initializeAnyploidPLIndexToAlleleIndices`, calculate and cache PLIndex allele lists on an as needed basis.  Since `initializeAnyploidPLIndexToAlleleIndices` is public and `anyploidPloidyToPLIndexToAlleleIndices` is protected, they remain in the code to avoid breaking the API, but are deprecated.
> No longer require external call to `initializeAnyploidPLIndexToAlleleIndices`

- src/main/java/htsjdk/samtools/SAMUtils.java
- src/main/java/htsjdk/samtools/SamFlagField.java
- src/main/java/htsjdk/samtools/cram/digest/ContentDigests.java
- src/main/java/htsjdk/samtools/cram/ref/ReferenceSource.java
- src/main/java/htsjdk/samtools/util/BlockCompressedFilePointerUtil.java
- src/main/java/htsjdk/samtools/util/SequenceUtil.java
- src/main/java/htsjdk/variant/vcf/VCFEncoder.java
- src/test/java/htsjdk/variant/vcf/VCFEncoderTest.java
*Setting the local to US in String.format calls that are used to generate computer readable outputs.  Error messages are still written with the default local. 
*Fix for https://github.com/samtools/htsjdk/issues/1510
> Adding Locales to String.format calls

- src/main/java/htsjdk/samtools/DuplicateSetIterator.java
- src/main/java/htsjdk/samtools/SAMRecordDuplicateComparator.java
- src/test/java/htsjdk/samtools/SAMRecordDuplicateComparatorTest.java
The getLibraryId function of SAMRecordDuplicateComparator.java can create race conditions when run multithreaded.
> Fix race condition in SamRecordDuplicateComparator

- src/main/java/htsjdk/samtools/util/SamLocusIterator.java
- src/test/java/htsjdk/samtools/util/SamLocusIteratorTest.java
Updated `accumulateIndels` in `SamLocusIterator` to check if bases in an insertion have base quality >= `qualityScoreCutoff` before adding them to the accumulator. The motivation for this change is that insertions should be filtered and accumulated consistently with matching bases.
> Check base qualities before accumulating inserted bases in SamLocusIterator

- src/main/java/htsjdk/samtools/cram/BAIEntry.java
Fix the not entirely useful CRAM error message that was reported in Picard https://github.com/broadinstitute/picard/issues/1624. Its still pretty cryptic for an end user, since it indicates an internal error or malformed input, but at least its now more precise.
> Fix CRAM BAI creation error message.

- src/main/java/htsjdk/tribble/gff/Gff3Writer.java
the Gff3Writer escapes strings as UTF8. While the format is **correct**, it produces strings that are not expected by some gff3 parsers. For example: it would generate a line like:
```
chr1	ucsc	exon	11869	12227	.	+	.	Parent=transcript%3ANR_148357.t1;Name=NR_148357;biotype=misc_RNA;exon_id=NR_148357%3AE0
```
which is not recognized by "bcftools csq" because it doesn't look for "Parent=transcript%3A" but for "Parent=transcript:"
```
[csq.c:729 gff_id_parse] Could not parse the line, "Parent=transcript:" not present: chr1	ucsc	exon	11869	12227	.	+	.	Parent=transcript%3ANR_148357.t1;Name=NR_148357;biotype=misc_RNA;exon_id=NR_148357%3AE0
```
this PR just  adds a new **protected** method `escapeString` which invokes `encodeString`. It can be overriden to implement a custom way to escape the …
> Gff3Writer : give a chance to implement a custom way to escape strings

- src/main/java/htsjdk/samtools/cram/ref/CRAMLazyReferenceSource.java
Fix slightly misleading rogue paren following contig name in error message.
> Fix error message typo in CRAMLazyReferenceSource

- src/main/java/htsjdk/samtools/util/BlockCompressedOutputStream.java
- src/test/java/htsjdk/samtools/util/BlockCompressedOutputStreamTest.java
Some minor tweaking to make things faster when calling `write(int bite)` on BlockCompressedOutputStream.
> Minor optimization and fix to BlockCompressedOutputStream

- src/main/java/htsjdk/io/HtsPath.java
- src/test/java/htsjdk/io/HtsPathUnitTest.java
Back ported from the GATK implementation.
> Add HtsPath copy constructor and tests.

- src/main/java/htsjdk/samtools/CRAMFileReader.java
- src/test/java/htsjdk/samtools/CRAMIndexQueryTest.java
`CRAMIterator` (which is a closeable iterator) closes it's underlying stream when it's closed (`BAMIterator` doesn't do this; it relies on the enclosing reader to do it). In the case where the underlying stream was supplied to the `CRAMFileReader` constructor directly, rather than through a `File`, this causes serial index queries to fail after the first query, since the `CRAMFileReader` constructors are typed as `InputStream`, and a `SeekableStream` can't be reconstituted from an `InputStream`. These stream constructors are the ones used by `SamReaderFactory` when an input is a non-local file, ie., when it's provided through a SamPathInputResource.
Changing CRAMIterator to not close the stream on `close()` will leak result in leaking streams that are created via other `CRAMFileReader` …
> Fix CRAMFileReader stream management

- src/main/java/htsjdk/samtools/util/BufferedLineReader.java
This PR is meant to start a discussion; nitpicks will be ignored.
When we have very large sequence headers, tools will fail with OOM.
Quoting @jacarey's issue 
> My issue was in a `readHeader`. BufferedLineReader fromString reads into a byte array of `len * max` bytes per char for UTF8, which in my case was greater than `2^31 -1`.
```bash
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
at java.lang.StringCoding.encode(StringCoding.java:344)
at java.lang.StringCoding.encode(StringCoding.java:387)
at java.lang.String.getBytes(String.java:958)
at htsjdk.samtools.util.BufferedLineReader.fromString(BufferedLineReader.java:57)
at …
```
> Support very large sequence dictionaries/headers

- src/main/java/htsjdk/samtools/SAMRecord.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
SAMRecord.mAlignmentBlocks cache field is not invalidated when changing the alignment start.
This causes processes using this field (such as NM tag calculation) to return an incorrect result.
- [N/A] Extended the README / documentation, if necessary
> Invaliding out of date SAMRecord.mAlignmentBlocks cache

- src/main/java/htsjdk/io/IOPath.java
- src/test/java/htsjdk/io/HtsPathUnitTest.java
Discovered by James when inadvertently passing a query interval `chr1:18502956`, which looks like exactly like a URI with no hierarchical part, to GATK as a BAM input.
> Fix IOPath::hasExtension NPE when a URI has no hierarchical part.

- src/test/java/htsjdk/samtools/cram/build/ContainerFactoryTest.java
- src/test/java/htsjdk/samtools/cram/structure/ContainerTest.java
- src/test/java/htsjdk/samtools/reference/FastaReferenceWriterTest.java
- src/test/java/htsjdk/samtools/util/BlockCompressedInputStreamTest.java
- src/test/java/htsjdk/samtools/util/QuietTestWrapper.java
We're close to exceeding the the travis threshold for maximum test log size, since TestNG serialize test method arguments, and they wind up in the travis log. I have branches that add new tests that are failing because of this, so we're pretty close to the max already.
If a data provider generates lots of test data (i.e., `List<SAMRecord>`), the log gets pretty big. This PR adds a new class to use with test methods that have arguments with large serialized representation; adds it to a couple of verbose tests; and updates some existing test that already used a similar strategy. 
Now instead of seeing megabytes of this:
You see this:
> Add QuietTestWrapper to suppress excessive test output that exceeds CI log size threshold.

- build.gradle
Exclude unintentional transitive junit dependency
Our new "dependency free" json parser mjson accidentally includes junit as a dependency because of a bug in it's pom file.
This manually excludes it.
> Exclude unintentional transitive junit dependency

- src/main/java/htsjdk/variant/variantcontext/Allele.java
- src/main/java/htsjdk/variant/variantcontext/ByteArrayAllele.java
- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/test/java/htsjdk/variant/variantcontext/AlleleUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFCodec43FeaturesTest.java
This is the first of a few commits/PR to refactor Allele as intended in the "Large" stale PR https://github.com/samtools/htsjdk/pull/1370
This first commit extracts an interface from Allele that becomes the new Allele common . class ejem interface, and the sole implementation is ByteArrayAllele that as the name states, uses a byte[] array to encode the allele bases, symbolic ID etc like the original Allele class. This change was suggested by @droazen.
ByteArrayAllele is not mean to be use publicly (package protection level). To instantiate it you should use the original Allele static create methods.
It also does some deprecation marking of unused or smelly methods like the "wouldBe*" and acceptableBases families.
@lbergelson Please review.
> Extract Allele into a interface with only one implementation as is currently the case.

- src/main/java/htsjdk/samtools/SAMReadGroupRecord.java
Adding PL Tag 'DNBSEQ' as the Platform/Technology for BGI/MGI.  Leaving BGI as a deprecated enum.
According to the SAM file spec, the proper PL tag for read groups generated on BGI/MGI technology is 'DNBSEQ'. 
We have reports of a ValidateSamFile error caused by this issue: 
https://github.com/broadinstitute/picard/issues/1661
> Adding PL Tag 'DNBSEQ' as the Platform/Technology for BGI/MGI.

- src/main/java/htsjdk/samtools/SAMReadGroupRecord.java
* Deprecate the PlatformValue OTHER since the spec advises omitting the PL field when the technology is not listed in the official ontology.
* A continuation of https://github.com/samtools/htsjdk/pull/1547 which deprecated BGI.
* Alphabetized the list of PL values and added clarifying comments to match the spec.
I kind of hate how I've formatted the new list but I'm not sure what a better way to do it is...
> Deprecate OTHER as a PL value

- .travis.yml
* Switching to use a wrapper around the codecov script that performs validation in order to prevent data breaches in the future.
> Validating the codecov script when downloading.

- src/main/java/htsjdk/beta/io/IOPathUtils.java
- src/main/java/htsjdk/beta/plugin/bundle/Bundle.java
- src/main/java/htsjdk/beta/plugin/bundle/BundleBuilder.java
- src/main/java/htsjdk/beta/plugin/bundle/BundleJSON.java
- src/main/java/htsjdk/beta/plugin/bundle/BundleResource.java
- src/main/java/htsjdk/beta/plugin/bundle/BundleResourceBase.java
- src/main/java/htsjdk/beta/plugin/bundle/BundleResourceType.java
- src/main/java/htsjdk/beta/plugin/bundle/IOPathResource.java
- src/main/java/htsjdk/beta/plugin/bundle/InputStreamResource.java
- src/main/java/htsjdk/beta/plugin/bundle/OutputStreamResource.java
- src/main/java/htsjdk/beta/plugin/bundle/SeekableStreamResource.java
- src/main/java/htsjdk/beta/plugin/package-info.java
- src/main/java/htsjdk/beta/plugin/reads/ReadsBundle.java
- src/main/java/htsjdk/utils/BetaPackage.java
- src/test/java/htsjdk/beta/plugin/bundle/BundleJSONTest.java
- src/test/java/htsjdk/beta/plugin/bundle/BundleResourceTest.java
- src/test/java/htsjdk/beta/plugin/bundle/BundleResourceTestData.java
- src/test/java/htsjdk/beta/plugin/bundle/BundleTest.java
- src/test/java/htsjdk/beta/plugin/reads/ReadsBundleTest.java
`Bundle` is another component of the [CZI](https://github.com/samtools/htsjdk/issues/1482) work, and provides a way to group a set of companion resources (such as a reads/index tuple, or a reference/index/dictionary tuple) into a single object. Each resource in a bundle is backed by either a URI-based `IOPath`; an `InputStream`; a `SeekableStream`; or an `OutputStream`, and has an associated content type string. Each bundle has a single "primary" content type (i.e., "READS", or "VARIANTS", etc.). Bundles that consist of `IOPath`-backed resources can be serialized to and deserialized from JSON:
```
{
"schemaName":"htsbundle",
"schemaVersion":"0.1.0",
"primary":"READS"
"READS":{"path":"myreads.bam","subtype":"BAM"},
"READS_INDEX":{"path":"myreads.bai","subtype":"BAI"},
}
```
Resources can …
> Beta implementation of Bundles.

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
A gate has been added to the getCalledChrCount() method to not count filtered out genotypes.
This fixes a bug in which AC/AN/AF were calculated without respecting if the genotypes were filtered out (and therefore shouldn't be used for calculations)
Re Laura: "It’s probably pretty rare that a user had FT fields they ignored, but if so they should unfilter rather then have some janky arg to ignore FT in annotation."
A genotype filtering unit test has been added since getCalledChrCount() changes based on filtering
- Breaking changes …
> Respect genotype filtering / FT tag when calculating AC/AN/AF

- src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
- src/main/java/htsjdk/samtools/SAMValidationError.java
- src/test/java/htsjdk/samtools/SAMFileHeaderTest.java
As reported in #1477, the SAM specification (§1.3) requires that the keys of header tagged fields match
`/^[A-Za-z][A-Za-z0-9]$/`, but HTSJDK even accepts keys that are not two characters in length.
This PR adds header tag key checking to `SAMTextHeaderCodec`'s validation. It adds a new `HEADER_TAG_INVALID_KEY` entry to `SAMValidationError`, described as representing keys invalid due to either containing invalid characters or being the wrong length. This PR implements a length check but does not implement an alphanumeric character check.
You may prefer to either remove the future intention from the `HEADER_TAG_INVALID_KEY` documentation comment or to implement a character validity check (and add further test cases).
- A bug fix should include a test that previously would have failed and …
> Validate that SAM header tag keys are exactly 2 characters long

- src/main/java/htsjdk/tribble/TribbleIndexedFeatureReader.java
When index file is absent, htsjdk errors with "An index is required, but none found" message
More details [here](https://github.com/samtools/htsjdk/issues/1512)
Error message specifies the expected index file format "An index is required, but none found with file ending .idx".
> add file format to index is required error message

- src/main/java/htsjdk/tribble/TribbleIndexedFeatureReader.java
@lbergelson I realized I had hardcoded the ".idx" file format in the exception message after the [Pull Request](https://github.com/samtools/htsjdk/pull/1567) was merged. 
**Description:**
When index file is absent, htsjdk errors with "An index is required, but none found" message
[here](https://github.com/samtools/htsjdk/issues/1512)
**Fix:**
Error message specifies the expected index file format "An index is required, but none found with file ending " + (index File Format).
> remove hardcoded .idx

- src/main/java/htsjdk/variant/variantcontext/VariantContext.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
Related to https://github.com/broadinstitute/gatk/issues/7111
- Usually, NON_REF alleles will be considered SYMBOLIC. Therefore, if a VariantContext contains the alleles `A*,C,<NON_REF>`, the resulting type would be MIXED. For GVCF files, however, it would be helpful that this would be considered a SNP. When true is passed as the optional argument `ignoreNonRef` to `VariantContext.getType()` NON_REF alleles will be ignored for type determination. If only NON_REF alleles are seen at a given site, the type will remain to be SYMBOLIC.
- Default behavior will not change. This type determination is only performed if `true` is passed for the optional `ignoreNonRef` argument to `VariantContext.getType()`
- Moderate refactoring of VariantContext type determination
- This was necessary because the …
> Added GVCF mode for VariantContext type determination

- src/main/java/htsjdk/tribble/TribbleException.java
- src/main/java/htsjdk/variant/vcf/VCFAltHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFCompoundHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFContigHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFInfoHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFMetaDataLines.java
- src/main/java/htsjdk/variant/vcf/VCFMetaHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFPedigreeHeaderLine.java
- src/main/java/htsjdk/variant/vcf/VCFSampleHeaderLine.java
- src/test/java/htsjdk/variant/vcf/VCFCompoundHeaderLineUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFContigHeaderLineUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFFormatHeaderLineUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderLineUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFInfoHeaderLineUnitTest.java
- src/test/java/htsjdk/variant/vcf/VCFMetaDataLinesUnitTest.java
* VCFMetaDataLines::getValidationErrors returns a map from line -> error useful for checking if version transition would succeed before doing transition
* Add tests for validating header lines
* Add TribbleException.VCFVersionValidationFailure
> Introduce non-throwing version validation methods for VCFHeaderLine

- src/main/java/htsjdk/variant/variantcontext/Allele.java
- src/main/java/htsjdk/variant/variantcontext/SimpleAllele.java
* When we refactored Allele into an interface we made the implementation package protected.
* This caused problems for downstream tools which previously subclassed allele.
* Making the implementation public so that there is an equivalent class to subclass as a base
for downstream implementations.
> Rename ByteArrayAlelle to SimpleAllele and make it public

- src/main/java/htsjdk/samtools/SAMSequenceRecord.java
This code addresses the issue posted [here](https://github.com/samtools/htsjdk/issues/1562) by making setters in SAMSequenceRecord return `this`.
> Allow chaining setters for SAMSequenceRecord

- src/main/java/htsjdk/tribble/gff/Gff3BaseData.java
- src/main/java/htsjdk/tribble/gff/Gff3Codec.java
- src/main/java/htsjdk/tribble/gff/Gff3Constants.java
- src/test/java/htsjdk/tribble/gff/Gff3CodecTest.java
When using a GFF3Reader with DecodeDepth==DEEP, it may use a large amount of memory with attributes that will never be used ("version" ,"tag", etc...). This PR gives the GFF3Codec a chance to set a `Predicate<String>` to only keep a defined set of attributes.
the private attribute of ID_ATTRIBUTE_KEY and NAME_ATTRIBUTE_KEY Gff3BaseData was removed to check if the predicate does not remove them.
a new method `setFilterOutAttribute` was added to GFF3Codec
the `static` attribute of GFF3Codec.parseLine was removed
I added a test codecFilterOutFieldsTest
- The commit message should describe what changed and is targeted …
> add predicate to GFF3Codec to give a chance to filter out some unused attributes

- build.gradle
* update org.xerial.snappy:snappy-java 1.1.7.3-> 1.1.8.4
* This updates to a newer version of snappy which bundles code for M1 Macs.
> Update to new version of the snappy compatible with M1 macs

- src/main/java/htsjdk/samtools/reference/FastaSequenceIndexCreator.java
The `AsciiLineReader.from()` method requires either a block-compressed or positional buffered input stream. If the input stream is neither, then a warning is emitted and the stream is wrapped in a positional buffered stream:
https://github.com/samtools/htsjdk/blob/7719274fe370a51a24e6067de21bbe7e18c160a9/src/main/java/htsjdk/tribble/readers/AsciiLineReader.java#L75-L95
I would like to silence the warning produced when creating a FASTA sequence index by pre-wrapping the stream in a positional buffered stream. This will make my logs that use this method cleaner and I can avoid these warnings:
```
WARNING 2021-08-05 19:54:23     AsciiLineReader Creating an indexable source for an AsciiFeatureCodec using a stream that is neither a PositionalBufferedStream nor a BlockCompressedInputStream
``` …
> Silence AsciiLineReader warning when creating a FASTA sequence index

- src/main/java/htsjdk/samtools/SAMReadGroupRecord.java
The [SAM Spec](https://samtools.github.io/hts-specs/SAMv1.pdf) allows for two additional values for PL inside Read Groups than currently implemented. I added both (`ELEMENT` and `ULTIMA`), in particular so the Ultima pipelines can be updated to use this for their read group values. I also cleaned up the formatting a bit to help readability of the code / comments.
> Added ULTIMA and ELEMENT as valid value for RG-PL according to SAM spec.

- .github/workflows/tests.yml
Codecov has deprecated their old bash uploader.  
See https://about.codecov.io/blog/introducing-codecovs-new-uploader/
This disables it so we don't fail tests until we can fix the problem.
> removing codecov from github actions until we can migrate to the new uploader

- .github/workflows/tests.yml
- src/main/java/htsjdk/samtools/CoordinateSortedPairInfoMap.java
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/test/java/htsjdk/samtools/BAMMergerTest.java
- src/test/java/htsjdk/samtools/CRAMFileWriterTest.java
- src/test/java/htsjdk/samtools/CRAMMergerTest.java
- src/test/java/htsjdk/samtools/reference/FastaSequenceIndexCreatorTest.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamFactoryTest.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
- src/test/java/htsjdk/tribble/index/IndexFactoryTest.java
- src/test/java/htsjdk/tribble/index/IndexTest.java
- src/test/java/htsjdk/tribble/index/tabix/TabixIndexTest.java
- src/test/java/htsjdk/variant/vcf/VCFFileReaderTest.java
- src/test/java/htsjdk/variant/vcf/VCFMergerTest.java
And updated version of #1617 which fixes and also deprecates the method in question.
> Fix temporary directory hijacking or temporary directory information disclosure

- src/main/java/htsjdk/samtools/util/AbstractLocusIterator.java
- src/main/java/htsjdk/samtools/util/IntervalListReferenceSequenceMask.java
* Use SequenceUtil to compare dictionaries
* Remove redundant sorting
@michaelgatzen Could you take a look at this? It turns out that IntervalList.uniqued() also sorts so I removed the other sorting, no good way to avoid it entirely.
I also switched the dictionary check to a more standard method that I hadn't known about, but it's now consistent with how other dictionary matching in CollectWgsMetrics is done.
> Minor improvements to AbstractLocusIterator

- src/main/java/htsjdk/variant/variantcontext/Allele.java
- src/main/java/htsjdk/variant/variantcontext/SimpleAllele.java
* These methods were deprecated in 3.0.0, it seems like that was probably a mistake
since there is no obvious replacement for this useful functionality.
* fixes #1623
> Remove deprecation from Allele.acceptableAlleleBases

- .gitignore
- src/main/java/htsjdk/variant/variantcontext/VariantContextComparator.java
- src/test/java/htsjdk/variant/variantcontext/VariantContextComparatorUnitTest.java
TLDR: This PR will make coordinate VCF sorting in HTSJDK/Picard similar to bcftools.
I tried to use Picard's [SortVcf](https://gatk.broadinstitute.org/hc/en-us/articles/360036858331-SortVcf-Picard) for a VCF comparison task, but I had difficulty because it's output was non-stable based on the full primary information of a variant context (contig, start, and alleles). I finally chose the [`bcftools`](https://samtools.github.io/bcftools/bcftools.html#sort) implementation because it [has a slightly more-stable sorting method](https://github.com/samtools/bcftools/blob/dd937aa89b3998aa4c6fd15375206e19c22d3f20/vcfsort.c#L95-L117). However, I want to ensure future users of Picard don't hit the same issue I did, hence this PR.
Before I write unit tests, is this something you are willing to …
> Use allele info in VariantContext comparisons for stable sorts

- src/test/java/htsjdk/beta/codecs/reads/cram/HtsCRAMCodec30And21QueryTest.java
Fixes https://github.com/samtools/htsjdk/issues/1631. Thanks for the patch @pgrt.
> Fix HtsCRAMCodec test data provider.

- build.gradle
* org.apache.commons:commons-compress:1.19 -> 1.22
> Update commons-compress to close vulnerabilities

- src/main/java/htsjdk/samtools/Cigar.java
- src/test/java/htsjdk/samtools/CigarTest.java
* This solves the confusion of having to find TextCigarCodec.decode()
> Adding Cigar.fromCigarString()

- src/main/java/htsjdk/variant/vcf/VCFEncoder.java
- src/test/java/htsjdk/variant/vcf/VCFEncoderTest.java
* Expose two public methods in VCFEncoder writeGtField and encodeGtField
* Supports https://github.com/broadinstitute/gatk/issues/8160 but seems like a useful thing to be able to do in general
* minor breaking change in VCFEncoder, made methods formatVCFField and buildAlleleStrings static
It is unlikely anyone overrides either of these methods so it should not be a problem.
> Expose the ability to encode a Genotoype into a GT field

- .github/workflows/tests.yml
- README.md
- build.gradle
- src/main/java/htsjdk/samtools/Defaults.java
- src/main/java/htsjdk/samtools/TextTagCodec.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
- src/test/java/htsjdk/samtools/fastq/BasicFastqWriterTest.java
- src/test/java/htsjdk/variant/bcf2/BCF2EncoderDecoderUnitTest.java
Testing on 17 and 19 to see how we do.
> Migrate to Java 17

- src/main/java/htsjdk/samtools/util/AbstractProgressLogger.java
I think printing read names for non-coordinate sorted data is useful, but the log message that "Seen many non-increasing record positions. Printing Read-names as well" is not that useful confusing to both developers and users, especially in an API.  I'd be fine with it being at the debug level.  I just don't want to see this message in my logs every time I use a progress logger that doesn't feed coordinate-sorted data.
> Remove low-value progress logging message

- build.gradle
- src/main/java/htsjdk/beta/io/bundle/BundleJSON.java
- src/main/java/htsjdk/samtools/util/htsget/HtsgetErrorResponse.java
- src/main/java/htsjdk/samtools/util/htsget/HtsgetPOSTRequest.java
- src/main/java/htsjdk/samtools/util/htsget/HtsgetResponse.java
- src/test/java/htsjdk/beta/io/bundle/BundleJSONTest.java
- src/test/java/htsjdk/samtools/util/HtsgetRequestUnitTest.java
There are CVEs reported for mjson, which does not appear to be an actively maintained project:
https://nvd.nist.gov/vuln/detail/CVE-2023-34611
https://github.com/bolerio/mjson/issues/40
and also snappy-java:
https://nvd.nist.gov/vuln/detail/CVE-2023-34453
https://nvd.nist.gov/vuln/detail/CVE-2023-34455
the latest snappy-java has been patched.
This PR does two things:
- It updates to the latest snappy-java
- It migrates from mjson (which appears to be a dead project) to org.json. From what I can tell mjson wasnt being used for anything other than pretty basic JSON object manipulation. In theory these should function about the same.
> Update snappy-java and migrate mjson to org.json to address CVEs

- src/main/java/htsjdk/samtools/SAMRecord.java
- src/main/java/htsjdk/samtools/cram/structure/Slice.java
- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
PR https://github.com/samtools/htsjdk/pull/1194 removed a number of Array.getLength(value) == 0 checks when setting B-array tagged fields, as such empty tagged field values had recently been made explicitly valid in SAM/BAM/CRAM files.
Unfortunately the existing such check in setUnsignedArrayAttribute() was omitted from that PR and has now caused the issue raised in https://github.com/samtools/hts-specs/issues/728. Whatever additional problems might (but probably don't) exist elsewhere in the HTSJDK code for zero-length ML tags, this check for a generic zero-length array was incorrect and should be removed. A test case for setUnsignedArrayAttribute() has also been added.
In grepping for other candidates, I noticed one other potentially incorrect looking Array.getLength invocation.
This …
> Zero len array

- src/main/java/htsjdk/samtools/SAMReadGroupRecord.java
This change is to allow Singular Genomics platform id in read groups. This update adds support for new sequencing vendor platform
- [ X ] Make sure your changes compile and new tests pass locally.
- [ X ] Add new tests or update existing ones:
- [ X ] Extended the README / documentation, if necessary
- [ X ] Check your code style.
- [ X ] Write a clear commit title and message
> add SINGULAR platform to read group

- build.gradle
These were not updated in the last update because they didn't have any CVE's listed but we might as well move them forward.
> Update two remaining out of date dependencies

- src/main/java/htsjdk/samtools/util/Interval.java
- src/main/java/htsjdk/tribble/IntervalFileFeature.java
- src/main/java/htsjdk/tribble/NamedFeature.java
- src/main/java/htsjdk/tribble/bed/BEDFeature.java
This short PR adds an `IntervalFileFeature` interface which extends the `Feature` interface to include a `getName` method common to both lines in bed files and interval_list files. This allows you to be able to parse and work with bed and interval_list file lines uniformly when you need to access metadata in the `name` field. This will be used in an upcoming change in GATK.
> Add IntervalFileFeature for common interface to name in bed or interval_list

- build.gradle
- src/main/java/htsjdk/samtools/util/IOUtil.java
- src/test/java/htsjdk/samtools/util/IOUtilTest.java
- src/test/resources/htsjdk/samtools/io/FofnWithHttpQueryParams.fofn
* Query parameters in an http path were breaking extension detection
> Fix IOUtil.unrollPaths for http paths with query parameters

- src/main/java/htsjdk/io/HtsPath.java
- src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
- src/main/java/htsjdk/samtools/seekablestream/SeekableStreamFactory.java
- src/main/java/htsjdk/tribble/FeatureCodec.java
- src/main/java/htsjdk/tribble/TribbleIndexedFeatureReader.java
- src/main/java/htsjdk/tribble/util/FTPHelper.java
- src/main/java/htsjdk/tribble/util/ParsingUtils.java
- src/test/java/htsjdk/io/HtsPathUnitTest.java
- src/test/java/htsjdk/samtools/seekablestream/SeekableStreamFactoryTest.java
- src/test/java/htsjdk/tribble/AbstractFeatureReaderTest.java
- src/test/java/htsjdk/tribble/util/ParsingUtilsTest.java
* Now when constructing streams it will prefer NIO plugins.
* If no http / ftp plugin exists it will fall back to the htsjdk bulit in
* No longer special casing local files, these will now be handled through NIO as well.
* Deprecating SeekableStreamFactory.isFilePath() since it is no longer used and interacts poorly
with nio filesystem providers
> Re-Ordering priority in SeekableStreamFactory

- src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
* Tests were failing on Debian systems due to ambiguity between boxed and unboxed number comparisons in SAMRecordUnitTest See https://github.com/samtools/htsjdk/issues/1695
* Fix the ambiguity by explicitly converting values to the primitive types before comparing
* Fixes #1695
> Updating tests in SAMRecordUnitTest to remove ambiguity

- src/main/java/htsjdk/samtools/util/IntervalList.java
- src/test/java/htsjdk/samtools/util/IntervalListTest.java
When using `IntervalMergerIterator` to merge many small intervals over a whole contig it can take quite a bit of memory to store each interval. This can happen when trying to convert a GVCF with many reference blocks that are only a few bases in length into an interval list. The intervals are stored only to concat the names of each interval, which is not useful when merging so many intervals. This change keeps memory usage lower by not adding each interval that is iterated over to `toBeMerged` when `concatenateNames` is false.
> reducing memory required in IntervalMergerIterator when not concatting names

- src/main/java/htsjdk/beta/io/IOPathUtils.java
- src/main/java/htsjdk/beta/io/bundle/BundleJSON.java
- src/main/java/htsjdk/beta/io/bundle/BundleResourceType.java
- src/main/java/htsjdk/beta/plugin/reads/ReadsBundle.java
- src/main/java/htsjdk/beta/plugin/variants/VariantsBundle.java
- src/main/java/htsjdk/io/IOPath.java
- src/test/java/htsjdk/beta/io/bundle/BundleJSONTest.java
- src/test/java/htsjdk/beta/io/bundle/BundleTest.java
- src/test/java/htsjdk/beta/plugin/reads/ReadsBundleTest.java
- src/test/java/htsjdk/beta/plugin/variants/VariantsBundleTest.java
- src/test/java/htsjdk/io/IOPathUtilsTest.java
Draft until https://github.com/samtools/htsjdk/pull/1702 goes in.
> Implement VCF bundles.

- src/main/java/htsjdk/samtools/SamReaderFactory.java
- src/test/java/htsjdk/samtools/SamReaderFactoryTest.java
To close #1716, copies the logic from here:
https://github.com/samtools/htsjdk/blob/127f3de750acb6a59fe1ceb5865ebbaee938847f/src/main/java/htsjdk/samtools/SamInputResource.java#L159-L161
> SamReaderFactory opens non-regular File and Path the same way

- src/main/java/htsjdk/beta/codecs/variants/vcf/VCFDecoder.java
- src/test/java/htsjdk/beta/codecs/variants/vcf/HtsVCFCodecTest.java
@cmnbroad This is a fix for an issue that @kshakir discovered.  It dropping the scheme because it's using toPath().toString() instead of either toPath().toUri().toString() or getURIString().  
I added a JIMFS test which fails without the changes.  In a second commit I refactored the code with the optionals a bit.  I think it's clearer.
> Replace toPath().toString() with getURIString()

- build.gradle
update to a newer version of commons-compress to fix a vulnerability
> Update commons compress to a 1.26.0

- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFile.java
- src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java
A small PR that adds a default method to ReferenceSequenceFile.java 
```
getSubsequenceAt(final Locatable loc )
```
shortcut to
```
getSubsequenceAt(loc.getContig(), loc.getStart(), loc.getEnd())
```
> add ReferenceSequenceFile.getSubsequenceAt(final Locatable locatable ) shortcut to getSubsequenceAt(loc.getContig(), loc.getStart(), loc.getEnd())

- src/main/java/htsjdk/beta/codecs/variants/vcf/VCFCodec.java
- src/main/java/htsjdk/beta/plugin/variants/VariantsBundle.java
- src/main/java/htsjdk/samtools/util/FileExtensions.java
- src/test/java/htsjdk/variant/variantcontext/writer/VCFWriterUnitTest.java
VCF suppliers like gnomad, provide VCF with the vcf.bgz extension (eg https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/vcf/exomes/gnomad.exomes.v4.1.sites.chr1.vcf.bgz ) . This PR adds vcf.bgz as a valid extension, defined as  COMPRESSED_VCF_BGZ
> .vcf.bgz as a valid vcf extension in FileExtensions

- src/main/java/htsjdk/tribble/gff/Gff3BaseData.java
- src/main/java/htsjdk/tribble/gff/Gff3Feature.java
- src/test/java/htsjdk/tribble/gff/Gff3CodecTest.java
This PR improves the GFF3 classes:
- 99%  the interesting attributes in a GFF3 file are unique (for example gene_biotype, gene_name, etc...) , so using the function `List<String> getAttribute(key)` can be cumbersome. This PR adds a new function  `Optional<String> getAttr(key)` , it returns an Optional if there is zero or one value. Otherwise an exception is thrown.
- I also added a function `hasAttribute` to test for the presence of an attribute.
- add `implements Locatable` to Gff3BaseData
- Breaking changes should be mentioned …
> improve gff: add Locatable to Gff3BaseData, add 'Optional<String> getAttr(key)' and 'hasAttribute'

- src/main/java/htsjdk/samtools/SamPairUtil.java
- src/test/java/htsjdk/samtools/SamPairUtilTest.java
- Improved documentation to clarify that PairOrientation (in SamUtils) pertains only to reads on the same contig.
- Now getPairOrientation will throw an exception if thrown when the two reads are mapped to different contigs
- Added tests to verify that the exception is thrown in the 4 cases specified.
> SamUtils PairOrientation is confusingly ambiguous about paired reads needing to map to the same contig

- scripts/install-samtools.sh
> update install samtools

- src/main/java/htsjdk/beta/codecs/hapref/fasta/FASTADecoderV1_0.java
- src/main/java/htsjdk/beta/io/bundle/BundleResourceType.java
- src/main/java/htsjdk/beta/plugin/registry/HaploidReferenceResolver.java
- src/main/java/htsjdk/beta/plugin/variants/VariantsBundle.java
- src/main/java/htsjdk/samtools/reference/AbstractFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/FastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java
- src/main/java/htsjdk/samtools/reference/ReferenceSequenceFileWalker.java
- src/main/java/htsjdk/samtools/util/GZIIndex.java
- src/test/java/htsjdk/beta/codecs/hapref/fasta/HaploidReferenceResolverTest.java
- src/test/java/htsjdk/samtools/reference/AbstractFastaSequenceFileTest.java
- src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java
- src/test/java/htsjdk/samtools/reference/ReferenceSequenceFileFactoryTests.java
The main feature implemented here is that a bundle can be used in place of a reference, without executing any code paths that assume that the individual resources are located in the same parent directory (there are a LOT of such code paths, since most of the existing code base makes these assumptions). There are a number of tests added that exist purely to catch any regressions where such assumptions are reintroduced, at lease in the code paths where bundles are enabled.
> Support reference bundles.
