src/java/htsjdk/samtools/cram/structure/ReadTag.java
src/tests/java/htsjdk/samtools/cram/structure/ReadTagTest.java

Fixes https://github.com/samtools/htsjdk/issues/153

Made ReadTag.buf ThreadLocal.

---

src/java/htsjdk/variant/variantcontext/GenotypeBuilder.java

it is still in use and has no replacement

Un-deprecating GenotypeBuilder.log10PError

---

src/java/htsjdk/samtools/SAMReadGroupRecord.java

the update to the SAM spec (samtools/hts-specs#16).

adding Program Group and Platform Model into the Read Group Record after

---

src/java/htsjdk/samtools/SAMRecordSetBuilder.java

the reads created in addUnmappedPair method should have paired flag on

paired flag in addUnmappedPair

---

src/java/htsjdk/samtools/util/IntervalList.java
src/tests/java/htsjdk/samtools/util/IntervalListTest.java

Added functionality to take a list of intervals and split them on band multiples in order to allow for finer granularity of scattering.

Add ability to split intervals on band multiples

---

src/java/htsjdk/samtools/SAMRecordSetBuilder.java
src/java/htsjdk/samtools/filter/InsertSizeFilter.java
src/java/htsjdk/samtools/filter/MappingQualityFilter.java
src/java/htsjdk/samtools/metrics/MetricsFile.java
src/java/htsjdk/samtools/util/CodeUtil.java
src/java/htsjdk/samtools/util/FormatUtil.java
src/java/htsjdk/samtools/util/SequenceUtil.java
src/tests/java/htsjdk/samtools/filter/InsertSizeFilterTest.java
src/tests/java/htsjdk/samtools/filter/MappingQualityFilterTest.java
src/tests/java/htsjdk/samtools/metrics/MetricsFileTest.java
src/tests/java/htsjdk/samtools/util/CodeUtilTest.java
src/tests/java/htsjdk/samtools/util/SequenceUtilTest.java

Added some generally useful utilities, including two new filters and support for ```char``` fields in metrics files.

HTSJDK changes needed for CollectSequencingArtifactMetrics in Picard

---

README.md

Update README.md with license info

---

src/java/htsjdk/variant/variantcontext/VariantContextBuilder.java
src/tests/java/htsjdk/variant/variantcontext/VariantContextBuilderTest.java

Was causing problems when using for testing purposes in GATK.

This fixes a bug in the VariantContextBuilder

---

src/java/htsjdk/variant/vcf/VCFHeader.java
src/tests/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java

There was an issue in addMetaDataLine where it was calling
loadMetaDataMaps after adding a new header line, which repopulated
all metadata again.  This was mostly not a problem since the
majority of the data structures were maps, so the keys/values were
just replaced, however contigs were stored in a list, so the list
effectively got duplicated.  Instead the functionality inside
loadMetaDataMaps got moved into a function to handle one line
at a time, which now gets called by addMetaDataLine for the new
line, and in loadMetaDataMaps inside a for-loop for each
metadata entry.  Only the constructor makes use of loadMetaDataMaps.
Unit test added to VCFHeaderUnitTest.java to ensure the exception
is no longer thrown.
Resolves: 214

Fix addMetaDataLine so sequence dictionary not duplicated

---

src/java/htsjdk/samtools/SamReaderFactory.java

instance (rather than just a File to be used to construct a
default ReferenceSource).
This enables cross-file sharing of a single ResourceSource instance, as
well as the possibility of that instance being a subclass of
ResourceSource with an alternative method of locating reference
sequence data.

Allow SamReaderFactory to be directly supplied with a ReferenceSource

---

src/java/htsjdk/samtools/reference/IndexedFastaSequenceFile.java
src/java/htsjdk/samtools/util/AbstractAsyncWriter.java
src/java/htsjdk/tribble/example/CountRecords.java
src/java/htsjdk/tribble/index/AbstractIndex.java

Performance optimisation for VCF indexing, bam/sam async writing, and retrieving small subsequences from a reference.

Performance enhancement

---

src/java/htsjdk/samtools/liftover/Chain.java

Ignore the id field (which is not used and is duplicated in some old chain files)

Allow comment lines in liftover chain files.

---

src/java/htsjdk/samtools/metrics/Header.java
src/java/htsjdk/samtools/metrics/MetricsFile.java
src/java/htsjdk/samtools/util/Histogram.java
src/java/htsjdk/samtools/util/TestUtil.java
src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java
src/tests/java/htsjdk/samtools/metrics/MetricsFileTest.java
src/tests/java/htsjdk/samtools/metrics/StringHeaderTest.java
src/tests/java/htsjdk/samtools/metrics/VersionHeaderTest.java
src/tests/java/htsjdk/samtools/util/HistogramTest.java
src/tests/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
src/tests/java/htsjdk/variant/vcf/VCFHeaderUnitTest.java

making various classes associated with `MetricsFile` serializable

making several metrics classes serializable

---

src/tests/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java

There will be unit tests that test the functionality of:
extraStrictValidation
validateReferenceBases
validateRSIDs(rsIDs);
validateAlternateAlleles();
validateChromosomeCounts();
The extraStrictValidation method calls all the other methods,
so the test for this makes use of the data providers for the
other tests - I couldn't think of a better way to do this,
and someone could change what extraStrictValidation does, so
it seemed safest to provide a test for it.  Each method has
a pass and a fail test for all the conditions I could think of.
Resolves: #203

Add unit tests for validation methods in VariantContext

---

build.sbt

For backwards compatibility for whomever is releasing, default to non-snapshot.

Enabling -SNAPSHOT versioning including git-hashes.

---

src/tests/java/htsjdk/samtools/CigarTest.java

@eitanbanks this one's for you :-)

added some test cases for the ValidateCigar function

---

src/java/htsjdk/samtools/CRAMFileReader.java
src/java/htsjdk/samtools/CRAMIndexer.java
src/java/htsjdk/samtools/SamFiles.java
src/java/htsjdk/samtools/SamIndexes.java
src/java/htsjdk/samtools/SamReaderFactory.java
src/java/htsjdk/samtools/cram/CRAIEntry.java
src/java/htsjdk/samtools/cram/CRAIIndex.java
src/java/htsjdk/samtools/cram/build/CramIO.java
src/java/htsjdk/samtools/seekablestream/SeekableMemoryStream.java
src/tests/java/htsjdk/samtools/CRAMComplianceTest.java
src/tests/java/htsjdk/samtools/CRAMEdgeCasesTest.java
src/tests/java/htsjdk/samtools/CRAMFileIndexTest.java
src/tests/java/htsjdk/samtools/CRAMFileWriterWithIndexTest.java
src/tests/java/htsjdk/samtools/SamFilesTest.java
src/tests/java/htsjdk/samtools/SamIndexesTest.java
src/tests/java/htsjdk/samtools/cram/CRAIEntryTest.java
src/tests/java/htsjdk/samtools/cram/CRAIIndexTest.java
src/tests/java/htsjdk/samtools/cram/build/CramIOTest.java

Adding random access for CRAM files with CRAI index files. Proposed way is to convert CRAI index into BAI using CRAIIndex.openCraiFileAsBaiStream() method.

Crai index

---

src/java/htsjdk/samtools/cram/CRAIEntry.java
src/tests/java/htsjdk/samtools/cram/CRAIEntryTest.java

Fixed overflow in 'CRAIEntry.fromCraiLine'

---

src/java/htsjdk/samtools/SAMBinaryTagAndUnsignedArrayValue.java
src/java/htsjdk/samtools/SAMBinaryTagAndValue.java
src/java/htsjdk/samtools/SAMRecord.java
src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java

Add SAMRecord deepCopy() method and tests.

---

src/java/htsjdk/samtools/SamPairUtil.java

mates if desired
- Fixing silly compile warning in ProgressLogger

- SetMateInfoIterator throws an exception when it finds missing

---

build.xml
src/java/htsjdk/samtools/ChainedDownsamplingIterator.java
src/java/htsjdk/samtools/ConstantMemoryDownsamplingIterator.java
src/java/htsjdk/samtools/DownsamplingIterator.java
src/java/htsjdk/samtools/DownsamplingIteratorFactory.java
src/java/htsjdk/samtools/HighAccuracyDownsamplingIterator.java
src/java/htsjdk/samtools/util/Murmur3.java
src/tests/java/htsjdk/samtools/DownsamplingIteratorTests.java

Changes to provide multiple downsampling strategies.

---

src/java/htsjdk/samtools/SAMUtils.java
src/tests/java/htsjdk/samtools/SAMUtilsTest.java

Adding useful utility methods to clip overlapping bases for mapped

---

src/java/htsjdk/samtools/CRAMFileReader.java
src/java/htsjdk/samtools/CRAMIterator.java
src/tests/java/htsjdk/samtools/CRAMEdgeCasesTest.java

https://github.com/samtools/htsjdk/issues/394

proppagate ValidationStringency from CRAMFileReader to CRAMIterator

---

src/java/htsjdk/samtools/SAMRecord.java
src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java

Added a test to explore issue #316

investigate issue 316 in htsjdk. 

---

src/java/htsjdk/samtools/util/SequenceUtil.java
src/tests/java/htsjdk/samtools/util/SequenceUtilTest.java

* Add support for IUPAC ambiguous base codes. 
* Add a new function, ```basesMatchWithAmbiguity```, that will consider the set relationships between codes when matching a read base to a reference base. 
* Specifically, if the read base code denotes a subset of the bases represented by the reference base code (e.g. A on read -> R on ref, or M on read -> H on ref), then it's a match.
* Use ```basesMatchWithAmbiguity``` for calculating the NM tag.
* Update documentation and add tests for ```SequenceUtil``` methods.
**Note that this PR changes the NM calculation to be different from samtools. @tfenne @ktibbett @eitanbanks have all OK'd this.**

Handle ambiguous IUPAC chars in reference; change NM calculation

---

src/java/htsjdk/samtools/SAMFileWriterFactory.java

in **SAMFileWriterFactory** : added **set/getCompressionLevel**  , initialized with BlockCompressedOutputStream.getDefaultCompressionLevel(), used where possible : in  makeBAMWriter for example:
```
public SAMFileWriter makeBAMWriter(final SAMFileHeader header, final boolean presorted, final File outputFile) {
return makeBAMWriter(header, presorted, outputFile, this.getCompressionLevel());
}
```
added
* Constructor
* copy constructor
* toString
* clone
while I was here...

compression

---

src/java/htsjdk/samtools/SAMUtils.java
src/tests/java/htsjdk/samtools/SAMUtilsTest.java

fixes the case where mates are not clipped if they start at the same

---

src/java/htsjdk/samtools/util/SamLocusIterator.java

I have not touched the default behavior and have tried to be as minimally invasive
as possible.  But we are seeing OOM problems for tools that use this class and it
is forcing us to up RAM to unacceptably high numbers.

Protect against massive pileups by allowing for a cap on the accumulation

---

src/java/htsjdk/samtools/SAMRecord.java
src/java/htsjdk/samtools/SAMValidationError.java
src/java/htsjdk/samtools/TextTagCodec.java
src/java/htsjdk/samtools/cram/encoding/readfeatures/BaseQualityScore.java
src/java/htsjdk/samtools/cram/encoding/readfeatures/InsertBase.java
src/java/htsjdk/samtools/cram/encoding/readfeatures/ReadBase.java
src/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
src/java/htsjdk/samtools/util/BinaryCodec.java
src/java/htsjdk/samtools/util/DateParser.java
src/java/htsjdk/samtools/util/Log.java
src/java/htsjdk/variant/vcf/VCFEncoder.java

This pull request is focused on resolving occurrences of Sonar rule pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ConsecutiveAppendsShouldReuse
Please let me know if you have any questions.
M-Ezzat

pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse

---

src/java/htsjdk/samtools/BAMFileWriter.java
src/java/htsjdk/samtools/metrics/MetricsFile.java
src/java/htsjdk/samtools/util/IOUtil.java
src/java/htsjdk/tribble/readers/TabixReader.java
src/java/htsjdk/variant/variantcontext/VariantContext.java
src/java/htsjdk/variant/vcf/AbstractVCFCodec.java
src/java/htsjdk/variant/vcf/VCFUtils.java

This pull request is focused on resolving occurrences of Sonar pmd:UseIndexOfChar - Use Index Of Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseIndexOfChar
Please let me know if you have any questions.
M-Ezzat

pmd:UseIndexOfChar - Use Index Of Char

---

src/java/htsjdk/samtools/SAMRecord.java
src/java/htsjdk/samtools/SAMTextHeaderCodec.java
src/java/htsjdk/samtools/TextTagCodec.java
src/java/htsjdk/samtools/cram/structure/CramCompressionRecord.java
src/java/htsjdk/samtools/cram/structure/SubstitutionMatrix.java
src/java/htsjdk/samtools/metrics/MetricBase.java
src/java/htsjdk/samtools/util/ProcessExecutor.java
src/java/htsjdk/samtools/util/StringUtil.java
src/java/htsjdk/tribble/index/interval/IntervalTree.java
src/java/htsjdk/variant/bcf2/BCF2Utils.java
src/java/htsjdk/variant/variantcontext/Genotype.java
src/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
src/java/htsjdk/variant/vcf/VCFEncoder.java
src/java/htsjdk/variant/vcf/VCFHeaderLine.java

This pull request is focused on resolving occurrences of Sonar pmd:AppendCharacterWithChar - Append Character With Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:AppendCharacterWithChar
Please let me know if you have any questions.
M-Ezzat

pmd:AppendCharacterWithChar - Append Character With Char

---

src/java/htsjdk/samtools/CRAMIterator.java
src/java/htsjdk/samtools/cram/build/Sam2CramRecordFactory.java
src/tests/java/htsjdk/samtools/cram/LosslessRoundTripTest.java

see https://github.com/samtools/htsjdk/issues/483 and https://github.com/samtools/htsjdk/issues/455

CRAM lossless roundtrip

---

src/java/htsjdk/samtools/BAMFileReader.java
src/java/htsjdk/samtools/SAMFileReader.java
src/java/htsjdk/samtools/SamStreams.java
src/java/htsjdk/tribble/index/IndexFactory.java
src/java/htsjdk/variant/vcf/AbstractVCFCodec.java
src/tests/java/htsjdk/samtools/SamStreamsTest.java
src/tests/java/htsjdk/samtools/util/BlockCompressedOutputStreamTest.java

Closed a bunch of streams that were left open. Thanks to @d-cameron - these changes come from https://github.com/samtools/htsjdk/pull/482

close opened streams. Thanks to @d-cameron

---

src/java/htsjdk/samtools/DuplicateSetIterator.java

Sorting the inputs may take quite some time, and so it is useful for a
user of the iterator to have logging and progress information to monitor
its progress.
@tfenne @yfarjoun

Add optional logging in duplicate set iterator.

---

src/java/htsjdk/variant/vcf/AbstractVCFCodec.java
src/tests/java/htsjdk/variant/vcf/AbstractVCFCodecTest.java

fixes #555 by reverting to previous behavior

fix the bug in AbstractVCFCodec.canDecodeFile

---

src/java/htsjdk/samtools/BAMFileReader.java
src/java/htsjdk/samtools/BAMIndexer.java
src/java/htsjdk/samtools/SAMBinaryTagAndUnsignedArrayValue.java
src/java/htsjdk/samtools/SAMBinaryTagAndValue.java
src/java/htsjdk/samtools/SAMFileReader.java
src/java/htsjdk/samtools/SAMRecord.java
src/java/htsjdk/samtools/cram/structure/Slice.java
src/tests/java/htsjdk/samtools/BAMIndexWriterTest.java
src/tests/java/htsjdk/samtools/SAMBinaryTagAndValueUnitTest.java
src/tests/java/htsjdk/samtools/SAMRecordUnitTest.java

Fixes https://github.com/samtools/htsjdk/issues/512, https://github.com/samtools/htsjdk/issues/402, and a couple of gratuitous javadoc fixes.

Bug fixes for SAMRecord, SAMBinaryTagAndValue, and BAMIndexer.

---

build.sbt

workaround whatever is causing #573 following advice from https://github.com/sbt/sbt-testng-interface/issues/9
fixes #573

workaround to make publishLocal work again

---

README.md

See e.g. https://github.com/samtools/htsjdk/issues/507

Document lack of support for BCF version 2.2

---

src/java/htsjdk/samtools/SAMFileWriterFactory.java

small fix for factory-method: in SAMFileWiterFactory changed 
`public void setCompressionLevel(final int compressionLevel) `
to
`public SAMFileWriterFactory setCompressionLevel(final int compressionLevel) { `

fix setter in SAMFileWiterFactory

---

.github/PULL_REQUEST_TEMPLATE.md

Propose adding a checkbox for backward compatibility to the PR template.

Proposed addition of a backward compatibility checkbox to the PR template.

---

README.md

Adds a badge to show the latest release on Maven Central

badge for the latest release on maven central

---

src/test/java/htsjdk/samtools/fastq/FastqRecordTest.java

Adding tests for `FastqRecord`. It now has 100% line coverage

100% test coverage for FastqRecord

---

src/main/java/htsjdk/samtools/Defaults.java
src/main/java/htsjdk/samtools/SAMFileWriterFactory.java
src/main/java/htsjdk/samtools/SAMFlag.java
src/main/java/htsjdk/samtools/SAMLineParser.java
src/main/java/htsjdk/samtools/SAMTextWriter.java
src/main/java/htsjdk/samtools/SamFlagField.java
src/main/java/htsjdk/samtools/cram/ref/ReferenceSource.java
src/test/java/htsjdk/samtools/SAMTextWriterTest.java
src/test/java/htsjdk/samtools/SamFlagFieldTest.java

similar to the 'samtools view -X' option.  Use the FLAG_FIELDS_OUTPUT
within the Defaults class to set this.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/samtools/htsjdk/232)

Adding the ability to output the SAM flag field in various formats,

---

src/main/java/htsjdk/samtools/cram/common/CramVersions.java
src/main/java/htsjdk/samtools/cram/structure/ContainerHeaderIO.java
src/main/java/htsjdk/samtools/seekablestream/SeekableMemoryStream.java
src/test/java/htsjdk/samtools/cram/VersionTest.java
src/test/java/htsjdk/samtools/seekablestream/SeekableMemoryStreamTest.java

write CRAM3 by default

---

src/main/java/htsjdk/samtools/DuplicateSetIterator.java
src/main/java/htsjdk/samtools/SAMRecordUtil.java
src/main/java/htsjdk/samtools/SAMUtils.java
src/main/java/htsjdk/samtools/filter/FilteringIterator.java
src/main/java/htsjdk/tribble/util/HTTPHelper.java
src/main/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
src/main/java/htsjdk/variant/variantcontext/filter/FilteringIterator.java
src/main/java/htsjdk/variant/vcf/VCFEncoder.java

- adding more information to some exceptions
- fixing java-doc
- java8 <>
- if/else alignment & braces
- removed use of @Deprecated SAMRecordUtils class
- @Deprecated all methods and members of SAMRecordUtils

Cleaned up SAMUtils (mostly cosmetic)

---

src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java

<edited>
@yfarjoun or @tfenne care to take a look?

Standardizes mate info computation in SAMRecordSetBuilder.

---

README.md

Adding gitter badge to readme for new chat room.

Adding the gitter badge.

---

src/test/java/htsjdk/samtools/CigarOperatorUnitTest.java
src/test/java/htsjdk/samtools/CigarTest.java
src/test/java/htsjdk/samtools/util/CigarElementUnitTest.java

Includes full coverage for `CigarElement` and `CigarOperator`, and new tests for `Cigar` (including explicit tests for already covered methods).

Increase test coverage for Cigar components

---

src/test/java/htsjdk/samtools/SAMReadGroupRecordTest.java

Explicit and/or new tests for SAMReadGroupRecord

Increase test coverage for SAMReadGroupRecord

---

src/main/java/htsjdk/samtools/util/BufferedLineReader.java

`BufferedLineReader` had a `TODO` to be replaced by the `LineNumberReader` instead. This commit simplify the `BufferedLineReader` by extending `LineNumberReader`.
If the original purpose is to remove completely the `BufferedLineReader` class, this commit can also deprecate it and replace the usages for the `LineNumberReader`. Nevertheless, I do not know if this is possible because I haven't check it.

Simplify BufferedLineReader by using LineNumberReader

---

build.gradle
src/main/java/htsjdk/samtools/util/SnappyLoader.java

This addresses the comments from samtools/htsjdk#872, so we can get it across the finish line. It also bumps snappy to the now-latest version.
@tfenne @lbergelson @jacarey, can you take a look?

Respond to review comments from snappy upgrade

---

src/main/java/htsjdk/samtools/SAMRecord.java
src/test/java/htsjdk/samtools/SAMRecordUnitTest.java

Add convenience method hasAttibute() to SAMRecord

---

src/main/java/htsjdk/samtools/SamReaderFactory.java

Simple PR to support references from a `java.nio.Path` abstraction in `SamReaderFactory` setter.

Add SamReaderFactory.referenceSequence(java.nio.Path)

---

src/main/java/htsjdk/samtools/util/AbstractProgressLogger.java

Add method to log the last record recorded.

---

src/main/java/htsjdk/samtools/BAMRecord.java
src/main/java/htsjdk/samtools/BAMRecordCodec.java
src/main/java/htsjdk/samtools/SAMRecordSetBuilder.java
src/main/java/htsjdk/samtools/SamFileValidator.java
src/test/java/htsjdk/samtools/BAMCigarOverflowTest.java
src/test/java/htsjdk/samtools/BAMFileWriterTest.java

white-space cleanup only. not code changes should appear here.

aesthetic changes only

---

src/main/java/htsjdk/samtools/util/SamLocusIterator.java

Fixes https://github.com/fulcrumgenomics/fgbio/issues/381

Bug fix: SamLocusIterator.accumulateIndels printed a newline to stdout

---

src/main/java/htsjdk/samtools/SAMRecord.java

fix a typo in SAMRecord that was bothering me.

fix a typo in SAMRecord

---

src/main/java/htsjdk/samtools/SAMRecord.java

fix the typo in #1036 that broke everything

fix compilation error caused by typo

---

src/test/java/htsjdk/samtools/util/IOUtilTest.java

It's been bothering me that the class is IOUtil and the test is IoUtil.  Renaming it to IOUtilUnitTest.
In a second commit I fixed a bunch of issues intellij was complaining about in the test class.

rename and fix IoUtilTest

---

src/main/java/htsjdk/samtools/SamInputResource.java
src/test/java/htsjdk/samtools/SamReaderFactoryTest.java

fixed spacing, removed dataprovider, added explanation

missed commit from previous PR.

---

src/main/java/htsjdk/variant/variantcontext/writer/VariantContextWriterBuilder.java

See broadinstitute/gatk#2128.
@cmnbroad I was going through code in `GATKVariantContextUtils` and saw this issue.  Is this the htsjdk change you had in mind?

made a protected method public

---

src/main/java/htsjdk/samtools/SamReader.java

* there were a number of fields that should be constants but were not

making public static fields in SamReader.Type final

---

src/main/java/htsjdk/tribble/index/AbstractIndex.java
src/main/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
src/main/java/htsjdk/variant/variantcontext/VariantContext.java

There are two valid plurals of index, Indeces isn't one of them.

fixing spelling error Indeces -> Indices

---

src/main/java/htsjdk/samtools/util/AbstractLocusInfo.java
src/main/java/htsjdk/samtools/util/Interval.java
src/main/java/htsjdk/variant/variantcontext/VariantContext.java
src/main/java/htsjdk/variant/vcf/VCFFileReader.java
src/test/java/htsjdk/samtools/util/IntervalListTest.java
src/test/java/htsjdk/tribble/index/IndexFactoryTest.java

- Wrote constructors to take Locatable as input when appropriate.
- Deprecated strangely named methods
- Extra javadoc etc.

Yf locatable all the things

---

src/main/java/htsjdk/samtools/fastq/FastqEncoder.java
src/test/java/htsjdk/samtools/fastq/FastqEncoderTest.java

Use quality header and SAMTag.CO in FastqEncoder

---

src/main/java/htsjdk/variant/variantcontext/VariantContextBuilder.java

Yf add getters to vcb

---

src/main/java/htsjdk/samtools/SAMSequenceDictionary.java
src/main/java/htsjdk/samtools/SAMSequenceRecord.java
src/main/java/htsjdk/samtools/util/Interval.java
src/main/java/htsjdk/samtools/util/IntervalList.java
src/test/java/htsjdk/samtools/util/IntervalListTest.java

- make interval operations scale better

---

src/main/java/htsjdk/samtools/cram/structure/SubstitutionMatrix.java
src/test/java/htsjdk/samtools/cram/structure/SubstitutionMatrixTest.java

This is mostly comments documenting what this code is doing, and some name changes, but there are no functional changes. A separate follow-on PR will pick up where this one ends.

SubstitutionMatrix class cleanup - part 1.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Updating the issue and PR templates to make the clearer and more helpful as guidelines to submitters.

Updating issue and PR templates

---

README.md

Updating our README to include more detailed description of our api evolution scheme and what the version number means.  This is essentially recording what I've doing and thinking when publishing releases.

Describing what our version number means

---

src/main/java/htsjdk/variant/vcf/AbstractVCFCodec.java
src/test/java/htsjdk/variant/vcf/VCFCodec42FeaturesTest.java
src/test/java/htsjdk/variant/vcf/VCFCodec43FeaturesTest.java
src/test/resources/htsjdk/variant/vcf42HeaderLines.vcf

Fix https://github.com/samtools/htsjdk/issues/1400.

Handle PEDIGREE header lines differently for vcf4.2 vs vcf4.3.

---

src/main/java/htsjdk/samtools/util/Log.java
src/test/java/htsjdk/samtools/util/LogTest.java

- Added option to log with suppliers

---

src/main/java/htsjdk/tribble/index/IndexFactory.java

We accidentally deleted a method when adding path options, adding it and a missed Pathification.

add method we killed accidentally

---

build.gradle

* updating snappy version 1.1.4 -> 1.1.7.3
* it might fix https://github.com/broadinstitute/picard/issues/1238

Update snappy version to 1.1.7.3

---

.travis.yml
scripts/install-samtools.sh
src/test/java/htsjdk/utils/SamtoolsTestUtils.java
src/test/java/htsjdk/utils/SamtoolsTestUtilsTest.java

Install samtools and utilities for using samtools for test validation round-tripping.

Install samtools and add SamtoolsUtils class.

---

build.gradle
src/main/java/htsjdk/variant/utils/BinomialCoefficientUtil.java
src/main/java/htsjdk/variant/variantcontext/GenotypeLikelihoods.java
src/main/java/htsjdk/variant/variantcontext/GenotypeNumLikelihoodsCache.java
src/test/java/htsjdk/variant/variantcontext/GenotypeLikelihoodsUnitTest.java

Modified numLikelihoods calculation for performance

---

src/main/java/htsjdk/variant/vcf/VCFFileReader.java

javadoc oops

---

src/main/java/htsjdk/samtools/util/AbstractRecordAndOffset.java

* Include the value of the offset and length in an error message so you know what the out of bounds value was.
This might help debug a bug the production team is seeing.

Improve error message in AbstractRecordAndOffset

---

src/main/java/htsjdk/samtools/SAMReadGroupRecord.java

Adding legal values for the PL tag of the @rg SAM header line (BGI and OTHER)

Yf add platforms

---

src/main/java/htsjdk/samtools/seekablestream/SeekableStreamFactory.java
src/test/java/htsjdk/samtools/seekablestream/SeekableStreamFactoryTest.java
src/test/java/htsjdk/variant/vcf/VCFFileReaderTest.java

Fix exceptions when trying to create a VCFFileReader on a VCF/.tbi when they're located in a path that contains spaces in the name (see https://github.com/broadinstitute/gatk/issues/6664).
The exception is caused by asymmetric assumptions about the encoding of the input string in different layers. This code in `VCFFileReader` [converts](https://github.com/samtools/htsjdk/blob/bd1b7396ec6bdb1b75c7e6c73fddff46733be2f9/src/main/java/htsjdk/variant/vcf/VCFFileReader.java#L146) the input path to a Uri, and the resulting url-encoded String is passed on, but there is downstream code in `SeekableStreamFactory.getStreamFor` [here](https://github.com/samtools/htsjdk/blob/c380053190616dc804d49d2a95cb2c629bd66fe2/src/main/java/htsjdk/samtools/seekablestream/SeekableStreamFactory.java#L99) that …

Handle spaces in input strings in Tabix and SeekableStreamFactory.

---

src/main/java/htsjdk/io/HtsPath.java
src/main/java/htsjdk/samtools/SamInputResource.java
src/test/java/htsjdk/io/HtsPathUnitTest.java

Rename HtsjdkPath to HtsPath.

---

scripts/htsget-scripts/htsget_config.json
scripts/htsget-scripts/start-htsget-test-server.sh
src/main/java/htsjdk/samtools/HtsgetBAMFileReader.java
src/main/java/htsjdk/samtools/util/htsget/HtsgetPOSTRequest.java
src/main/java/htsjdk/samtools/util/htsget/HtsgetRequest.java
src/test/java/htsjdk/samtools/HtsgetBAMFileReaderTest.java
src/test/java/htsjdk/samtools/util/HtsgetRequestUnitTest.java

Provide classes implementing the new Htsget POST request API, as well as integrate this into the HtsgetBamFileReader class so that it makes use of the API when available.
@lbergelson 

Htsget POST request support

---

src/main/java/htsjdk/samtools/util/IntervalTree.java

* Include the start and end values in an error message in IntervalTree

Improve error message in IntervalTree

---

src/main/java/htsjdk/annotations/BetaAPI.java
src/main/java/htsjdk/annotations/InternalAPI.java
src/main/java/htsjdk/beta/codecs/hapref/fasta/FASTADecoderV1_0.java
src/main/java/htsjdk/beta/codecs/package-info.java
src/main/java/htsjdk/beta/codecs/reads/ReadsCodecUtils.java
src/main/java/htsjdk/beta/codecs/reads/bam/BAMCodec.java
src/main/java/htsjdk/beta/codecs/reads/bam/BAMDecoder.java
src/main/java/htsjdk/beta/codecs/reads/cram/CRAMCodec.java
src/main/java/htsjdk/beta/codecs/reads/cram/CRAMDecoder.java
src/main/java/htsjdk/beta/codecs/reads/cram/CRAMEncoder.java
src/main/java/htsjdk/beta/codecs/reads/sam/SAMCodec.java
src/main/java/htsjdk/beta/codecs/reads/sam/SAMDecoder.java
src/main/java/htsjdk/beta/codecs/reads/sam/samV1_0/SAMEncoderV1_0.java
src/main/java/htsjdk/beta/codecs/variants/vcf/VCFCodec.java
src/main/java/htsjdk/beta/codecs/variants/vcf/VCFDecoder.java
src/main/java/htsjdk/beta/codecs/variants/vcf/VCFEncoder.java
src/main/java/htsjdk/beta/codecs/variants/vcf/VariantsCodecUtils.java
src/main/java/htsjdk/beta/exception/package-info.java
src/main/java/htsjdk/beta/io/package-info.java
src/main/java/htsjdk/beta/package-info.java
src/main/java/htsjdk/beta/plugin/interval/HtsIntervalUtils.java
src/main/java/htsjdk/beta/plugin/package-info.java
src/main/java/htsjdk/beta/plugin/reads/ReadsDecoderOptions.java
src/main/java/htsjdk/beta/plugin/registry/HtsCodecResolver.java
src/main/java/htsjdk/beta/plugin/variants/VariantsDecoderOptions.java

Move the API annotations into a separate package.

Move annotation classes into an annotation package.

---

scripts/explain_sam_flags.py

Updating the scripts/explain_sam_flags.py to use python3
This patch was contributed by @pgrt in https://github.com/samtools/htsjdk/issues/1582

Update explain samflags script to python3

---

src/main/java/htsjdk/samtools/BAMFileReader.java
src/main/java/htsjdk/samtools/CSIIndex.java
src/main/java/htsjdk/samtools/CompressedIndexFileBuffer.java
src/main/java/htsjdk/samtools/IndexFileBufferFactory.java
src/main/java/htsjdk/samtools/SamIndexes.java
src/test/java/htsjdk/samtools/BAMFileReaderTest.java
src/test/java/htsjdk/samtools/SamIndexesTest.java

Fixes https://github.com/samtools/htsjdk/issues/1507.

Support loading of CSI from URLs/streams.

---

src/main/java/htsjdk/samtools/CRAMIterator.java
src/main/java/htsjdk/samtools/cram/build/CRAMReferenceRegion.java
src/main/java/htsjdk/samtools/cram/build/SliceFactory.java
src/main/java/htsjdk/samtools/cram/ref/CRAMLazyReferenceSource.java
src/main/java/htsjdk/samtools/cram/ref/CRAMReferenceSource.java
src/main/java/htsjdk/samtools/cram/ref/ReferenceContext.java
src/main/java/htsjdk/samtools/cram/ref/ReferenceSource.java
src/main/java/htsjdk/samtools/cram/structure/AlignmentContext.java
src/main/java/htsjdk/samtools/cram/structure/CRAMCompressionRecord.java
src/main/java/htsjdk/samtools/cram/structure/CRAMRecordReadFeatures.java
src/main/java/htsjdk/samtools/cram/structure/Slice.java
src/test/java/htsjdk/beta/codecs/reads/cram/CRAMDecoderOptionsTest.java
src/test/java/htsjdk/beta/codecs/reads/cram/CRAMEncoderOptionsTest.java
src/test/java/htsjdk/samtools/CRAMContainerStreamWriterTest.java
src/test/java/htsjdk/samtools/CRAMEdgeCasesTest.java
src/test/java/htsjdk/samtools/CRAMReferencelessTest.java
src/test/java/htsjdk/samtools/CRAMSliceMD5Test.java
src/test/java/htsjdk/samtools/CRAMTestUtils.java
src/test/java/htsjdk/samtools/cram/ref/CRAMReferenceRegionTest.java
src/test/java/htsjdk/samtools/cram/structure/CRAMCompressionRecordTest.java
src/test/java/htsjdk/samtools/cram/structure/CRAMStructureTestHelper.java
src/test/java/htsjdk/samtools/cram/structure/ContainerTest.java
src/test/java/htsjdk/samtools/cram/structure/SliceTests.java

Fixes https://github.com/samtools/htsjdk/issues/1597 (support IGV browse more for CRAM decoding).

Support CRAM reference regions.

---

build.gradle

Update jmfs and commons-lang test dependencies to newer versions

Update test dependencies to newest versions

---

src/main/java/htsjdk/samtools/MemoryMappedFileBuffer.java

* remove unnecessary stream creation
* prevent potential buffer overflow

Minor updates to MemoryMappedFileBuffer

---

.github/workflows/tests.yml

Update github actions to use upload_artifact@4

---

src/main/java/htsjdk/samtools/SamPairUtil.java

feat: set mapq on supplemental alignments in SamPairUtil
